### ISSUE TITLE
Trees doesnt sync with players

### ISSUE THREAD

**Issue by GoldenGuy** [transhumandesign/kag-base#101]
just look at screenshots.
this might bring some disbalance for archers. some players can go higher then the others.
![image](https://user-images.githubusercontent.com/26719582/39698150-53b7dc3a-51fc-11e8-9274-9170aff0074e.png)
![image](https://user-images.githubusercontent.com/26719582/39698152-5685fa5a-51fc-11e8-87b8-dd8b32c533ee.png)

**Comment by Harrison-Miller** [comment]
Good catch. Shouldn't be to bad to fix, I'll look into it.

**Comment by 1bardesign** [comment]
Should be fixed next build pending testing - please re-open if it's not!
