### ISSUE TITLE
Make hearts behave like food and also make  knights hit food like archers

### ISSUE THREAD

**Issue by butterdome** [transhumandesign/kag-base#1017]
**Current in-game behaviour.**

Currently shooting burger or grain is just a funny feature that almost never comes into play... even though it is a very interesting feature

**Proposed Change**

To make it more of an consistent feature i think it should apply to hearts too and maybe would make sense to let knights be able to slash food too so that it flies a short (not als long as with arrows) distance. 

**Additional idea**

An alternative and maybe interesting way  to shoot food would be to make arrows "spike" food and the food would travel the same path as the arrow... and would stick on a wall. this would not only be cool but also make it way easier to aim food to your teammates.

**Comment by eps0003** [comment]
> let knights be able to slash food too so that it flies a short (not als long as with arrows) distance.

I could see this becoming an annoyance. You might accidentally slash away food in the heat of battle. Archers, unlike knights, fight from afar which doesn't make this sort of thing an issue.

**Comment by butterdome** [comment]
OK i see how it could be annoying to slash food... then i want to draw your attention on my "additional idea" - i think it would be a nice feature for archers... the food wouldn't just fly away anymore, instead you could aim it precisely (to your allies or just away from enemies, on walls). it would also disable the feature that people would block arrows with hearts since they would just get hit and healed (so they consume 1 heart...)

**Comment by eps0003** [comment]
It's already a feature (sort of) now that arrows stick into blobs.
![8TqexA7Xgs](https://user-images.githubusercontent.com/30195802/114853916-9ffcf380-9e27-11eb-9ed1-544e8e148bb3.gif)
