### ISSUE TITLE
Falling spikes should not collide with backwards facing platforms

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#1027]
**Describe the feature**

Title. It makes sense. It would allow players to drop spikes on enemies in failed traps, for example.

**Comment by bunniewormy** [comment]
This is a massive buff to defensive playstyle. Currently builders have to decide if they will protect their tower with downward-facing ladders or will not use them to be able to spikedrop incoming enemies. Defensive playstyle will be too easy to abuse with this change. Not a good idea imo
