### ISSUE TITLE
Black block shader should instead use the same shade of black sprite outlines use

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#1045]
**Describe the feature**

I think it would look better if it didn't use a solid black colour and instead shared the same colour used for the outline of most sprites.

![image](https://user-images.githubusercontent.com/30195802/117438666-30d17580-af75-11eb-85b2-7750e1ae4a80.png)

**Comment by AsuMagic** [comment]
this would look like something like this, which I am not terribly convinced about: 
![image](https://user-images.githubusercontent.com/8986152/117446877-095eb680-af3d-11eb-814a-bacb2fa0057e.png)

(tested on staging, edited color by filling in gimp, but i don't think that it would look much different in-engine)

also the map border gradient might look weird with this

**Comment by Shadowblitz16** [comment]
makes it look more like kag classic which imo looks better.
