### ISSUE TITLE
Knight Issues Mega Compendium

### ISSUE THREAD

**Issue by LaikaDawg** [transhumandesign/kag-base#1061]
(EDIT) Yeah I forgot about triple slashing too

**Description**

These are a collective of knight glitches, 
I have no doubt bunnie is going to come here and call them features.

1) Slashing through one block gaps
2) Eating, or opening inventory at all when stunned, 
I asked my favorite THD intern about this one he said its an engine side glitch.
3) Sawjumping, its clearly not a feature bunnie
4) Doors tanking slash damage, although this is less a knight glitch and more of a glitch that effects     knight, it causes you to slash at weird angles to damage them
5) Triple Slashing

**Your Setup:**

(only relevant for graphical/timing/crash related or OS-specific issues, use your best judgement)

- OS: [eg. Windows 10]
- Build Number: [eg. I dont know]
- CPU: [eg. AMD 7 3700x]
- Graphics Hardware: [eg. NVIDIA GeForce RTX 2070s]
- RAM: [eg. 32GB]

Please mention if any of your hardware is modified/overclocked/etc.

**Additional context**

Cope harder

**Comment by LaikaDawg** [comment]
Left set up to flex I play block game with no input lag like the cool homek kids

**Comment by LaikaDawg** [comment]
@AsuMagic another troll issue to close
-bunnie

**Comment by LaikaDawg** [comment]
![external-content duckduckgo com](https://user-images.githubusercontent.com/86168546/122654447-68594300-d119-11eb-8ba4-41c8165c4549.jpg)

**Comment by LaikaDawg** [comment]
"it was concluded that these are not bugs"
oh in that case my bad bro my bad

can you site your sources tho preferably in this thread

**Comment by LaikaDawg** [comment]
Also im truly sorry Asu but Ni wont unban me because he thinks im gonna troll or something, isnt that crazy, so I gotta argue my points with bunnie here. Sorry Father

**Comment by Biurza-Real** [comment]
My very good friend laika just brought these to my attention, truly horrible injustices to the KAG community, as a tier 4 patreon subscriber, I am endorsing these changes, for the betterment of the kag community.

**Comment by Biurza-Real** [comment]
I am also endorsing the unban of my great friend laika from the kag offi discord, I have known him for a very long time, and could not possibly imagine him trolling, and thing he would be a great addition to the discord.

**Comment by Shadowblitz16** [comment]
lol bunnie actually down-voted.
I thought laika was joking about the bunnie part
