### ISSUE TITLE
Cycling through chat messages with arrow keys is slightly broken

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#1065]
**Description**

You can cycle through the messages you sent in chat (if you want to re-send a message) by pressing arrow keys up or down while having chat open. For example, pressing arrow key up 3 times cycles to a message you said before the two most recent messages.

The only issue here is that if you decide to change the order of cycling - eg, press arrow key down to go forward one message - the game will still think youre cycling backwards. This happens only for 1 key press, and after that it goes back to normal.

**Reproduction**

1. Join server
2. Write messages with numbers into chat: 5 -> 4 -> 3 -> 2 -> 1
3. Try opening chat then clicking arrow key up 3 times (should cycle through messages: 1 > 2 > 3) then arrow key down. It should cycle to 2, but instead cycles to 4. Next time you press arrow key down, it'll start cycling forwards in the proper order 3 > 2 > 1.

Same happens with arrow key up if you've been cycling with arrow key down.

**Expected Behavior**

Clicking arrow key up should always iterate backwards, and arrow key down - forwards
(only relevant for graphical/timing/crash related or OS-specific issues, use your best judgement)

**Comment by Nananas** [comment]
Good catch!
I made an engine PR with a fix for this. So will hopefully be merged by the next update.

**Comment by AsuMagic** [comment]
Fix merged engine-side

**Comment by AsuMagic** [comment]
Forgot to close this issue. It was fixed since the last update.
