### ISSUE TITLE
Feature Pitch: Fix for all flags being captured by both teams

### ISSUE THREAD

**Issue by DoctorSnakes** [transhumandesign/kag-base#110]
There have been many times when I have captured the flag only to discover that the other team has captured our flag. Usually you then have to store your flag in a catapult to not stand in base all round.

I propose a fix for this:

1. Remove the ability to place flags in catapult.

2. Make it so that a timer appears when all flags are captured by both teams. When the time runs out, both flags go back to their initial spots. 
![screen-18-05-11-14-17-35](https://user-images.githubusercontent.com/29209584/39924478-353d991e-5528-11e8-92a9-e356b023da56.png)

(I wrote 5 minutes, but maybe 3 or 2 minutes is a better idea)

**Comment by Mazey** [comment]
Not sure if this is the perfect solution, but I'd love a "fix" for this, maybe allow capping at the tent?

**Comment by DoctorSnakes** [comment]
But then there would be no point for your team to capture the other team's flag if they captured your team's flag first. It'd just be a race. However if my approach is made then it can allow a team to stall the other team for 5 minutes, which could allow for builders to rebuild a base. That's what I think anyway

**Comment by benjamingorman** [comment]
It seems like a really good idea. This situation happens pretty frequently in competitive play.

**Comment by Blubahub** [comment]
Maybe, but keep the catapult - otherwise, it's just a race, where once they're safe at spawn the winner is already determined. Instead, I think that you should be able to NEVER launch the flag, instead giving the players the ability to take the flag out of the cata (where the player that does so automatically is holding it)..!

**Comment by terracraft321** [comment]
I agree to this, except the cata. The timer would be useful, it even could be like a small gui popup when the flag gets taken or such which shows the time in a bar.

**Comment by AsuMagic** [comment]
Throwing an idea but it might not be ideal - in this situation there could be a timer like suggested originally, but when time runs out the game instead turns into sudden death, i.e. no respawning.  
This way it might be a little more intense of an ending but it's the same issue as zero tickets left in a tickets gamemode, in that people has to wait for the game to end.

**Comment by 1bardesign** [comment]
This pitch has been successful and received a contributor bounty: `Bounty 3: $20`

The bounty will be awarded to the first submitted working PR addressing this issue. Good luck!

**Comment by norill** [comment]
to whoever implements this - make the flag return time easily configurable for server operators (put a variable in ctf_vars.cfg)

**Comment by Blubahub** [comment]
To whom it may concern: I agree with Asu - it would be best if it went into a sudden death/TDM lightning round..!

**Comment by DoctorSnakes** [comment]
Good luck to whoever makes this!

**Comment by Vivalas** [comment]
Doesn't 81b4bef fix this?

**Comment by 1bardesign** [comment]
It does indeed! Fixed by #120 

Thanks and congrats to @Pirate-Rob for completing the bounty. Will make sure the other bounties are marked as such as well.
