### ISSUE TITLE
Get a Better Host for Official US Servers or Resolve the Host Issues

### ISSUE THREAD

**Issue by Kazaco** [transhumandesign/kag-base#1103]
**Current in-game behaviour.**

If a game last for over an hour on any of the KAG Official CTF US Servers (full server) there is a high possibility that the server will restart due to CPU use.

| Dates | Message |
| --- | --- |
|10/2 9/24  9/18  6/6 | Clients, this server has been using too much cpu (99% > 99%) for too long. Will restart in 5 seconds.. |
| 10/2 10/1 9/25 9/24 9/18 8/29 2/28 | This server will automatically restart in 300 seconds if it does not stop using XXX% of system cpu. (99% is max) |

In the first row are dates where the server actually restarted (can check the logs), while the second row contains dates that issued warnings that the server could restart. The only way to currently to avoid a restart is to either finish the game, have a successful next map vote, or the warning goes away.

**Proposed Change**

Get a better host for official US Servers or resolve the host issues. Next mapping instead of restarting would be a better way to handle this as well.

**Additional context**

The EU servers do not seem to have this issue occur as often as US. I am not aware if AUS servers have this issue. It's difficult to seed US servers so it restarting as often as they do does not help at all.

Thanks!

**Comment by furai** [comment]
@jrgp have a look here.

**Comment by jrgp** [comment]
Hey @Kazaco thanks for the report/feedback.

I've disabled that CPU check on the US official KAGs, and will look into what we can further do to minimize this problem.

Regards
