### ISSUE TITLE
translation error - spectrators slots on russian

### ISSUE THREAD

**Issue by Vlad193** [transhumandesign/kag-base#1163]
spectrators slot on en
![Screenshot_20211113-201547750 (1)](https://user-images.githubusercontent.com/60475782/141655910-5c52b54e-ba60-4b5f-b96f-176647d3d161.jpg)
and "games automates" on rus
![Screenshot_20211113-201820983 (1)](https://user-images.githubusercontent.com/60475782/141655922-d7689a45-a2ad-472e-a0fb-d4cbd94f6155.jpg)
example of the right solution:
"Слоты для спектраторов"
"Спектраторские слоты"

**Comment by GoldenGuy** [comment]
Change it to "Слоты наблюдателей:"

**Comment by Vlad193** [comment]
> Change it to "Слоты наблюдателей:"

**Comment by Vlad193** [comment]
> Change it to "Слоты наблюдателей:"

yes
