### ISSUE TITLE
Feature Pitch: Entering Crates

### ISSUE THREAD

**Issue by Radinyn** [transhumandesign/kag-base#119]
Older players remember this system. It was one of the best things in the entire game! But then it was removed because you could put people who were in the crates in the storage (there was nothing wrong with it, they could still suicide their way to freedom. So my idea is... Bring it back! It was so beautiful!

+ Add Crates to CTF in builder shop :)

**Comment by bunniewormy** [comment]
Yes please, it was my favourite thing in the Fun CTF mod. You could do some pretty sick teamwork with it.

**Comment by Suprejso** [comment]
There's no other choice for me than agreeing with the post above. The system was very fun and you could've done some really fancy stuff using it.

**Comment by Olimarrex** [comment]
i believe it was only ever used as a joke, players only fell for it once.
Players would make a crate, sit inside it, then scream at other players to take him to the enemy base. Then they'd just get murdered by knights once they got there.
I will admit though, it was a Favourite mechanic and I'd love to see it come back.
It would also have great uses for transporting builder up past knights onto enemy walls etc, but I think there needs to be some changes to the mechanic in some way,

**Comment by Radinyn** [comment]
I think there's nothing to change with their mechanics.

**Comment by Olimarrex** [comment]
Won't people get pissed if their team-mates do nothing but sit in a box though?

**Comment by Radinyn** [comment]
Well... people can still stay and do nothing... In the box they at least have a chance of doing something.

**Comment by bunniewormy** [comment]
The problem mentioned by Oli is a typical 'no teamwork' problem. It already happens a lot in pubs, for example - sitting in a catapult for 5min waiting for people to launch you while everyone is in enemy base. I don't think adding crates would increase the amount of players like that.

**Comment by Cuttek** [comment]
Bring it back plz : D

**Comment by Mazey** [comment]
Unless crates get added to CTF (and become somewhat useful), I don't see why uncommenting the crate-entering code (and fixing the storage stuff) should be a bounty...

**Comment by Radinyn** [comment]
I'm pretty sure they are in CTF. Well back in the day they were for sure.

**Comment by Mazey** [comment]
They've only ever been in TTH/WAR.

**Comment by Radinyn** [comment]
I'm pretty sure I played CTF with them.

**Comment by bunniewormy** [comment]
then just add them to CTF

**Comment by terracraft321** [comment]
I also as well like to see this feature, or make it smarter in a way. Maybe if it could be a optional option?

**Comment by 1bardesign** [comment]
I'm quite torn on this, especially as a bounty pitch.

It's clear there's a lot of nostalgia for this, but:

- The code is already present, just removed, and removed deliberately as a result of player complaint (people would "hide" in crates because they thought it was hilarious rather than participate in the game)
- The crates are not present in CTF or TDM, the majority-played game modes, so they would have to be added somewhere (builder shop in CTF, trader shop in tdm?), and would be totally useless in TDM for sure.
- If it's an option (serverside) then there's just going to be inconsistent behaviour.

**Comment by Radinyn** [comment]
I think that much more people were actually hurt by it's removal than how much those few haters were. Why would you add them to TDM, just to ctf there's no need for them in arena gamemode.

Removing a feature is never a good thing. You can clearly see that this post has the highest number of upvotes on github yet, guess people just want it back, and why not give it? It doesn't even has to be a bounty, it just has to come back.

**Comment by AsuMagic** [comment]
If this was implemented back we'd have to make sure of some things:

- We shouldn't be able to put people inside of crates in storages.
- We shouldn't be able to keep something picked up while being in a crate (because of recursively putting people in crates and moving around a handful of people at once that way).
- There should be a way to prevent people from being useless and messing with this instead of playing.
- It sounds a bit OP to be able to safely get two people at once catapulted: Knights can fly much longer than builders can and can deny most of the fall damage. It would make it much easier to wreck havok with catapults.

**Comment by Radinyn** [comment]
It worked perfectly back in the day. The only problem were those people who are useless in the crates, but people still can be useless without the crates! It's the teamwork problem. It wasn't considered too op back then so why would it be op now.

**Comment by Qadric** [comment]
This could be nerfed by making the user suffocate after staying in the crate for a while. Would require a bit more strategy to be able to use it effectively, and would also make sense imo.

**Comment by AsuMagic** [comment]
> This could be nerfed by making the user suffocate after staying in the crate for a while. Would require a bit more strategy to be able to use it effectively, and would also make sense imo.

Sounds actually pretty funny. I wonder if that could work.

> It probably isn't necessary for us to worry about the effectiveness of hiding in crates if enemies are still going to be able to see your health bar when they mouse over it.

It isn't so much about hiding being effective IMO, unless you're throwing in fake crates enemies will easily figure out there's somebody in a crate (especially as they break when you get out).

**Comment by MatheusGodoi** [comment]
> It sounds a bit OP to be able to safely get two people at once catapulted: Knights can fly much longer than builders can and can deny most of the fall damage. It would make it much easier to wreck havok with catapults.
Can't we avoid that making players drop the crate when they sit in catapult? Like when you are a knight holding a keg and try to sleep in a quarter, you will drop the keg on the ground, maybe the same could be made so you cant fly with a builder to the enemy base

**Comment by bunniewormy** [comment]
Honestly guys, what is going to be the point of crates and being able to enter them if you will only be able to be in it for like 30 sec and wont be able to get launched from cata?

**Comment by MatheusGodoi** [comment]
Why not make it so you can enter in the cata inside a crate, like you load a boulder, but when you land, the crate break and you dont take fall damage, so flying as builder is a viable strategy (without needing to wait for chickens) and you cant abuse the knight holding builder combo
