### ISSUE TITLE
Solo Sandbox "crash" after suicide

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1208]
When selecting solo -> Sandbox and suiciding as a Knight or as an Archer via the menu option, the game will not let you continue moving. It will start flashing red circles around every entity and say that there are script errors and to contact the dev team.
It doesn't seem to happen when suiciding as Builder.

**Comment by mugg91** [comment]
This seems to happen in all of the solo modes (Save the princess, tutorial, challenges).

**Comment by Gingerbeard5773** [comment]
This was fixed a day prior to this issue. Check PR #1207
