### ISSUE TITLE
Changing Class while Attacking sometimes causes script error

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1214]
This bug might or might not have been fixed by [Pull Request #1207](https://github.com/transhumandesign/kag-base/pull/1207). Since I can't test it, I decided to post about this issue.

When sitting at a TDM spawn or a tent and repeatedly changing class to archer or knight while holding attack key (to slash or shoot arrows), then the game may eventually have a script error. Occasionally you will just get kicked from the server.

This can happen in TDM, CTF and Sandbox.

I did not have this happen as a builder so far.

Video: https://www.youtube.com/watch?v=5rdycW0LnUI

**Comment by laws65** [comment]
Yep that was fixed by #1207
