### ISSUE TITLE
Feature pitch: builder wars

### ISSUE THREAD

**Issue by Mazey** [transhumandesign/kag-base#122]
**Introduction:** When mechanisms got announced, they were going to be used for single player content and potentially a "builder wars" multiplayer gamemode. I'd like to see this implemented.
**Idea:** 
-A builder-only gamemode which enables building mechanisms.
<details> 
  <summary>Example ruleset which does not necessarily has to be followed</summary>

-Players spawn on the edge of the map like in TTH for the first time
-Each team has a pile of gold blocks (like in classic) like this:
![image](https://user-images.githubusercontent.com/4616537/40852346-77b82338-65ca-11e8-9ad4-e357b8bc92e8.png)
![image](https://user-images.githubusercontent.com/4616537/40852380-96102a6a-65ca-11e8-9470-096eb9075c46.png)
-There is a nobuild-zone at the gold (illustrated by the red area)
![image](https://user-images.githubusercontent.com/4616537/40852336-719c910a-65ca-11e8-92be-115f986ed751.png)
-No CTF shops except for builder shop, storage, tunnel and quarry
-You win by mining all of your enemies' gold
-No way to replenish your pile of gold
-125 seconds build time. 250 wood and 250 stone every 40 seconds, added to your existing inventory automatically. Every 60 seconds after buildtime, 500 wood and stone drops in a crate with a parachute ([ala 2013 war](https://youtu.be/hVeKmBsUSdg?t=111)) at the each team's gold pile.

</details>

**Comment by Radinyn** [comment]
That's something more like for a mod not an addition to the base game.

**Comment by Mazey** [comment]
Care to elaborate why?

**Comment by Radinyn** [comment]
Base gamemodes are mostly around those traditional ways of playing, and  those more arcade ones are made by modders. If you really would like to see it and cannot make it than you should ask on the discord server for some help. This weird gamemode would really stand out from the ones we have now.

PS
Please remove that self given thumbs up emoji, it hurts.

**Comment by Mazey** [comment]
I guess we just don't have the same opinion then :) this doesn't seem arcade-y to me and builder wars is something I think suits vanilla (and so did the devs - seeing it was going to be an official gamemode at some point)

About the emoji, I see where you're coming from. Habit from Discord, I'll remove it.

**Comment by 1bardesign** [comment]
I actually really like this. It'd be like sandbox with a purpose.

**Comment by bunniewormy** [comment]
I wouldn't say it's a good idea.
First of all, the main gamemodes are generally simple [even TTH]. Mechanisms wouldn't work because they're too complex and they honestly take too much time to build and then they're not even dangerous.

The only other builder combat that exists is:
- Pickaxe fighting - which is boring, and the targetting is often broken
- Drills - targetting with it also broken
- Spikes - Killing enemy builders with it is just a baitfest

-1

**Comment by AsuMagic** [comment]
Mechanisms are severely underpowered but it doesn't mean they could be reworked/buffed for such a gamemode. Though as you said they're a bit tedious to build and I'm not sure they have enough variety to be worth using in such a gamemode.

Obviously that's if mechanisms are kept in this state, something like my vehiblock concept could make such a gamemode very interesting :)  
But implementing such a gamemode is "trivial" in comparison to implement dynamic vehicles like that unless it's dumbed down and doesn't get e.g. dynamic block destruction and/or construction.

**Comment by FuzzCat927** [comment]
If this does get added, I've love to see team versions of the mechanism stuff, like a team button only the placing team could use it
Also, 'trapped' versions of the mechanisms would be cool too, like a trapped button could be activated by anyone but the placing team

**Comment by 1bardesign** [comment]
This pitch has a bounty posted for $50! If you would like to get involved, please signal your interest here before getting started.

**Comment by rayneomancer** [comment]
Started working on it

**Comment by furai** [comment]
How's progress on this?

**Comment by Shadowblitz16** [comment]
:D this is cool a new official gamemode

**Comment by Andresian** [comment]
I`ve picked this up for reasons Rayne stated in discord.

**Comment by Andresian** [comment]
Finished working on this. [Repository](https://github.com/Andresian/Builder_Wars1.0/tree/master)

**Comment by Vam-Jam** [comment]
Closed as its been finished for a while, bounty paid and its being tested for release
