### ISSUE TITLE
Players burn when invulnerable

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1221]
**Description**

Respawned players will take burn damage and start panic running immediately, even while still invulnerable.

**Reproduction**

Happens sometimes in CTF. You can produce this situation in Sandbox:

1. Join Sandbox server.
2. build wood background at the spawn point.
3. Shoot a fire arrow at it. Wait until it burns.
4. Open menu and suicide. 
5. If you respawned at the burning structure, you will take burn damage and start panic running immediately.

**Expected Behavior**

You shouldn't take burn damage the first 3 seconds after respawning.

**Comment by mugg91** [comment]
Further testing:

- In solo sandbox, a shark will not damage you while you are in invulnerability. However, if you shoot him from a catapult into the spawn place and then you suicide, it will insta-kill you every time you spawn there.
- In online sandbox, spikes that are already there will not damage you. But spikes that you placed in the same session will damage you even in invulnerability.

Perhaps further testing is needed as this seems to be a more complex problem.

**Comment by mugg91** [comment]
> you're invulnerable to all damage except damage done by yourself

Oh, that explains everything. But not really intuitive. How can a player know such a thing unless a dev tells them.

> as far as i know this is intended in order to prevent spamming suicide which makes you fly into the air when you're invulnerable

What does "fly into the air" mean?

**Comment by bunniewormy** [comment]
> What does "fly into the air" mean?

if i remember correctly, spamming suicide when you're invulnerable makes you fly into the air

> Oh, that explains everything. But not really intuitive. How can a player know such a thing unless a dev tells them.

i doubt any player ever had any problem with this in an actual match

**Comment by mugg91** [comment]
When I spam suicide in Sandbox EU, it doesn't make me fly into the air. Is there a video or further instructions on how to trigger that problem?
