### ISSUE TITLE
Withdrawing wooden items causes sound bug

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1234]
**Description**

If you withdraw certain items that make a wood sound effect (bucket, water bucket, drill, lantern, mine, log...) from storage/dinghy/etc. directly into your backpack, the game will erroneously keep playing a wooden sound effect when you touch the ground.

The bug does not happen if your backpack is full and you withdraw the item into your hand.

It also doesn't seem to happen if you withdraw from a crate, for some reason.

**Reproduction**

https://www.youtube.com/watch?v=qHh5JjoX7Z0

1. Join sandbox.
2. Deposit items mentioned above.
3. Withdraw one or more of those items into your backpack.
4. Wooden sound effect keeps playing.

**Expected Behavior**

Play no wood sound effect.

**Additional Info**

The bug happens also if you activate a bomb or water bomb, ~~put it in a dinghy quickly and then withdraw it~~ and put that directly in your backpack.
Bomb will play a metallic and water bomb a watery sound effect.

**Comment by mugg91** [comment]
Depositing wooden items at a storage or a Dinghy via the "backpack button" will also cause a sound bug, which occurs at the storage's/dinghy's location. But it only happens sometimes. So the exact "steps to reproduce" are not clear yet. It does not happen with a crate because crates don't have the "backpack button".

As an aside, storing an extinguished lantern at a storage will make the storage emit light, even though the lantern isn't really burning.

**Comment by mugg91** [comment]
It seems this only happens in online servers. Not in offline.

**Comment by AsuMagic** [comment]
The bug seems to be that on clients the shapes don't seem to go inactive when put into any inventory when playing online, even though they do in localhost.

**Comment by AsuMagic** [comment]
The out-of-screen logic overrides whether the shape is active or not, which only applies online and is not desired.

**Comment by AsuMagic** [comment]
Should be fixed engine-side by next build
