### ISSUE TITLE
Spikes should not pass Red Barrier 

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1278]
## Current in-game behaviour.

A builder can place falling spikes on a trampoline to make them bounce over to the other team which kills enemies while they are building and awards the builder with coins. I think this should not be possible.

The purpose of the red barrier before match start is that both teams prepare for battle. Spikes being able to pass the red barrier seems like a bug and defeats the purpose of the barrier.

## Proposed Change

Make falling builder blobs get ejected by the red barrier.

## Additional context

Stuff that can pass barrier:
- anything that is team 101 or higher and not tagged "no barrier pass" (any materials, seed, log, grain, animals, greg)
- any builder blobs, if they bounce off trampoline (ladder, spikes, wooden_door, ...)

Noteworthy stuff that doesn't pass barrier:
- food - always gets initialises as team 0.
- egg - gets team set to player who spawns/buys it.
- bison and shark - while you mount it, becomes tagged "no barrier pass"

Sometimes, a careless player will throw materials into the barrier, making them inaccessible. Although this could be addressed, too, this is less of a problem.

When working on a solution, please consider that the map may consist of stuff in the middle (animals, neutral items) that should not get ejected.

**Comment by Vam-Jam** [comment]
https://github.com/transhumandesign/kag-base/pull/1003

**Comment by Gingerbeard5773** [comment]
resolved
