### ISSUE TITLE
Items shouldn't be picked through platforms

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1342]
## Current in-game behaviour.

When an item is hidden behind a platform facing against the picker, the picking up will still happen.

Screenshot - https://i.imgur.com/3cyHqtf.png

In the screenshot, you can pick the blobs behind platforms and bridge, but not behind the door. My suggestion really only applies for the platforms though, not the team bridges.

## Proposed Change

Make a blob to not be pickable if it is behind a platform that faces the picker.
If a player wants to pick a blob behind platforms, they must be destroyed first.

**Comment by mugg91** [comment]
I couldn't find an easy way to implement this yet.

Assuming there is only a platform between `blob1` and `blob2`,
`getMap().rayCastSolid(blob1.getPosition(), blob2.getPosition(), end);` will collide with a platform both when it is facing towards `blob1` as well as when facing away from `blob1`.
Knowing this, I'm not sure yet, why Arrow - which also uses `rayCastSolid()` - doesn't collide with away-facing platform.

**Comment by NoahTheLegend** [comment]
you can get direction of pickup (pointing from blob to each item in end array) and add some kind of 
`if ((deg < 45.0f || deg > 315.0f) && vely > 0.0f) //up		
		{
			return true;
		}`
		this will check the rotation between a 90 degree triangle rotated by 45 for preventing small digit deviation (e.g. rotated to right platform can be having angle of 90.00001 etc)

**Comment by mugg91** [comment]
@NoahTheLegend 
If I understand your solution correctly, this would apply to the whole block.
[So Player B in this image wouldn't be able to pick the item.](https://i.imgur.com/ffTQIFe.png)
I'm interested in a solution where Player A can't pick the item, but Player B can.

Maybe, in addition to your solution, one could use `CShape@ --> ShapePlatformDirection@ getPlatformDirection(int index)` to see where exactly the platform is. 
You could assume two lines, one from the player to the picked item, the other from the one corner to the other corner of the platform block. Check if they cross.
I may look into it when I have more time.

**Comment by NoahTheLegend** [comment]
adding a check if player is beyond the facing direction with x | y coordinates may help
`if (blobPos.x > itemPos.x && (angle_degree < 45.0f || angle_degree > 315.0f)) //up { return true; }`
pick direction passing tru platform which is facing to right, blob's pos is more to right from the item, so it will prevent picking up item in this way
