### ISSUE TITLE
CBlob::getCarriedBlob() and CBlob::DropCarried() don't function as expected

### ISSUE THREAD

**Issue by Pirate-Rob** [transhumandesign/kag-base#139]
As stated, the Carried functions don't work 100% as their name suggests. In theory, these functions should only be interacting with blobs attached to the blob calling them, however, they will instead interact with any blob attached to the blob calling them.

DropCarried() is confirmed to do this, and based on a conversation with Geti, getCarriedBlob() also suffers from a similar issue.

**Comment by Vam-Jam** [comment]
Fixed for the next kag build
