### ISSUE TITLE
Don't place multiple lit bombs in the same inventory slot

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1392]
## Description

Lit bombs can be stacked in groups of 3 per inventory slot.
Since their `mat_bombs` counterparts cannot be stacked, the lit version shouldn't be possible to stack either.
This is only the case with regular bombs, not with water bombs.

## Optional

Since bomb explosions will also explode nearby bombs at the same time, you could make it so if a bomb explodes in your inventory, it explodes any other lit bomb in your inventory, too.

## Reproduction

Go to Sandbox.
Spam `!bomb`
Place as many as you can in your inventory.
Notice you can stack lit bombs in groups of 3.
Notice when your bomb explodes, the other lit bombs you had in your inventory won't explode at the same time.

**Comment by eps0003** [comment]
I dislike this change because allowing lit bombs to stack makes it easier to perform crazy chained bomb jumps.

**Comment by mugg91** [comment]
I thought it might be an odd remnant from ancient versions, but as pointed out by @eps0003  it seems to be an intentional feature. Since it doesn't really need "fixing", might as well close.
