### ISSUE TITLE
Super keg to end stalemates

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#141]
Just some additional firepower.
made it 250 coins (cost more then 2 kegs combined)
a longer timer (makes it easier for the enemy team to intercept so it wont be op)
Heavy weight ( gives it a bigger chance to backfire)
bigger explosion ( builders have a hard time repairing the damage done to the tower,flagroom, etc.) so it can end stalemates in that regard.
buy it at siege shop only( to prevent builders from laddering over the enemy tower and building a knightshop and dropping these would be way to op.) Now they need atleast 50 gold to bring with them to do it.

https://www.youtube.com/watch?v=4JWyDrAS-kk&feature=youtu.be

**Comment by 1bardesign** [comment]
I kind of like this. It would need a new sprite for sure, but it's an interesting way to deal with stalemates problem late-game.

**Comment by bunniewormy** [comment]
No. We have enough explosives in the game already. The building/destructing ratio was perfect before the quarries; the quarries just need to be hugely nerfed now and stuff will be back to being fine.

**Comment by Franrek** [comment]
Kegs don't really help with stalemates, they are way better for defending then attacking. This one would be even better for just dropping from the top of tower.

**Comment by Vikhenzo** [comment]
In general, negative feedback was given but something could be made out of this so please open a new issue if you would like to refine this idea. You can also contribute directly by making the changes yourself and sending us a pull request – We appreciate your interest in KAG.

Thank you! :)
