### ISSUE TITLE
Feature Pitch: Display players in each server in the server browser

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#143]
The data for this is already stored in the API so someone only needs to add it. It could look similar to how I did it in my chrome extension:
![image](https://user-images.githubusercontent.com/30195802/41768610-134b850c-7650-11e8-9516-b33a62c96ce7.png)

**Comment by AsuMagic** [comment]
This would have to be done in-engine, it can't be done with a mod.

**Comment by bunniewormy** [comment]
is this is this ever going to happen?

**Comment by eps0003** [comment]
@bunniewormy I lost my code when updating my files a while ago. It will happen eventually.
