### ISSUE TITLE
Feature pitch: Resupply button

### ISSUE THREAD

**Issue by benjamingorman** [transhumandesign/kag-base#144]
Currently if you want to resupply as builder and you already have mats, you need to first drop your mats or put them in a storage cache. This is awkward and annoying to do repeatedly.

I propose adding a new button to the tent & builder shops which performs the resupply in 1 click, even if you have mats.

Alternatively, the tent & builder shops could just give you the resupply automatically if you walk onto them (respecting the resupply timer).

This would make resupplying as a builder much more comfortable. In competitive play, builders do this anyway, so it would not affect the amount of mats in competitive games. However in pub games it would likely result in an increase in the number of mats available - since not many people use resupplies properly.

Second suggestion:
Players spawning as knight could automatically drop builder mats. In competitive play, people do this anyway; knight players always switch to builder and then back to knight so that builder mats drop. This is annoying to have to do repeatedly. However, this is of course a big increase in the number of mats present in pub games since the majority of knights don't do this (but they should). Interested to hear if people agree with this suggestion.

**Comment by eps0003** [comment]
An issue with the first suggestion might be wanting to get a full restock but the tent/shop automatically tops up what you have, giving you half of what you could potentially get.
I strongly disagree with the second suggestion because it would look like the mats are spawning for no reason. You might as well make the quarry fully automatic. :sweat_smile:

**Comment by makmoud98** [comment]
The main idea here is that we don't want to reward players for AFKing. So your second suggestion is out of the question. However, you first suggestion isn't that bad as it would solve the issue, but it is not a very elegant solution. I could see the button being there for the class shops (replace the change class button with a resupply button if you are already that class), but it wouldn't make sense in the tent where the only button is dead center and everyone is used to it being there. Also, I could imagine having to switch classes in a hurry and accidentally pressing the wrong button.

**Comment by vicenteferrari** [comment]
As this feature pitch is very old and garnered almost no community traction I'm closing the issue to keep things less cluttered. If you wish you may post this again, thanks for your interest in KAG!
