### ISSUE TITLE
[Featuer Pith] superkeg

### ISSUE THREAD

**Issue by Andresian** [transhumandesign/kag-base#148]
so
i think
that this [this](https://forum.thd.vg/threads/superkeg.27746/)
needs to be aded to kag why? cause
1. makes sense - more coin = more gunpowder = bigger boom
2. balanced according to recent builds (can destroy quary)
5, square explodition makes for great penetration.
I hope you add xD

**Comment by Andresian** [comment]
whoops duplicate but I have better reasonsx XD

**Comment by Andresian** [comment]
woah i got bettre idea what about adding minecraft to king arthurs factorio?
cool xDD

**Comment by Andresian** [comment]
also I would like to see battle royale mode with neopets

**Comment by 1bardesign** [comment]
Nice try - please do not spam the github though, this is for serious/genuine involvement only :+1:
