### ISSUE TITLE
water and fire changes i would like to see.

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#149]
This is my thought of waterbombs, water arrows and firearrows.

Because of the total troll abuse water can give make it so everyone gets stunned in the proximity of the explosion.

because of the stonespam(quarry) make firearrows spread fire to everyone when they are in close proximity of each

EDIT :Ehm nvm i forgot about standard ctf players, and only thought about competitive play

**Comment by 1bardesign** [comment]
(Closing this due to the edit)

Modifications like this can be applied on competitive servers as mods; there's no need to bring all hardcore concerns to vanilla.
