### ISSUE TITLE
Make bombarrows deal consistent damage.

### ISSUE THREAD

**Issue by Franrek** [transhumandesign/kag-base#151]
At the moment when you're hit by a bomb arrow standing next to the wall with shield it does no knockback and deals 0hp, when you're not shielding it does 1hp with knockback.  Which is some strange bug I guess.
Here is a video to prove that:
https://www.youtube.com/watch?v=2omWGFJJpPE&feature=youtu.be

Bomb arrows also don't deal damage  to friendly blobs (but destroy backwall behind them) which gets really annoying sometimes. I know it is supposed to be "grief protection" but noone uses bombarrows to grief anyway. Even if someone did the protection wouldn't change much.

Another strange inconsistenty is the lack of stun. Since all other explosives in game stun you/insta-kill you on hit and bombarrows don't, but that's not thing that I certainly want to be changed coz it would buff them a lot.

**Comment by Suprejso** [comment]
I can't think of a clever comment at this as it's 1am but I agree

**Comment by 1bardesign** [comment]
Fixed by #168 thanks to @Pirate-Rob
