### ISSUE TITLE
Gold despawning in Sandbox will trigger Admin Alert

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1513]
## Description

Go to offline Sandbox.
`!gold`
Wait for gold to decay.
When the last pebble of gold disappears, it say something like: "8 gold fell into the void"
or if you held it in hand before: "Player x caused 8 gold to fall into the void"

## Proposed Behavior

Don't show this admin alert message when gold decays by itself.

**Comment by mugg91** [comment]
In theory this can happen in TDM servers, too, if you wait long enough. 
Because `TDM.as` doesn't remove `DecayQuantity.as` from gold like the other gamemodes do but TDM rules aren't tagged `"quick decay"`.
Therefore `DecayQuantity.as` is in effect but only ticks every 66 seconds (2000 ticks).

**Comment by mugg91** [comment]
The bug can be seen in this video.
https://www.youtube.com/watch?v=e-rpXITQNA0

**Comment by eps0003** [comment]
I took a quick look into how this could be resolved but I couldn't think of a straightforward solution that covers all decay situations. For example, `DecayUnused.as` uses `server_SetTimeToDie()` which prevents us from tagging the blob with `"AdminAlertIgnore"` right before it dies.

Even if it were as simple as tagging the blob to fix this issue, we would still need to do the same for every other situation that destroys gold but shouldn't alert an admin. Ideally, we shouldn't be tagging blobs with `"AdminAlertIgnore"` in various scripts. Instead, we should be tagging blobs with the way they are destroyed (e.g. `"decayed"`, `"voided"`, `"burned"`, etc.) so `AlertAdminOnDie.as` can be the one to decide which methods should alert admins.

**Comment by Gingerbeard5773** [comment]
Was this resolved?

**Comment by AsuMagic** [comment]
> Was this resolved?

Doesn't look like it.
