### ISSUE TITLE
Can't place seed as builder, if have no enough resources

### ISSUE THREAD

**Issue by longwoodbow** [transhumandesign/kag-base#1514]
Builder sometimes can't place seed like building.
Edit: Checked this again, and get regularity

Case 1:
1.Put seed to inventory
2.Select wooden platform(or something blob)
3.Build it to use all wood you have
4.Pickup seed
5.Can't place the seed, dialog that need wood to build is shown
It resets on detach, it is happen even select block or put to inventory again

Case 2:
1.Put seed to inventory
2.Build workshop to get less than 150 wood
3.Pickup seed
4.Same thing is happen

I think we need to check BlobPlacement.as or PlacementCommon.as

**Comment by mugg91** [comment]
Can confirm this issue exists.
