### ISSUE TITLE
Crate doesn't autopickup things.

### ISSUE THREAD

**Issue by Hobey** [transhumandesign/kag-base#1516]
Crates used to pickup logs when you walk over them or if you throw the crate at a log. 

Since Build 4234, crates don't do that anymore.

Reproduce:
- Buy a crate in a buildershop
- spawn a log
- Throw the crate at the log, or walk over it.

**Comment by Hobey** [comment]
It seems that crates actually can't autopickup anything anymore. I just noticed with logs first I guess.

**Comment by eps0003** [comment]
Crates don't pick up anything in all the tagged commits I've tried which makes me suspect the regression was caused by an engine change.
