### ISSUE TITLE
Chat commands don't work on staging build.

### ISSUE THREAD

**Issue by Hobey** [transhumandesign/kag-base#1525]
https://user-images.githubusercontent.com/26771587/204141959-54759214-be4c-4423-a828-495f24eea255.mp4

In the video, I first have the non-staging build open on sandbox and commands work; then I open staging and it doesn't work. It also doesn't work on staging if I play locally, or on another server.

**Comment by Hobey** [comment]
(I assume it's not some problem with the way I installed staging, but that might be the case, maybe.)

**Comment by eps0003** [comment]
Closing because staging issue.
