### ISSUE TITLE
[Feature Pitch] In-game Emote Binding Editor

### ISSUE THREAD

**Issue by koihub** [transhumandesign/kag-base#154]
A GUI for easily changing the emote bindings (1-9 keys) in-game, instead of manually finding emote IDs, editing EmoteBindings.cfg, etc. Maybe a dialog in settings, or selecting them in the emote wheel or something.

Also, persist emote bindings after updating (e.g. Move EmoteBindings.cfg out of `/Base` into install folder like mods.cfg and autoconfig.cfg).

**Comment by AsuMagic** [comment]
Pretty sure rewriting emotes to be handled in-scripts could help with changing this kind of stuff.  
It could make emote wheel modification possible and blend nicely with this idea.

**Comment by AsuMagic** [comment]
Currently implementing a new scripted emote menu. I made it generic enough to be used by other mods and to be reused in the future.

IDK if I will implement the emote bindings and menu editor that soon though.

**Comment by Blubahub** [comment]
To note you'd probably want this to be a child script of autoconfig.cfg, so you can easily find, edit, and store it.

**Comment by 1bardesign** [comment]
Sorry for the late note: This pitch has been selected for a bounty.

Definitely talk with @AsuMagic if you are interested in participating to avoid conflicts.
