### ISSUE TITLE
Admin Tab doesn't appear on esc menu.

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#156]
this seems to be a long standing bug from kag where if the user is a admin or mod of a server and doesn't login to rcon and reload security the admin tab doesn't appear in the escape menu.

https://forum.thd.vg/threads/1591-has-admin-powers-but-has-no-admin-tab.24242/
this is fixed however when the user logs in and reloads security.

a simple fix would be to reload security when the server starts up automatically so people do not have to login to recon and reload the security every time the server is started.

**Comment by 1bardesign** [comment]
We debugged this further in #help on discord - the seclevs aren't being sent on join, potentially only to local players.

**Comment by bsjohnson20** [comment]
Short answer = /rcon /reloadseclevs
If ya can of course...

**Comment by Shadowblitz16** [comment]
i know that but it would be nice of the bug was fixed so i don't have to
