### ISSUE TITLE
Sweat drop emote changes color when inside red crate as blue player 

### ISSUE THREAD

**Issue by ParaLogia** [transhumandesign/kag-base#1567]
**Description**

The outline of the sweat drop emote changes color (blue -> red) when inside a red crate as a blue player.

**Reproduction**

1. Join a CTF match on blue team
2. Get inside of a crate
3. Have a red player pick up the crate so that it changes color to red
4. Use the sweat drop emote
5. See the red outline of the sweat drop

Note: This does not seem to happen in solo mode if you enter a crate as a red and use `!team` to change back to blue.

**Expected Behavior**

The emote does not change color

**Video Demonstration**
In this video, the blue player is already inside the crate, and I pick up the crate to turn it red.
[https://youtu.be/x3FnC1gxvEw](https://youtu.be/x3FnC1gxvEw)

**Comment by mugg91** [comment]
Can confirm. It happens in CTF Tutorial.
1) `!team 1` and `!crate`
2) Pick up the crate, then `!team 0`
3) Get inside.
4) Use the sweat emote.

**Comment by AsuMagic** [comment]
Maybe this was fixed for regular player emotes by setting a flag of some sort on the emote `CSpriteLayer` that was not applied to the crate case. As to why the code would be different if that were true though...

**Comment by Gingerbeard5773** [comment]
Quickest easiest solution is to change the pixels RBG by 1. Any reason this would be unpreferred?

**Comment by AsuMagic** [comment]
Not really, except that doing it from code shouldn't be difficult. Or if it is there's something wrong. :P

**Comment by Gingerbeard5773** [comment]
It seems best to post-pone fixing this issue until #1047 has been merged

**Comment by Gingerbeard5773** [comment]
This is resolved by #1047
