### ISSUE TITLE
Can't slash/jab corpses of your own team

### ISSUE THREAD

**Issue by ParaLogia** [transhumandesign/kag-base#1578]
**Description**

Knights can't slash/jab corpses of their own team to get rid of them. This is a problem because it's common for your teammates' corpses to hold your doors open, and it's difficult to clear them out now.

**Reproduction**

1. Join any gamemode and go knight
2. Find a corpse that belongs to your team
3. Try to slash or jab the corpse to damage it
4. The corpse is unaffected

**Expected Behavior**

The corpse should be damaged by your slashes/jabs.

**Video**

https://user-images.githubusercontent.com/22576116/215299279-14094b0b-062c-4506-a3a8-aa46eefb9530.mp4

**Comment by AsuMagic** [comment]
Agreed but corpses currently being held by someone should not be able to be destroyed.

**Comment by ParaLogia** [comment]
> Agreed but corpses currently being held by someone should not be able to be destroyed.

Arguably that could be filed under a separate issue, since the current behavior in master is that you _can_ slash corpses held by anyone (as long as the corpse is a different team from you). 

That seems to be a missed case in #1083/#1102.

**Comment by AsuMagic** [comment]
I wonder what behavior we'd exactly want:

1. Being only able to slash corpses that are _not_ being _held by_ a teammate
2. Being only able to slash enemy corpses that are being held

Probably 1.?

**Comment by ParaLogia** [comment]
Option 1 is better than 2, but another alternative is to prevent slashing of any corpses held by anyone. 

That would be consistent with other slashable held items like boulders and dinghies.
