### ISSUE TITLE
Held items should have momentum when dropped as you die

### ISSUE THREAD

**Issue by AsuMagic** [transhumandesign/kag-base#159]
That is, for example, when getting killed by an archer while you're thrown from a catapult and holding a keg.

When you die, the keg should keep going forward, rather than falling straight vertically.

**Comment by 1bardesign** [comment]
@AsuMagic is this maybe related to the weird forces on bounced items after being grabbed that @MrPotatobird found while working on the crate stuff?..

**Comment by 1bardesign** [comment]
This pitch has a bounty posted for $20! Please signal here if you are interested in contributing.

**Comment by makmoud98** [comment]
working on it now

**Comment by 1bardesign** [comment]
Fixed by #218 - @makmoud98 please get in touch with us securely with your paypal email for bounty payout.
