### ISSUE TITLE
Map-prebuilt background tiles behind flags get destroyed (except dirt)

### ISSUE THREAD

**Issue by AsuMagic** [transhumandesign/kag-base#1604]
**Description**

If you add wooden or stone background tiles behind where a flag base would be in a map `.png`, then the background tiles get turned into air. This probably is caused by the code that also places bedrock tiles beneath flag_base.

**Reproduction**

Load CTF map `Asu_Kelsier_v2`

**Expected Behavior**

Flag backwall should remain

**Screenshots**

![image](https://user-images.githubusercontent.com/8986152/228043450-7ff5bb37-de7d-47ab-ad1d-0444ee4cb3f1.png)
![image](https://user-images.githubusercontent.com/8986152/228043357-7ad3c141-66ed-4273-9496-2cbc389ed1ad.png)

**Your Setup:**

N/A

**Additional context**

N/A

**Comment by Gingerbeard5773** [comment]
Added a fix to this issue in #1580
