### ISSUE TITLE
Rename 'Trap block' to 'Team block'

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#163]
New players keep thinking it traps the enemy below. They end up creating shit traps which give enemy builders a spot to tunnel.

please

**Comment by bunniewormy** [comment]
Team platform would be a better name - it was like that in classic. Maybe we could even change the sprite as well to a team platform? i think the classic one was lots better

**Comment by MrPotatobird** [comment]
That just seems even more mysterious of a name. What the heck's a "team block"?

I'm pretty sure they don't think it traps enemies, they just don't think it through. It says right in the description "only enemies can pass."

**Comment by AsuMagic** [comment]
@Coroz no, spikes are there for a reason. That would be pretty unintuitive.

**Comment by Coroz** [comment]
then make spikes trigger faster because traps suck atm

**Comment by Vikhenzo** [comment]
I can't think of a better name than trap block, but if it indeed cause confusion due to it being unintuitive then something should be done about it.

**Comment by Blubahub** [comment]
@bunniewormy if it was a team platform, 1) veterans may think you can press S to go down, and 2) then it would be burnable, easy for enemies to damage, and kind of useless at that point... That's why it's stone!

**Comment by vicenteferrari** [comment]
This issue has long been gathering dust, in order to keep the repository a bit more organized I'll be closing the issue down, please feel free to post it again if you so wish. Thanks for your interest in KAG!
