### ISSUE TITLE
We cant collect coins on too low map position

### ISSUE THREAD

**Issue by longwoodbow** [transhumandesign/kag-base#1697]
**Description**

We can't collect dropped coins on too low map point.

**Reproduction**

1. Go to the TDM map bunnie_Wojciech_Jaruzelski_v2
2. Open the chest
3. We can't collect coins from chest

**Additional context**

When I was making maps, I suffered about this issue, then I tried to lift up the height of ground.
I guess 7 blocks height is the limit we can collect dropped coins.

**Comment by Vam-Jam** [comment]
Engine patch submitted
