### ISSUE TITLE
Inconsistent font size on tips pane (ctf spectating state)

### ISSUE THREAD

**Issue by NoahTheLegend** [transhumandesign/kag-base#1699]
**Description**

When a match is ended, there is font changed to much bigger one, somewhere before rendering tips

**Reproduction**

Join ctf, stay with enabled tips and die, then trigger the "match" to end
Notice that tips font changed and go out of background pane bounds

**Expected Behavior**

put GUI::SetFont("menu") before rendering tips

**Comment by mugg91** [comment]
I tested in offline.
Being dead and then using chat command `/endgame` will not cause the issue.
But being dead and then the ctf flag being captured will cause it.

It looks like this - https://i.imgur.com/hfx2Z6u.png

**Comment by mugg91** [comment]
https://i.imgur.com/pHzI66z.png
Top right button
