### ISSUE TITLE
[Feature pitch] Better admin interface

### ISSUE THREAD

**Issue by AsuMagic** [transhumandesign/kag-base#170]
It would be good to be able to report a player to admins currently online on the server, so they can respond more quickly (especially as you can't always watch the chat).

This would offer features for a few cases:
- `!report <username OR character name>` (shortcut `!r` *and* an in-game shortcut so you can report a player by hovering them): this would do a noticeable bell sound for every admin, with username, character name and team displayed in their chat (but _not_ in the user chat).
- Vote-kicking a player would automatically cause a report.
- Muted players cannot report.
- `!moderate <username OR character name>`: go directly into spectator mode *and* follow the reported player.
- `!moderate` (shortcut `!m`): with no parameter, picks the last report available and go directly into spectator mode *and* follow the reported player.
- Moderation and report chat commands are _not_ visible to the chat (even if they fail), but other admins should be aware when another admin has used `!moderate` for a given report.
- Close matches are picked directly for the `!report` and `!moderate` commands.
- Translation support.
- Spam throttle: amount of people reported in a given time span, amount of reports per person in a given time span.

**Comment by 1bardesign** [comment]
Sorry for the late note: This pitch has been selected for a bounty.

Definitely talk with @Vikhenzo if you are interested in participating to avoid conflicts.

**Comment by 1bardesign** [comment]
#197 and #213 finish this off nicely - I'm not sure how translation support is but I'll just tag @Diprog and @AsuMagic in for the moment to review the code, and close this for now. Thank you @Vikhenzo ! Please get in touch with paypal details.
