### ISSUE TITLE
Change trap block collisions

### ISSUE THREAD

**Issue by GoldenGuy** [transhumandesign/kag-base#172]
When player walks on trap blocks some physics glitches happens (like, player slows down, animation jitters). Wouldnt it be better to use dummy tile collision, like used in obstructor? This maybe also be applied for platforms.

**Comment by AsuMagic** [comment]
Huh, I don't think we have dummy tiles appropriate for platforms though.

**Comment by GoldenGuy** [comment]
It will be better if we had them ;)

**Comment by eps0003** [comment]
Same with upwards facing platforms

**Comment by Harrison-Miller** [comment]
1. trap blocks are no more
2. I did a lot of work on platform collision that I believe at least partially resolved some of the bouncing.
