### ISSUE TITLE
[Feature pitch] Adding a team scramble vote option

### ISSUE THREAD

**Issue by ghost** [transhumandesign/kag-base#174]
I'd say that about 75% approval would have to be reached, teams are randomly scrambled if people feel like it's unbalanced. Maybe if a team votes unanimously it does it anyway?

**Comment by makmoud98** [comment]
players hate switching sides, it would never pass even at 50% I would wager

**Comment by Mazey** [comment]
This feature pitch has been selected by the community as a bounty for **20$**

@eps0003 has a pull request ready for this: #384. If you'd like to contribute, you could review his code or think of ways to improve the feature.
