### ISSUE TITLE
[Feature Pitch] Spawn choice gets saved (properly)

### ISSUE THREAD

**Issue by ParaLogia** [transhumandesign/kag-base#175]
If a player has multiple spawn options, and specifically chooses one of them while waiting for respawn, that should be the default pick for subsequent respawns. 

It would appear that this is the intended behavior--but it fails very often for some reason. Too many times, the game insists that I spawn at a ballista in the middle of nowhere, and I have to re-pick the tent every single time. If I forget to do it once, I have to walk all the way across the map to get to the action.

**Comment by ParaLogia** [comment]
After an hour of testing, I have been unable to reproduce the bug in either the Solo CTF Tutorial or on a 2-player CTF server. But I am certain that I've had the issue occur as recently as yesterday, in a CTF server. It was a modded server (Leo's), but I don't think it would've affected this.

**Comment by ParaLogia** [comment]
The issue did appear several times while I was playing on a semi-full TTH server just now, so it definitely exists. But the spawning in TTH is especially buggy, which is another matter(?)

**Comment by 1bardesign** [comment]
I think the issue is with the way that your pick is currently stored. I'm not super certain of this because that is some very old code.

I think it's an offset into the list of spawns, but that can change when a spawn is created or destroyed. Might be what's causing the confusion?

TTH spawns are treated quite differently I think, but again, I haven't looked at that code in a while.

**Comment by Blubahub** [comment]
This will also be very useful when sv_test is on and you switch teams with the intent of being on that team permantly, only to find out you have to type "!team 4" every time you spawn... 😕

**Comment by ParaLogia** [comment]
Video evidence of the bug: https://youtu.be/hXLt3_gNqtI

Notice in the first few frames that I selected the ballista as my spawn point. On my next death, the selection was not saved.
