### ISSUE TITLE
Votekicks display wrong username info in chat

### ISSUE THREAD

**Issue by FuzzCat927** [transhumandesign/kag-base#180]
Votekicks display the username of the person who started the kick, rather than the one who the vote is on.
The information about who started the vote is correct.

![Image 1](https://steamuserimages-a.akamaihd.net/ugc/946203282875579581/764E332973EAB0519B9886E3D5BBBDDB5DC8AFC8/)
![Image 2](https://steamuserimages-a.akamaihd.net/ugc/946203282875579433/9248073C10D49F43B124C350185635EFA3CE132C/)

**Comment by ParaLogia** [comment]
Does it show the wrong name in the voting box too, or is just in chat?

**Comment by 1bardesign** [comment]
This should be fixed by #181 and the resulting changes afterwards; will push them to github soon but they are merged with a few more sensitive changes currently.
