### ISSUE TITLE
[Feature Pitch] Overhaul Challenges Game Mode

### ISSUE THREAD

**Issue by Olimarrex** [transhumandesign/kag-base#182]
**Overhaul Challenges Game Mode**

The Challenges Game Mode is currently terrible, buggy, and dull.

### Here are the main Issues that I can think of:

**Parkour 06 (Find the longboat!) challenges map** - Bad Deltas kicks everyone off the server whenever that map starts. Map itself misses an opportunity to be some kind of maze,  rather than just another parkour map.

**Class choosing** - Classes are randomly chosen at start of map. Some have only one option. Archer is best for most parkour maps, because he’s fastest.
3 options I can think of: Players can choose one of 3 classes on map start, but some classes are disabled on some maps OR Records are kept per-class per-map (Still ought to be able to choose which class in that case) OR only one class per map.

**Knight AI** - weak and cheesable, it shields when you left-click, so just hold it down and double slash him to death. Leads to dull gameplay.

**KillEmAll GameMode in general** - Impossible to beat a highscore, because there’s no way of killing more than the number of knights currently in there. It’s easier to do well if you’re playing on your own. Just generally not very fun.

**Map names** - since map names are now displayed, “Parkour 01 - 07” should be changed to something memorable

**Nextmapping system is confusing** - Game nextmaps when everyone’s dead, but only if nobody died to the void. Game nextmaps if time is up. Game nextmaps if everyone got to checkpoint. Game not nextmap based of death at all. Game should probably nextmap if portion of players get to the checkpoint.

**Maps In General** - The maps themselves are not challenging for skilled players. Ideally, each map would have multiple routes. One route might be more difficult to get through, but it would also be easier to speed through. Another possibility is to add extra parts to the map that go on past the checkpoint.

### Suggestions:

**Global records** - All Official CTF challenges records should be shared. Local records should still be available for other non-official / modded servers, to prevent hacking etc.

**Spinning platforms** - I have already made a prototype of these, the platforms spin 180 degrees before stopping for a few moments. There are a couple of small issues though, as the platform is unable to collide with blobs that are standing still. Through colours the platform could be horizontal and vertical, and it could spin in either direction.

**Infinite dispensers** - A separate blob to normal dispensers, whenever a dropper or bolter shoots an item from this dispenser, it does not run out of items.

**More in-dispenser items** - Add more items to the list of things that can be put into the dispensers. This could be things such as orbs, bombers, bolters, or (somehow) live bombs.

**“Immortal mode”** - This would be a boolean in the map cfg file, if true, items such as platforms, wires, doors, bisons, and sharks would have infinite life / not take any damage. All of the before mentioned things (except animals) would also not fall down or be destroyed when they lose support.

**Undying Mines** - Floating mines that do not destroy themselves when they explode. These mines might also be shieldable.

**Fans** - Blows players in a certain area away from them. The closer they are to the fan the stronger the wind.

**Checkpoints** - When player touches them his spawn point is now the checkpoint.

I know that some of these ideas are probably controversial, but they are all just suggestions to be discussed.

**Comment by Olimarrex** [comment]
**Overhaul Challenges Game Mode**

The Challenges Game Mode is currently terrible, buggy, and dull.


### Here are the main Issues that I can think of:

**Parkour 06 (Find the longboat!) challenges map** - Bad Deltas kicks everyone off the server whenever that map starts. Map itself misses an opportunity to be some kind of maze,  rather than just another parkour map.

**Class choosing** - Classes are randomly chosen at start of map. Some have only one option. Archer is best for most parkour maps, because he’s fastest.
3 options I can think of: Players can choose one of 3 classes on map start, but some classes are disabled on some maps OR Records are kept per-class per-map (Still ought to be able to choose which class in that case) OR only one class per map.

**No Global records** - All Official CTF challenges records should be shared. Local records should still be available for other non-official / modded servers, to prevent hacking etc.

**Knight AI** - weak and cheesable, it shields when you left-click, so just hold it down and double slash him to death. Leads to dull gameplay.

**KillEmAll GameMode in general** - Impossible to beat a highscore, because there’s no way of killing more than the number of knights currently in there. It’s easier to do well if you’re playing on your own. Just generally not very fun.

**Map names** - since map names are now displayed, “Parkour 01 - 07” should be changed to something memorable

**Nextmapping system is confusing** - Game nextmaps when everyone’s dead, but only if nobody died to the void. Game nextmaps if time is up. Game nextmaps if everyone got to checkpoint. Game not nextmap based of death at all. Game should probably nextmap if portion of players get to the checkpoint.

**Maps In General** - The maps themselves are not challenging for skilled players. Ideally, each map would have multiple routes. One route might be more difficult to get through, but it would also be easier to speed through. Another possibility is to add extra parts to the map that go on past the checkpoint.

### Suggestions:

**Spinning platforms** - I have already made a prototype of these, the platforms spin 180 degrees before stopping for a few moments. There are a couple of small issues though, as the platform is unable to collide with blobs that are standing still. Through colours the platform could be horizontal and vertical, and it could spin in either direction.

**Infinite dispensers** - A separate blob to normal dispensers, whenever a dropper or bolter shoots an item from this dispenser, it does not run out of items.

**More in-dispenser items** - Add more items to the list of things that can be put into the dispensers. This could be things such as orbs, bombers, bolters, or (somehow) live bombs.

**“Immortal mode”** - This would be a boolean in the map cfg file, if true, items such as platforms, wires, doors, bisons, and sharks would have infinite life / not take any damage. All of the before mentioned things (except animals) would also not fall down or be destroyed when they lose support.

**Undying Mines** - Floating mines that do not destroy themselves when they explode. These mines might also be shieldable.

**Fans** - Blows players in a certain area away from them. The closer they are to the fan the stronger the wind.

**Checkpoints** - When player touches them his spawn point is now the checkpoint.

I know that some of these ideas are probably controversial, but they are all just suggestions to be discussed.

**Comment by Blubahub** [comment]
For the classes, I agree that players can pick a class (if they can access the spawn), but the map.cfg should decide WHICH classes are playable. 

I agree with everything else though (albeit I never had that problem being kicked off that map), while I do want to note that for any new maps made checkpoints shouldn't be used a ton.

**Comment by Olimarrex** [comment]
[Challenges.zip](https://github.com/transhumandesign/kag-base/files/2209568/Challenges.zip)
Here is the mod file for a potential game mode, it's got a bunch of maps from mod-made servers, and a couple to showcase what you might be able to do

**Comment by makmoud98** [comment]
I think the challenges gamemode needs to be set aside for now. Although it is nice to have all of the issues written in one place, this feature pitch has waaay too many suggestions in it. I suggest you edit your post and just include the most important issues. As a side note, I think challenges can be a lot more fun if there was some better more creative (and challenging) maps. Maybe that will increase the number of people willing to play it.

**Comment by Olimarrex** [comment]
I think some of the other challenge modes could be made enjoyable, but the way it counts highscores needs to be changed.
