### ISSUE TITLE
[Feature Pitch] Come back to classic Kag trapblock

### ISSUE THREAD

**Issue by Orsovi** [transhumandesign/kag-base#184]
Currently, the trapblocks aren't really usefull, often misunderstood by beginner and well used in very few case. I miss the old trap plateform of the old classic version

![Blue on plateform](https://i.gyazo.com/0e673eb32a628f1b6a1599a3847c4e71.gif)
![Red on plateform](https://i.gyazo.com/3df5de36f4493b4c310fef59f8d7a7dc.gif)

However, this plateform had some inconvenients.

- All the bridge of trap-plateform go down in once
- You can go the both way on your own plateform (it's incoherent with the standard-realeased-platform).

So I propose you to add a new block in KAG or to replace the current one by a trap-plateform with the following caracteristics : 

- Let go the enemies (that's the goal ^^) both way
- Allow your team to go only one way
- Open one block by one block

**Comment by Blubahub** [comment]
I'd say to add a new block - the Classic and current trap block both have their own uses. Also, this has already been modded, so it isn't like there's no code for it!
