### ISSUE TITLE
[Feature Pitch] Spectator AFK kick timer

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#189]
People in spectator should have the same AFK timer as when being AFK while on a team.
The game should check for camera movement, mouse movement and chat interaction to see if someone isn't AFK.
Admins should be immune to this.

Pros:
- Prevents AFK people from taking up slots

Cons:
- Time-lapse recordings are slightly more difficult to do

**Comment by AsuMagic** [comment]
If spectators using slots is a problem then the proper solution would be to add dedicated spectator slots (which needs in-engine changes however).

**Comment by Shylie** [comment]
at some point (not sure when) an option to vote-kick spectators was added.
