### ISSUE TITLE
[Feature Pitch] Fix holiday scripts

### ISSUE THREAD

**Issue by Mazey** [transhumandesign/kag-base#191]
Holidays were a very fun addition to KAG, fixing the currently disabled holiday script would allow for the old holidays (like halloween with the gregs) to be revived and new holidays to be added, which would add some diversity to the game and allow for fun stuff that normally wouldn’t fit KAG.

This feature pitch requires extensive testing of Holiday.as (mainly when a holiday is over), I believe more information is in that scripts.

**Comment by bunniewormy** [comment]
Another fun thing [kinda related] would be having random events on servers, that could occur for, lets say, 1 in 30-40 games. It could sometimes spice the game up; for example, you could make kegs 2x cheaper for one game, or have double coin gain, and so on. Of course, you'd need to also add a notification that an event is happening somewhere, so everyone knows about it.

It could of course be a server-side variable [so you can disable it for your own server]

**Comment by 1bardesign** [comment]
This pitch has a bounty posted for $30! Please signal your interest here if you are interested in contributing.

**Comment by makmoud98** [comment]
working on it

**Comment by Blubahub** [comment]
I'd think if you are gonna do what bunnie says, @makmoud98 , then you would probably want to both print it to the chat, and have yellow text pop up on screen (same as the "Spawning in ..." text) - well, that's my opinion..!

**Comment by Mazey** [comment]
Bunnie's idea is not possible with holidays (and would be best done by making a separate system). The pitch is just for fixing the existing holidays system.

**Comment by 1bardesign** [comment]
Fixed by #219 - we'll pay out once it's passed testing but I'll close this to avoid anyone else starting on it.

Further "event" system implementation should indeed be done separately, but does sound fun 👍
