### ISSUE TITLE
Add interpolated mouse pos

### ISSUE THREAD

**Issue by Shylie** [transhumandesign/kag-base#192]
Currently there is no such thing as interpolated mouse pos for 60 fps stuff. It would be really nice to have this.

**Comment by Blubahub** [comment]
True, but make it optional.

**Comment by eps0003** [comment]
I'm only just realising how useful this would be, especially for my 3D stuff

**Comment by Vam-Jam** [comment]
Added for the next kag build (+ other features for 3D mods)
