### ISSUE TITLE
Extreme fps drop every time map changes - build 2567

### ISSUE THREAD

**Issue by benjamingorman** [transhumandesign/kag-base#194]
Every time there's a new map fps drops significantly for around 5 seconds. This is possibly caused by the new rendering code.

I don't think it's specific to my hardware since everyone in TDM was reporting the same issue.

Incase it helps though:
CPU: Intel i7-4710MQ
GPU: Nvidia GeForce GTX 850M
Windows 10

**Comment by 1bardesign** [comment]
Fixed in 2661 👍 Sorry for the slow followup
