### ISSUE TITLE
Keg bad code

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1990]
## Description
`Keg.as` at line 21 
```
	CSprite@ sprite = this.getSprite();

	CSpriteLayer@ fuse = this.getSprite().addSpriteLayer("fuse", "Keg.png" , 16, 16, 0, 0);
```
should be
```
	CSprite@ sprite = this.getSprite();

	CSpriteLayer@ fuse = sprite.addSpriteLayer("fuse", "Keg.png" , 16, 16, 0, 0);
```

Who knows, maybe that's the cause of https://github.com/transhumandesign/kag-base/issues/1266 ? Although I haven't been able to reproduce it lately.

**Comment by asumagic** [comment]
That's functionally equivalent: `getSprite()` returns the same handle to the sprite component of the blob.

**Comment by mugg91** [comment]
I thought instances like that should be reduced to a minimum.
The `sprite` variable is unused, wasted memory space.

**Comment by asumagic** [comment]
It's better to reuse the local variable when you have one, but that's kind of more for code quality reasons. Realistically, for a handle to an engine type, the memory consideration is non-existent as it is effectively a mere pointer, and the performance considerations are not significant especially for `onInit`.

(To be fair, truly understanding what is the performance impact of different things needs some understanding of the AS VM and that is not something very approachable without prior knowledge on language design and scripting language VMs.)

Hot loops or computationally demanding tasks are usually more of a concern, e.g. throwing several raycasts and iterating over the results, or iterating over a lot of blobs or tiles, etc., and using the staging profiler is then helpful to identify whether the performance is even concerning.

**Comment by mugg91** [comment]
I still think we shouldn't place variables that aren't going to be used.

`Obstructor.as` contains unnecessary `#include "Hitters.as";`.

**Comment by asumagic** [comment]
> Obstructor.as contains unnecessary #include "Hitters.as";.

Includes add to compile time so that's another reason to cut down on them.

**Comment by mugg91** [comment]
`WoodenPlatform.as` has
```
	this.getShape().getConsts().waterPasses = true;

	CShape@ shape = this.getShape();
	shape.AddPlatformDirection(Vec2f(0, -1), 89, false);
	shape.SetRotationsAllowed(false);
```
The first line could be placed further down, with `shape` being used instead of `this.getShape()`.

**Comment by mugg91** [comment]
`Sponge.as` has unused `#include "SplashWater.as";`

**Comment by mugg91** [comment]
The tag `"invincibility done` in `UnSpawnImmunity.as` doesn't seem to fulfill any purpose. Described in this old PR https://github.com/transhumandesign/kag-base/pull/1349
May need a closer look.

**Comment by mugg91** [comment]
Crate.as 
```
	(...)

	const bool putting = carried !is null && carried !is this;
	const bool canput = putting && this.getInventory().canPutItem(carried);
	CBlob@ sneaky_player = getPlayerInside(this);
	// If there's a player inside and we aren't just dropping in an item
	if (sneaky_player !is null && !(putting && canput))
	{

	(...)
```

Since `putting` is already checked in `canput`, it can be removed in the `if` code.
