### ISSUE TITLE
[Feature Pitch] Gamemode: War [Massive]

### ISSUE THREAD

**Issue by Radinyn** [transhumandesign/kag-base#204]
**New gamemode: War**
**Description:** Maps are really big, each team starts in an war base (!war_base command). On the map you can find empty halls, houses (trader shops) and tents. The goal is to destroy (not capture, that would be too easy) enemy team's war base.

**Halls** - in this gamemode both normal workshop and factory workshop are allowed, basically you can you factory workshops only near halls, out there you can produce items the same way as in TTH. You can buy more workers with gold.

**NPCs and houses** - when you find a house you can take ownership of it for your team, houses basically increase the population, and they can be upgraded with gold to the certain lvl to give more (not to much, we don't want servers to blow). When you have enough population you can buy NPCs in your war base. Of course there are 2 types of them - knights and archers - both to protect your land from those scums in other team. You can move them where you want to make the protection as good as you can. If you lose houses NPCs may turn rebelious and join team -1.
*Edit: NPCs respawn over time, unless they would be worthless with their potato ai.

**Tents** - tents are locations on the map filled with bandits (knights and archers) from team -1, they do not respawn. Under their base you can find chests (from tdm) with coins, bombs and arrows and of course - gold for your upgrades.

This gamemode is probably really hard to be made, however if it will become a thing one day it will most likely be a lot of fun and should gather quite a few players. Maps aren't too much of a problem I can make some with help from my friends, however if someone would be brave enough to take the task of coding it, I would be really grateful. Cheers! :)

Special thanks to Homek for helping me to design this gamemode.

**Comment by Mazey** [comment]
I have work done on a "fixed" war base, could probably use that.

**Comment by Radinyn** [comment]
Yeah that would be nice

**Comment by Uristthedorf** [comment]
Is the kag user base big enough for this?

**Comment by Enderzilla747** [comment]
Maybe if it goes F2P lol

**Comment by Radinyn** [comment]
For playing it? Definitely that's why there are bots! That's literally the whole point.

For creating it? Maybe.

**Comment by 1bardesign** [comment]
Sorry, we reviewed this and it's just too big for a realistic feature pitch at this point. You may be able to talk with modders and work out a "non-official" way to get it developed, but I'm closing this out of the feature pitch system. Thanks for your time! 👍
