### ISSUE TITLE
Arrows are harvested in mid air when shooting while hanging

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#2074]
## Description

https://github.com/transhumandesign/kag-base/assets/14877281/4ba465e3-5cd3-4f76-951a-b20249e35dc0

Played in online Sandbox

**Comment by asumagic** [comment]
They don't actually collide with nothing, it's because of the arrow harvesting mechanism (from holding RMB) which doesn't actually check if the arrow is stuck on a tile or not.

**Comment by mugg91** [comment]
Ok, I will rename the issue. I hope we can agree that harvesting should happen only when the arrow is stuck.

**Comment by mugg91** [comment]
If you hang and shoot fire arrow, you will set yourself on fire.
