### ISSUE TITLE
[Bug] Dead body in inventory 'eats' items

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#209]
If you have a dead body in your inventory and try to replace it with another item, the item disappears. Lit bombs act like they aren't in your inventory and deal 1.5 hearts. Water bombs are the same but stun instead. Both should instantly kill you when they are inside your inventory when they explode and the item should replace the dead body.

Steps to reproduce:
1. Put a dead body in your inventory
2. Grab another item
3. Click to replace the dead body with the held item. The item should disappear

**Comment by eps0003** [comment]
The items are going into the dead body btw
Managed to make a Russian doll with 5 bodies xD
Mines put in the enemy bodies turn into enemy mines

**Comment by terracraft321** [comment]
This is something i've noticed aswell with other blobs, perhaps Migrants.
 But ouch.

**Comment by Uristthedorf** [comment]
I think this is a relic of when dead bodies had inventories (i liked that feature)

**Comment by rayneomancer** [comment]
Actually dead bodies still have an inventory, it's just inaccessible. Since the dead body is just a regular player blob with  <0 health, I'm pretty sure the only way to fix this would be to have an entirely new blob for dead bodies that doesn't have an inventory at all.

**Comment by 1bardesign** [comment]
This likely needs some handling in the inventory code for "blocking" putting stuff into containers. Dead bodies are treated as containers in this context as they're an item with an inventory.

**Comment by bsjohnson20** [comment]
What actually happens is ya put it in the inventory, drop the body press e and 4 space inventory for 3...
Done it in tdm first, unusual but has its logic... Bodies have inventories!

**Comment by FuzzCat927** [comment]
can we not "fix" this, or add a way to toggle it, rather than removing it? I've been finding it very useful for the mod I'm currently making.

**Comment by Harrison-Miller** [comment]
Is this still issue, I don't think you can put corpses in your inventory anymore?
