### ISSUE TITLE
Sometimes can't collide blobs built before joining

### ISSUE THREAD

**Issue by longwoodbow** [transhumandesign/kag-base#2103]
**Description**

For example, sometimes I can through enemy doors, can't climb ladder or team bridge.

**Reproduction**

1. Join online server
2. Touch blobs built before joining
3. Check blobs working

**Your Setup:**

(only relevant for graphical/timing/crash related or OS-specific issues, use your best judgement)

- OS: Windows 11
- Build Number: current, it is happen from older version
- CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
- Graphics Hardware: Intel(R) Iris(R) Xe Graphics
- RAM: 8GB

**Comment by Vam-Jam** [comment]
Closing duplicate issue
