### ISSUE TITLE
[Feature Pitch] Add Tickets to ctf

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#214]
Tickets were a system in previous versions of KAG a few years ago. Basically, in CTF each team had a set amount of lives. Every time you died and respawned, one ticket was taken from your team's ticket amount. When it reached 0, your teammates would stop respawning. At that point, the enemy team could either win by 2 ways:

- Capture enemy flag
- Kill all remaining enemies

Now, before saying how this could be implemented into modern KAG, let's talk about why would it be nice or why would it be bad:

Pro-Tickets

- Eliminates stalemates [quite successfully]. With a set amount of tickets, games would almost never last over, let's say 40 minutes. If the game wouldn't be able to be finished with a flag cap, it would be able to be finished with tickets.
- Makes killing enemies more awarding. Sometimes knights and archers may complain about having no power, or sometimes games are just won by ratting builders that eventually capture the flag, or some stupid stuff like that; it's not a satisfying win for the winning team, and a very frustrating loss for the losing team. It's just how CTF works, games are usually won by builders. Tickets would make knights and archers feel more important; now both builders will be able to win games [if they are fast enough], and also combat classes will feel useful. 
- "last stands". I don't know about others, but I love being on the team that reaches 0 tickets first. There's just something thrilling about it; you start making plans on how you could kill enemies 40 times without dying, you start defending, while your teammates are dying and you start being more and more outnumbered; you become desperate, and sometimes you even win like that; you win the entire game by yourself. It's a rare event, but very satisfying when it happens.

Anti-Tickets

- May result in camping. I believe this is only partially true. Keep in mind, it's pubs; not everyone is gonna tryhard that much and camp. This would be a much bigger problem in  competitive matches, but when you'd play with tickets on pubs, most people wouldn't even notice it and be like 'OH SHIT, TICKETS!' when it's too late.
- 0 tickets stalemate. If both teams would reach 0 tickets at a similar time, then the last few people of both teams are going to want to camp in their towers. Both teams would be afraid to make progress. There could be multiple ways on how you could solve it. For example, you could buff explosives when both teams reach 0 tickets; you could make them cheaper or make bigger damage to enemy structures, therefore eliminating the need to have a builder with you [which would be risky for the vulnerable builder]. You could also have a battle royale-style red zone that would close off from both sides of the map, causing the teams to move to mid for a final battle. You could also teleport the remaining players 
to a TDM-style arena for a knight&archers battle, deciding the entire match. I'm not sure which solution would be the best, or if a solution is even needed; I'm open to suggestion.
- People not being able to play if they die. It feels kinda obvious that you wouldn't be able to play, but people are still going to get bored and frustrated (at least a part of them; I know a part would watch the game and try to give advice to their still living teammates). The solution would probably be giving them something to occupy themselves; perhaps you could let them to optionally play in a tdm-styled arena in the same server while waiting for next match (or maybe even a free-for-all arena, just for fun). @EDIT: a simple betting system would also work i guess; you could bet on who dies next, who kills the most, who dies last, etc etc.

Implementing Tickets
Now, probably the most important part: how should they be implemented? I can think of 3 ways:

- Tickets existing since the start of the match; it's how it always was and probably seems the most intuitive.
- Tickets being activated after a certain time passes, for example 30 minutes. This would let tryhards focus on the flag only for the first 30 minutes, and only start worrying about tickets later. 
- Tickets being activated with a vote. Tickets would probably eliminate the need for a 'stalemate' next map vote, although I don't really like that idea. The voting system is kinda broken and would need to be fixed first most likely; people randomly click O and P, or sometimes they wont even notice the vote.

**I strongly suggest that if this pitch passes, the community should vote on Discord about which option is the best.**

Of course people would still be able to host servers without tickets on their own.

Also, the amount of tickets should probably be determined by the amount of people playing when the match starts; if it would be a full 20 player server, perhaps you would have 200 tickets, while you'd have only 100 with let's say 10 players.

@edit: for those who would still want a server without tickets, I thought that it could be good if for each region there was 1 ctf with tickets and 1 without

**Comment by Franrek** [comment]
It would only work with timer coz that's the only way people wouldn't camp from the start of the game.

**Comment by Coroz** [comment]
I would like to see reduced coin loss from death with tickets.. so you wont get double screwed when you die.

**Comment by MatheusGodoi** [comment]
Agreed with the ticket starting in a timer, as another huge problem tickets would have is when a team get full of good players the enemy would get stomped as loose all the tickets faster ( like homek vs all, 200 tickets vs 75, most the matches ends in 30 x 0 tickets ) and would be frustating / unfair; But starting the tickets in a timer would make one team have a longer lifespam or make the stronger team win before the tickets even starts and make it worse for everyone.

**Comment by Orsovi** [comment]
Im for only if they are declenched after a time (like 20 min) to let the game play fully before everyone camp.

**Comment by Blubahub** [comment]
Tickets being run with a vote sounds nice - better than doing stalemate or surrendering in most cases (albeit, it gets kinda boring just watching other people literally survive). I dunno, maybe have some lobby room [?], just something so players can at least do slightly more than watching others. 

Obviously, make a few autoconfig.cfg server stats: sv_tickets (how many tickets each team starts with), sv_uses_tickets (1 or 0 - deciding if players can do a vote to activate tickets), and possibly just make a separate cloned game mode of CTF, but with tickets constantly active? E.g. sv_gamemode = TCTF.

**Comment by Basea** [comment]
I like the style of the game when tickets end, it may be annoying for newbies, because they want to play instead of watching a camp-fest.
I suggest a counter for every player, so if you kill a player with a large count of points, your team gets additional tickets / enemy team losses more than 1 ticket.
Points may be increased by killing enemy players, so if you kill a good player, your team will get an advantage, which could balance the game.
There is still a camping problem, tho.

**Comment by bunniewormy** [comment]
i like the idea of some players being worth 'more' tickets - but i think it should be like max 4 players per game.

after some thought, i think the camping problem at 0 tickets is best solved with the idea i mentioned in the post: 'battle royale-style red zone that would close off slowly from both sides of the map, making the teams move to mid for a final battle.' - solves camping, and it also encourages more attempts to take mid when tickets is going down [if you have the mid while at 0 tickets, the red zone isn't going to hurt you that much - but the enemies are going to need to attack mid, or else they'll just die]

**Comment by dpants** [comment]
Tickets would be great. Wasn’t it mentioned somewhere that the old version tickets would have a person respawn after a few min when 0 tickets ?  I like that idea.

**Comment by AsuMagic** [comment]
@Blubahub this would be a `*_vars.cfg` variable rather than an autoconfig one, because this only applies to CTF.

I would be against activating it forcedly after N minutes, but through manual vote or through a vote started automatically at certain time points, it would be pretty nice. IMO it's interesting because it gives a "second breath" to otherwise plain stalemates.

The only issue there is to me is that players are forced out when there are 0 tickets left, so I strongly agree with the "battle royale-style red zone" idea.

During stalemates I often feel like one of the teams are actually at a noticeable disadvantage, which would be reflected by larger ticket loss _(in theory)_, in particular when one of the teams owns the middle of the map, because of the red zone idea (height advantage).

**Comment by bsjohnson20** [comment]
Hey, wouldn't it be great if there was a vote for random bombs to be dropped from the sky, a vote section where there are other stalemate options. For example bombs falli g from the sky, or boulders...
Voting for tickets would be good...   ...Seen a ctf match on the same map for 3 hours, now thats absurd!

**Comment by Shadowblitz16** [comment]
if tickets were implemented then i would like to see support for activation when the match starts.
this way players can choose if they want a vote based tickets system or just them on all the time.

**Comment by bunniewormy** [comment]
closing since it wasn't liked by the community and not upvoted enough on #democracy
