### ISSUE TITLE
Spiker sometimes deals 2 hearts damage

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#2152]
## Description

Spiker triggered by motion sensor will sometimes deal 2 hearts of damage instead of 1.

Tested and verified in online Sandbox.

This is of significance in TDM since same traps exist there and one Spiker should not deal more than 1 damage per hit.

**Comment by mugg91** [comment]
This issue also exists in offline, where you can even receive 3 hearts of damage at once which I have not seen in online.

Spiker should only deal 1 heart of damage per contact in offline and online.

**Comment by mugg91** [comment]
Just a heads up.
I'm in favor of Spiker not using a spritelayer which I implemented in some PRs, such as here https://github.com/transhumandesign/kag-base/pull/1854
If I get around to looking at the damage issue, I will probably revive that PR and add a fix to that instead of making a new PR.

**Comment by Gingerbeard5773** [comment]
this bug only happens on localhost, and its because command sanitation was not properly applied to mechanisms. All of the mechanism code is done twice because the synchronization command for client is not disabled on localhost.

**Comment by mugg91** [comment]
@Gingerbeard5773 
It happens in online and offline. In online, 1 or 2 hearts are depleted and in offline up to 3 hearts are depleted. 
This video shows the bug happening in online, Sandbox US server.

https://github.com/user-attachments/assets/a69c3dec-e0a0-48eb-b02f-3fe2eac968b2
