### ISSUE TITLE
Add rendering functions for GUI

### ISSUE THREAD

**Issue by GoldenGuy** [transhumandesign/kag-base#220]
The title says it. If i wanna use render to make a hud, or something, i need to precalculate position relative to screen every tick, wich is pretty bad on perfomance, however, if we would have GUI remdering, i could just make all vertexes on init and that would be it, no need for position transform.

**Comment by GoldenGuy** [comment]
Nop

**Comment by 1bardesign** [comment]
(tagged with engine changes - will require someone to sit down with the script rendering code at some point to add this)

**Comment by Vam-Jam** [comment]
Added ages ago + goldenguy requested it to be closed
