### ISSUE TITLE
Zombie mode should be one of official game modes

### ISSUE THREAD

**Issue by nauponap** [transhumandesign/kag-base#221]
Seriously I just need it...
Some of my best moments and majority of my playtime were spent in the zombie game modes.
Can't rely on community made mods for it, they can be up or down anytime and I haven't seen one up in a long time :(

**Comment by makmoud98** [comment]
bro if ur trying to pitch a zombie mode on the github, then its gonna be made by the community either way. instead of a half assed comment why dont you discuss 1. what is wrong with current zombies gamemode? 2. what you expect in an ideal zombies gamemode? 3. pitch your own idea

**Comment by naps123** [comment]
Oh sorry guys... I thought this is directly for game developers of kag to see.

>  1. what is wrong with current zombies gamemode? 2. what you expect in an ideal zombies gamemode? 3. pitch your own idea

Problem is I haven't seen any zombie server up in some time. Am I missing something? 
All I remember from years ago is the zombie server hosted by "Beo", it was called "Beo's zombie server" That version was pretty much ideal. I just wanted to have beside all "KAG Official CTF EU No. ..." to have a "KAG Official Zombies" or something, to be always up and running you know...

**Comment by makmoud98** [comment]
This isn't quite the place for these kinds of requests, but if you want to talk to some of the community members I believe Rayne is working on a revamped version by of zombies. As far as I know, there have been many iterations of the zombie game mode over the years. The one on Beo's server was pretty decent but I think if we want it in the official game, there needs to be some polishing done to it. If you want to discuss this kind of stuff the best place to do it is in the discord. The developer reads the discord all the time and you can talk to him directly. But you should know that he is trying to move development over to the community. So best way is to discuss it with the community on discord then just pitch an idea in a more proper and formal way.

**Comment by vicenteferrari** [comment]
I'm closing this issue as it didn't gain any traction in order to keep the repo more organized. If you still feel like this is a good idea please feel free to make a new issue. Thanks for your interest in KAG!
