### ISSUE TITLE
[Feature Pitch] Make trampolines support multiple objects bouncing at once

### ISSUE THREAD

**Issue by FuzzCat927** [transhumandesign/kag-base#222]
Trampolines behave very strangely since they have a cooldown for bouncing something. For example, if you and a teammate both attempt to bounce on a trampoline at the same time, only one person will bounce. This is very frustrating in TDM.

**Comment by 1bardesign** [comment]
**This pitch has received a bounty for $30** - As always, please signal interest here before starting work on this bounty.

**Comment by Seanharrs** [comment]
I'd be interested in taking this one on.

**Comment by 1bardesign** [comment]
@Seanharrs go for it; the interest here is a courtesy/collaboration thing, not asking for permission 👍

**Comment by 1bardesign** [comment]
This bounty was met by #257 - thanks @makmoud98 and thanks @Seanharrs for your separate implementations of this bounty! ✨
