### ISSUE TITLE
Allow change class chat command in official Sandbox servers

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#2264]
## Current in-game behaviour.

On the `KAG Official Sandbox AUS` and `KAG Official Sandbox US` servers you can't switch class via chat command.
You can only do it on `KAG Official Sandbox EU` server.

This is a problem because, assuming you build a knightshop and switch to Knight, you cannot switch back to builder anymore until you leave and rejoin the server.

Change class chat command should be allowed on the AUS and US servers.

**Comment by asumagic** [comment]
Seems like `sv_test` was set on EU but not on US/AUS. I've changed that, and it should be persistently fixed.
