### ISSUE TITLE
[Feature Pitch] add back charging cursor for Knight slashes

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#227]
Being able to do fast slashes is one of the most important, if not THE most, things in Knight Combat. If someone is able to do slashes faster than you, you will lose in most situations. Considering we're going to have F2P soon, I thought we should make Knight Combat a bit easier. Currently, you just need to either time slashes without any visual help, or look at your animation. It's not a very good way to learn fast slashes, so some people (some of the best knights I know) decide to use an edited sprite - with the frame where you're able to slash being coloured red. I won't discuss if it's ethical or not, but the thing is, why is something like this needed to be better? Even if you can learn fast slashes without the red frame, it's going to take more time.

My suggestion - to remove the need for custom workarounds and to make learning Knight (especially fast slashes) easier for new players - is to bring back charging cursor from Classic. Archers in Release KAG already have it, so why not knights as well? I don't even know why it got removed at all, but it should be brought back. Can you imagine shooting arrows without the charging cursor?

This may seem useless for good players, but it's going to help newer players a lot with learning.

**Comment by Metadorius** [comment]
Something as noticeable as a red frame would be great, that's for sure. I think it's the quality of life change and have to be added, though I'm unsure if the cursor would be as noticeable as a red frame texture.

**Comment by Blubahub** [comment]
I agree, but (of course) make this optional.

**Comment by 1bardesign** [comment]
**This pitch has received a bounty for $30** - As always, please signal interest here before starting work on this bounty.

**Comment by Andresian** [comment]
Im interested in working on this.

**Comment by 1bardesign** [comment]
Addressed by #256 , thanks @Andresian !
