### ISSUE TITLE
Add server queues

### ISSUE THREAD

**Issue by Metadorius** [transhumandesign/kag-base#228]
Basically waht the title says. It's really annoying to spam that "update" button to see if someone left the server when it's full (i.e. EU CTF every evening), and even more frustrating to see "Server is full" when you haven't joined fast enough and other player jumped in just before you

I suggest to implement a queue system: if the server is full, instead of join button there would be an "enqueue" button. After pressing the button one will be assigned a number in queue, and when there's no players left in front of the player and someone leaves, he automatically joins (and KAG beeps/flashes in the toolbar so one can know he's entered the game). Current queue size should also be displayed in server info.

**Comment by makmoud98** [comment]
the server browser is currently hard coded into the engine meaning the devs need to get involved for this change. great suggestion tho because that's something I know many people have wanted for a long time

**Comment by Metadorius** [comment]
> 
> 
> the server browser is currently hard coded into the engine meaning the devs need to get involved for this change. great suggestion tho because that's something I know many people have wanted for a long time

that's why I hasn't added [Feature Pitch] to the title.

**Comment by AsuMagic** [comment]
#1353 solved this by adding a queue for spectators in build 4137, as spectator slots are now functional for a while now.
