### ISSUE TITLE
[Issue] Camera scrolling no longer works when HUD is disabled with F6

### ISSUE THREAD

**Issue by cabodary** [transhumandesign/kag-base#235]
Can't move the camera around with mouse button or with WASD when the UI is toggled off by pressing F6. You used to be able to do this

**Comment by 1bardesign** [comment]
(this is indeed a bug)

**Comment by 1bardesign** [comment]
Engine change is _probably_ required or the camera logic needs to check for uncapped AND hud is hidden and continue to update in onTick (will degrade to 30fps camera when UI is off)

**Comment by eps0003** [comment]
Fixed in the engine-side pull request that goes with #566
