### ISSUE TITLE
CSprite EmitSound not playing for spectators

### ISSUE THREAD

**Issue by MonkeyFeats** [transhumandesign/kag-base#236]
Cannot hear sprite emit sounds when spectating.
Add this to a blob on tick, spawn it and swap between spectator and a team.
```cpp
this.getSprite().SetEmitSound("/Thunder1.ogg");
this.getSprite().SetEmitSoundPaused(false);
this.getSprite().SetEmitSoundVolume(1.0f);
```

**Comment by 1bardesign** [comment]
👍 thanks for the easy repro, will hopefully find time for it for next build

**Comment by MonkeyFeats** [comment]
While you're at it please add the engine function SetEmitSoundPitch( float ), thanks :^)

**Comment by 1bardesign** [comment]
Fixed next build (or test build if you have it), did not add the pitch for emitsound I'm afraid, but @AsuMagic or @Vikhenzo may be interested in helping you out! 😅 

Also needs to be tested that "infinite drill sound for spectators" bug has not reappeared as a result of this fix 👍
