### ISSUE TITLE
[Feature Pitch] If you're standing next a shop, number keys buy items instead of emoting

### ISSUE THREAD

**Issue by benjamingorman** [transhumandesign/kag-base#240]
This would make it easier to buy items quickly. Buying items at the minute is slightly awkward because you have to be quite precise with your clicks, and it's easy to buy the wrong item. This feature pitch would also help in situations where you need to buy something extremely quickly (e.g. you're about to die if you don't buy a burger).

I think it could be implemented by mapping every slot in the shop to one of the number keys. If there were more than 10 slots then shift+number, ctrl+number etc. could be used to handle a large number of items.

**Comment by eps0003** [comment]
This should only work once you've clicked e on the shop, otherwise it would lead to a lot of accidental purchases.

**Comment by bunniewormy** [comment]
i'd rather have it bound to ctrl+number key rather than number key alone. i imagine i'd actually buy lots of stuff by accident by emote spamming. good idea nonetheless

**Comment by Vikhenzo** [comment]
I agree this would be a good Quality of Life improvement. I also of course agree it shouldn't be straight up when you're standing next to a shop. Shift + number would be good enough, having it csgo-style where you can use the numbers while inside the menu would also work but I think modifier + number would be even better.

**Comment by benjamingorman** [comment]
It's hard to know that number keys alone would be intrusive without testing in game. It might actually be very comfortable. Initially people would be buying stuff accidentally but people might get used to it?

It should be pretty easy to test both number keys alone, and modifier + number keys. The implementation will be very similar. Number keys in menu is a little different.

**Comment by bunniewormy** [comment]
what if someone just prefers to use numbers for emotes instead for buying

**Comment by benjamingorman** [comment]
Well best of both worlds: have a settings option that enabled buying with plain number keys. Ctrl+number keys would work too regardless of the setting.

**Comment by eps0003** [comment]
I strongly disagree with using a modifier key because they aren't used anywhere else in the game and put your hand in a slightly uncomfortable position (especially if ctrl is used). I think this should just be an extension onto the current behaviour of shops by first clicking 'e'. Clicking 'e' before using number keys will give the user feedback on which shop they are using. Without having this feedback, it might be difficult to know when you are in range of the shop.

**Comment by Andresian** [comment]
I`m willing on making that feature if it gets accepted.

**Comment by 1bardesign** [comment]
This pitch has a **$30 bounty**! As always, please signal interest here before starting work on this bounty. 

As there has been some discussion around exactly how it should work (without obvious consensus afaict), asking more folks in `#development` and `#general` may be a good idea.
