### ISSUE TITLE
[Feature pitch] Water rework

### ISSUE THREAD

**Issue by benjamingorman** [transhumandesign/kag-base#241]
Water arrows and bombs are overpowered and should be reworked.

They can be frustrating to play against because the only counterplay is to buy a sponge. Buying a sponge kind of sucks though because it uses an inventory slot and most of the time if you buy one at base you won't end up using it.

However I still feel obligated to buy sponges all the time because it's the only way to have a chance against someone hitting you with water. If you don't have a sponge and an archer pulls out a water arrow on you it's just game over.

Some suggestions which might help the problem:

- Water could not stun but instead just provide a large knockback. This could still be used to disrupt the enemy team; knocking people off towers etc.
- Knights could have some way to block water arrows. Maybe shield could block them like all other arrows? Maybe they could be slashed out of the air in the same way that ballista bolts can?
- The stun effect could have diminishing returns so at least you can't be chain stunned for 10+ seconds.
- The water arrow could just be replaced with an entirely different kind of arrow.

I think that if there is a change here it's important that:
- It isn't too much of a nerf to archers.
- There's still a way to put out fires.

Simply increasing the cost of water arrows, or decreasing the amount that archers can hold would not really help the problem.

**Comment by ferrezinhre** [comment]
If I may propose a few solutions:

First: Simple one, decrease stun time from 45 to 30 or 25 (would say it will be playerbase choice), decrease area of "splash"(require "direct hit") and removing "stun trought walls" (personally  I would add small damage, just for fun)

Second: We just don't like stun, it's bad evil, and devilish invention (right, like you can't just evade water eh?). Let's then water arrows and bombs slow down players instead stunning them, possible but require new .as just for water slowdown (I think?)

Third: Just try evade water arrows and water bombs, it's possible (btw: stating that "they're not fun for anyone and can be very frustrating" is irrational not everyone have same view as you dear. ) anyway there are my solutions. ps: (what about endless shield stun loop? )

**Comment by benjamingorman** [comment]
Thanks for supporting the issue Ferrez.

First: All these things would definitely help. Although I think that just 'tweaking the numbers' masks the problem rather than fixes it, because the water stun mechanic itself is the underlying issue.

Second: Slowdown is a good idea yeah, this could definitely work.

Third: Sure sometimes you can evade water arrows and bombs by dodging. But there are many situations where it's impossible to do so. The arrow comes too quickly and your character moves too slowly. Or you could be in a narrow corridor, or on a flat plain. I know my comment was quite opinionated, butI think it's hard to make a strong case that water is a fun mechanic. From a game design perspective, fun mechanics are those that give the player (and the opposing player) a lot of options and possibilities for creativity. Water is a totally onesided mechanic because the opposing player has all options removed (they are stunned and helpless).

**Comment by vicenteferrari** [comment]
I think, in some aspects, you're trying to straight up make the game easier, this does not equal to a more enjoyable game in most cases. In general I personally don't have complaints with stun mechanics. Of course I don't think the KAG implementation is flawless. But it's not _bad_ either.    
    
    If you were to remove the stun mechanic you would only be making the game shallower, not more fun. In regards to the sponge, we would have to evaluate it more specifically, I suppose it could be improved, having options to counter mechanics does generally make it a better exprience. But it hardly warrants a 'water rework'.

**Comment by Vikhenzo** [comment]
I think, in some aspects, you're trying to straight up make the game easier, this does not equal to a more enjoyable game in most cases. In general I personally don't have complaints with stun mechanics. Of course I don't think the KAG implementation is flawless. But it's not _bad_ either.    
    
If you were to remove the stun mechanic you would only be making the game shallower, not more fun. In regards to the sponge, we would have to evaluate it more specifically, I suppose it could be improved, having options to counter mechanics does generally make it a better exprience. But it hardly warrants a 'water rework'.

**Comment by benjamingorman** [comment]
@Vikhenzo "If you were to remove the stun mechanic you would only be making the game shallower"

I'm advocating that the stun mechanic be replaced with something else, not flat out removed. The game shouldn't be any shallower.

"you're trying to straight up make the game easier"

No, I think players should just have more options to deal with the water mechanic. Because at the minute it's kind of an unbeatable boss. If you get hit with a water arrow - you're just dead. There is nothing you can do most of the time. To me, this is frustrating.

If you bought a sponge - you're lucky (but that's not possible on many TDM maps which have water spawns but no shops).

If the water arrow feature was added now, and had never been in the game, I imagine there would be backlash about it.
- The arrows are very cheap
- The stun can be chained for a long time with no diminishing returns
- The stun goes through walls
- It's an AoE stun that can hit many people at once
- It lasts a long time
- You're totally defenceless while stunned and can be dropped from 100% - 0 health

When you write it like this, it seems totally OP. I don't know of any other game which has a spammable AoE stun?

**Comment by benjamingorman** [comment]
I'm surprised that the feedback to this has been negative. People have been asking for a water rework for years. Would the people who voted down care to argue against what I said?

**Comment by ParaLogia** [comment]
I'd love the idea of diminishing returns on stun-time to be revisited.

To me, the only completely unfun part of water is when some enemy archer(s) saves up enough coins to completely stunlock you--and everyone near you--for 15 seconds at a time. It's just not a good experience.

If you keep the initial stun the same, you'll still be able to make great plays with well-timed water. You just won't be able to cover over poor timing with more water.

**Comment by Blubahub** [comment]
What @ParaLogia said is I [now] think is the best "fix." While not making Water Bombs/Arrows useless, it would not make it so spammy either.

**Comment by bunniewormy** [comment]
this should be closed now that you can actually shield water
