### ISSUE TITLE
Make crouch work only when the crouch sprite is visible.

### ISSUE THREAD

**Issue by Franrek** [transhumandesign/kag-base#249]
Right now crouch doesn't work whenever player is moving in any way and at any speed. I would like to change that and disable crouch when it's the player who is inputing movement on his character. That would mean you can crouch while you're slowly sliding down of an edge, which right now is really annoying and seems random since movement like that can be so slight its pretty much invisible. 
![ezgif com-crop 1](https://user-images.githubusercontent.com/39047604/47265662-63383600-d523-11e8-8756-3c9d15ef3019.gif) 
![ezgif com-resize 9](https://user-images.githubusercontent.com/39047604/47265729-50723100-d524-11e8-9db9-cb5d9acce682.gif)

Change like that would also mean you could do some cool stuff like gaining a lot of speed as archer and sliding through other players. However I would count grapple as a movement action that stops crouching (not sure bout that yet) to make it require more skill.
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/39047604/47265780-df7f4900-d524-11e8-960b-3391a34b02d8.gif)

Obviously I wouldn't want to allow crouching in midair. So there should be a requirement that character is in contact with the ground below him to crouch.

**Comment by Basea** [comment]
It's not such an important bug, but developers should start fixing at least with such problems to make KAG playable for newbies.

**Comment by benjamingorman** [comment]
Definitely support this.

**Comment by Basea** [comment]
> Something that should've been fixed for a long time already.
> 
> However i don't think i like the idea of archer getting yet another trick, with grapple + crouch. Big or not, It's still a buff and yet another way for archers to fool knights. Playing against good archers in TDM is pain already.

Actually, I think that most players think that archers aren't balanced well because of their opportunity to escape from the knight, since they have greater mobility than knights.
I think that it's not a problem, since they have no way to kill a careful knight.
"Archer problem" in kag is exaggerated, they are balanced well in my opinion.

**Comment by Franrek** [comment]
> Something that should've been fixed for a long time already.
> 
> However i don't think i like the idea of archer getting yet another trick, with grapple + crouch. Big or not, It's still a buff and yet another way for archers to fool knights. Playing against good archers in TDM is pain already.

It would still pretty hard to do coz it requires flat ground and not lifting off of it. It would be one of these things that happens rare but it's awesome when it does. Won't change much about how annoying the archer in tdm is imo. It's the way TDM rules are that makes archer vs knight combat annoying.

**Comment by 1bardesign** [comment]
This pitch has received a **$30 bounty** - there is already a PR waiting for it ( #273 ) so starting work before that has been reviewed is not recommended!

**Comment by 1bardesign** [comment]
Closed as a result of #273 - please do get in touch after testing if there are issues and we will work to resolve them 👍 @eps0003 please get in touch with payment details for the bounty
