### ISSUE TITLE
support for map wrap without massive slowdown

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#250]
can map wrapping be supported by the CMap?
it would be a feature that can be toggled on for vertical and horizontal, and would do the following

-disabled map bounds for blobs  on the enabled axis
-render wrap the edges of the map on the enabled axis
-collision wrap the edges of the map on the enabled axis
-position wrap the edges of the map on the enabled axis

it would be pretty easy to implement engine side in would just wrap, draw and do collisions on the blob on all 9 sections of the map..

-top
-topleft
-topright
-middle
-middleleft
-middleright
-bottom
-bottomleft
-bottomright

**Comment by 1bardesign** [comment]
Not going to happen officially I'm afraid; it's actually a large amount of work and not going to be used in vanilla.
