### ISSUE TITLE
[Feature Pitch] Add leaderboards for official servers with various statistics

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#251]
A pretty big feature pitch, but it would be nice if we could get it for f2p - I suggest adding leaderboards for official servers, and add a new button to the main menu - "Official Leaderboards". It would incentivise people to play more and it would be interesting to look at some statistics. Some servers in Classic had such leaderboards: 
![image](https://user-images.githubusercontent.com/39147836/47759362-8eebb680-dcaf-11e8-8b6a-e166e1819260.png)

**You could sort leaderboards by:**
- Global / Region (EU, US, AUS)
then
- All gamemodes / Specific Gamemode (TDM, CTF, TTH)
then
- All classes / Specific class (Archer, Builder, Knight)
then
- Global (some kind of points?) / Specific Statistics (Flag Captures, Kills, Kills by arrows, etc.)

Bad graph:

![image](https://user-images.githubusercontent.com/39147836/47757751-2e0cb000-dca8-11e8-997b-aa557f3d48e2.png)
For example, you could sort EU>TDM>Knight>Kills, or Global>CTF>Archer>Deaths by arrows, or EU>Global>All classes>KDR. Basically anything that anyone wants, sorry for bad explanation.

For 'truly global' sorting, you would probably need to bring back points (experience points?):
Default sorting probably should be Global>All gamemodes>All classes>Points

KAG Classic had points, I don't know the exact formula, but you could assign points to certain statistics, and then count them all or something like that (for example, flag cap 50 points, kill 2 points, double kill 8 points, spike kill 10 points, death -1 points - just examples)

**I would suggest tracking the following stuff (reminder that each of them could be sorted by class, so need to track the class as well).**
- Kills (including: kills by sword/pickaxe/arrow, stomp, bomb, mines, kegs, spikes, fire, boulders, drowning, fall damage, pushing to void, riding through someone with siege, ballista bolts and catapults stone, exclude teamkills)
- Deaths (including suicides and deaths by stuff mentioned in Kills, probably should exclude deaths in building time)
- KDR
- Flag Captures
- Wins (don't count if team was swapped 3minute before finished game)
- Losses
- Coins Gained (and then you could split way of gaining coins, combat/building etc)
- Mats Gained (by yourself - chopped logs, mined stone and gold)
- Mats Used
- Blocks Digged (split into dirt/stone/wood blocks/etc)
- Blocks Constructed (split again, stone/wood/ladders/etc)
- Damage (split same way u split kills)
- Heals (hearts)
- Blocks travelled (while inputting)
- Hours played (don't count spectator)

I also suggest adding a reward for the best Knight, Archer and Builder in each region - a special badge and perhaps even a coloured name? If the leaderboards are going to be for all offi servers, the best players deserve more recognition than just a badge

**Comment by 1bardesign** [comment]
This pitch has received a **$100 bounty** - but we'll need to discuss staging that into multiple actual _tasks_.

If anyone has a split they think would work, they're welcome to suggest it!
The one suggested on discord was:
- Add in-game per-server stat tracking (using config files most likely)
- Share leaderboard data between official servers (some kind of tcpr solution)
- Show official leaderboards externally (website aggregating the official server stats)

The specific stats to measure also needs to be agreed; the list above from bunnie is a sensible starting point.

**Comment by Vikhenzo** [comment]
per server config files? you would have to make new interafces to display the real time data seems out of scope. I think just make a centralized server with a simple api that aggregates and sorts all the incoming data from official servers and has a good frontend

**Comment by 1bardesign** [comment]
I figured splitting the concerns would be good, but if it was to be tackled as a single solution that'd be fine too. In that case, ideally it'd be open source and compatible with other hosts' servers as well, so they could run their own leaderboards.

**Comment by makmoud98** [comment]
working on this

**Comment by Harrison-Miller** [comment]
Work is almost done with the first draft
http://staging.kagstats.com/#/leaderboards
https://github.com/Harrison-Miller/kagstats

Hopefully releasable sometime in august.

**Comment by 1bardesign** [comment]
@Harrison-Miller has got http://kagstats.com/ hooked up to the official servers - going to close this now, verra get in touch please about the bounty 💖 

Please forward issues with kagstats to the [appropriate repo](https://github.com/Harrison-Miller/kagstats)!
