### ISSUE TITLE
Knight Cursor Change

### ISSUE THREAD

**Issue by Lava678** [transhumandesign/kag-base#258]
The cursor right now is too large and annoying to play with.

My cursor looks better and is the same size as the old one with the same functionality as the new one.

[here ](https://media.discordapp.net/attachments/337266863841214465/510549675758059521/KnightCursor.png?width=30&height=476)it is

by the way I have no clue as to how to use github :)

**Comment by 1bardesign** [comment]
You are free to use texture mods in your own game, but the existing cursor uses the same assets as the archer cursor. Adding inconsistency for the sake of a personal preference for a smaller cursor is probably not in the game's interests.

Thanks for your time though! You might consider submitting this as a texture pack resource [on the forums](https://forum.thd.vg/resources/categories/texture-packs.9/) and linking folks there.

For future reference, submitting file changes is best done through a [pull request](https://github.com/transhumandesign/kag-base/pulls), not an issue.
