### ISSUE TITLE
Random[] does not hold seed when used with property copy operator

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#261]
***Description**
Random array does not retain seed used with property or copy operator..

**How to Reproduce**
1. create a blob
2. use this as the blobs script https://pastebin.com/wZ4QtfPJ
3. run localhost and spawn it
4. see that the seeds when copied are now 0

**Expected Behavior**
the randoms in the random array should hold there state and seed

**Screenshots**
![image](https://user-images.githubusercontent.com/2453707/48319036-73d94a80-e5bd-11e8-910e-147f95d8db1e.png)

**Comment by 1bardesign** [comment]
Fixed next build, thanks for the report ✨
