### ISSUE TITLE
Make swapping team to spectator and exiting the game count as a death.

### ISSUE THREAD

**Issue by Franrek** [transhumandesign/kag-base#274]
It's a cheesy way to avoid dying and losing coins/kdr, which is just plain stupid and has no reason to exist.

Other way to make that "mechanic" not viable that I didn't consider before is adding a delay on team swap after joining spectator. 30 sec/1 min would be enough probably.

**Comment by Vikhenzo** [comment]
I think it's fine the way it is. I personally like hopping to spectator to wait out build phase. Besides, when admins go into moderation mode with !m it swaps them to spectator, not that it couldn't be circumvented but still.

**Comment by Harrison-Miller** [comment]
This is non-issue.
