### ISSUE TITLE
[Feature Pitch] Hp's Near cursor

### ISSUE THREAD

**Issue by Norwaivhi** [transhumandesign/kag-base#281]
Idea is to display Hp bar near cursor so it can be seen more easily.

It also will go nice with new Knight cursor where you can see hit charging process.This way new players(and maybe some more experienced ones) will have better control over the character as they will not only see charging process and also their hp's.

Here is my vision of how it might look:
![123](https://user-images.githubusercontent.com/45542273/49344205-3aa86d80-f685-11e8-96a3-509bb9f76121.png)

**Comment by terracraft321** [comment]
As long as it isn't intrusive to the gameplay

**Comment by Norwaivhi** [comment]
> As long as it isn't intrusive to the gameplay

Add it as the toggleable option/Make it a bit transparent(hearts)?

**Comment by Franrek** [comment]
I don't want more distracting stuff around my cursor. It's fine as it is. Big competitive games have hp displayed on the side/bottom of the screen and it works well.

**Comment by bunniewormy** [comment]
make it togglable [tbh in a perfect world the entire GUI would be customizable] and there is no problem

**Comment by terracraft321** [comment]
> > As long as it isn't intrusive to the gameplay
> 
> Add it as the toggleable option/Make it a bit transparent(hearts)?

As for the toggleable option, depends how it is handled.
 If it's accomplished by the in-game options, would need something changed in the hard-coded engine.
There isn't really anything much with opacity in the game I reckon. 
So either full hearts ( or maybe squares with nothing in the middle). So it's more likely to be just hearts.

> I don't want more distracting stuff around my cursor. It's fine as it is. Big competitive games have hp displayed on the side/bottom of the screen and it works well.

It's not always optimal to change one thing unless it can be future proofed.

> make it togglable [tbh in a perfect world the entire GUI would be customizable] and there is no problem

Yeah if we make the GUI modular, or atleast semi-modular.

**Comment by eps0003** [comment]
This really doesn't need to be on the cursor. Health is clearly visible at the bottom of the screen.
