### ISSUE TITLE
Make player mouse-over hp bar script-side

### ISSUE THREAD

**Issue by Shylie** [transhumandesign/kag-base#282]
Currently the feature where you can mouse over a player to see how many hearts they have is engine-side. Can we get this moved to script-side please?

**Comment by terracraft321** [comment]
@AsuMagic 

Don't we need the i/o packets, somehow that everybody has the same information?

**Comment by AsuMagic** [comment]
What do you mean about "needing the i/o packets"? All the information needed is already known by the client: Clantag, character name (i.e. visible name), health and max blob health.

Indeed though, this requires engine changes to remove the then old code that handles this.

**Comment by AsuMagic** [comment]
Additional note from #976 that should be a good idea:

> Also let everyone see enemy health from any distance, currently this gameplay advantage is given only to admins for some reason.
