### ISSUE TITLE
Assist system

### ISSUE THREAD

**Issue by Suprejso** [transhumandesign/kag-base#290]
I think we all get mad sometimes when someone steals our kill, which we don't even get rewarded for. 
Well, I thought of an assist system. I don't think there's much to explain, I'll just leave you with one example;
Player X hits player Z for 3hp which leaves him with 1
However Player Y came out of nowhere and kills Player Z getting better KDR and more coins
Player X is now frustrated as he didn't get nothing for taking most of Player Z's health.
What would reward him the effort? Of course an assist (counts as 0.5 kill added to KDR) and half of the coins Player Y's got for the kill.

I think that's all you should know, in case anything is hard to understand just let me know.
kthxbye, V

**Comment by Franrek** [comment]
You already get coins for dealing damage. Increasing kdr for dealign damage is stupid imo. It's called kill death ratio for a reason. I guess "damage dealt" in scoreboard would make sense but I don't think its much needed anyway.

**Comment by Turtlebutt** [comment]
Take into account kegs, bombs and other damage dealing entities. (Only by teammates though.)

**Comment by Blubahub** [comment]
I think player Y should get 25 percent, and player X should get 75. Of course, this wouldn't work in cases where there are 2 assisting players (for example). So, you'd have to make a system where it checks how much damage dealt to the player and give more to the player that dealt more damage, and so forth.

Possibly have boost for the finishing blow. You'd also have to factor in environmental attacks (which in the code would basically be where the net loss goes, so i.e. Z player doesn't get a lot of money for barely attacking C player.

But those are my two cents - overall, I like the idea of a support system.

**Comment by Turtlebutt** [comment]
> I think player Y should get 25 percent, and player X should get 75. Of course, this wouldn't work in cases where there are 2 assisting players (for example). So, you'd have to make a system where it checks how much damage dealt to the player and give more to the player that dealt more damage, and so forth.
> 
> Possibly have boost for the finishing blow. You'd also have to factor in environmental attacks (which in the code would basically be where the net loss goes, so i.e. Z player doesn't get a lot of money for barely attacking C player.
> 
> But those are my two cents - overall, I like the idea of a support system.

It's about kill credit on scoreboard, you already get money for damaging the enemy.

**Comment by Suprejso** [comment]
> You already get coins for dealing damage. Increasing kdr for dealign damage is stupid imo. It's called kill death ratio for a reason. I guess "damage dealt" in scoreboard would make sense but I don't think its much needed anyway.

You don't get increased KDR just for damaging a player, you have to be get an assist, and I have to say that you are right, Franek, maybe increasing KDR isn't the best idea and another table on leaderboards would be fine too, I can't tell.


> I think player Y should get 25 percent, and player X should get 75. Of course, this wouldn't work in cases where there are 2 assisting players (for example). So, you'd have to make a system where it checks how much damage dealt to the player and give more to the player that dealt more damage, and so forth.
> 
> Possibly have boost for the finishing blow. You'd also have to factor in environmental attacks (which in the code would basically be where the net loss goes, so i.e. Z player doesn't get a lot of money for barely attacking C player.
> 
> But those are my two cents - overall, I like the idea of a support system.

You misunderstood me here; Player X would get 100% of the kill, and Player Y would get additional %'s, either 25% or 50%, not sure which option would work out better. 
There is always 1 assisting player, the one who dealt damage to Player Z as the last player before he gets killed by Player X (talking about the example situation in first post)


There might be some stuff to change, I just came out with the idea and example situation so that you guys can think of it and see which option works out the best.

**Comment by Suprejso** [comment]
Also about the coins for dealing damage - if the assist system would be added, the additional coins should be either decreased or removed.

**Comment by Suprejso** [comment]
I honestly think that adding "assists" counter on the scoreboard is a better way than getting +0,5 kill for each assist

**Comment by 1bardesign** [comment]
I think there'd be value in assists, honestly. Particularly in CTF as an archer or builder you can be assisting in combat on the frontlines very effectively while not getting kills, and having a stat that reflects that would be nice.

It'd be best done engine-side to extend the current single "last hit by" functions to get a list of all recent attackers + maybe how long ago they attacked as well.

I don't think the coin rewards should be changed at the same time, that'd seriously affect game balance for what is essentially just a stats number on the scoreboard. Potentially reducing coins per damage and adding coins for a successful assist would be worth doing once this was implemented though.

**Comment by eps0003** [comment]
I'm working on this

**Comment by Mazey** [comment]
This feature pitch has been selected by the community as a bounty for **75$**

@eps0003 has started working on this. Working on this without approaching him is ill-advised.
