### ISSUE TITLE
[Feature Pitch] make changing class at enemy ballista possible

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#292]
just a little suggestion. i think siege is a bit OP sometimes; the only actually good counter against it is bomb arrows. capturing a ballista is also super hard if it's on enemy territory - even if you do it, it will be taken back like right after. i think siege should be easier to capture. with this idea, you could change from knight to builder after killing enemies and block the enemies from coming. it will also make people protect their team's ballista more, and putting a ballista in a spot that isn't so safe will actually have some consequences if a skilled player gets near it

oh also, this is supposed to go together with https://github.com/transhumandesign/kag-base/issues/293

**Comment by Blubahub** [comment]
Yes. This only makes sense, since we can already turn classes at i.e. enemy shops.
