### ISSUE TITLE
[Feature Pitch] Make ballista bolts and catapult shots go through platforms

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#293]
As things are now, ballista bolts and rocks that catapults launch cant go through platforms no matter what way they are facing. Siege will always damage or completely destroy them as shown here:
https://gfycat.com/CautiousPleasedLeveret
This should be reworked so you could shoot through platforms safely if they are faced the right way.

**Comment by 1bardesign** [comment]
This pitch has a **$50 bounty**! As always, please signal interest here before starting work on this bounty.

**Comment by 1bardesign** [comment]
Addressed by by #352 - thanks @MonkeyFeats !
