### ISSUE TITLE
[Feature Request] Ability to replace damaged wood blocks with stone

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#295]
This will make it easier to repair and upgrade wood blocks.

I'll be willing to implement this myself but I want community feedback first.

**Comment by Blubahub** [comment]
Best, and it only makes sense logically (well, I guess magically making wood become stone is a stretch, but hey, this suggestion isn't stretching the big rubber band of KAG Logic that much more then it already is).

**Comment by benjamingorman** [comment]
One thing about this change is that it would nerf fire arrows, because it would be a lot easier to quickly cover burning wood with stone blocks.

**Comment by HappySheepo** [comment]
In my opinion that would make stone bricks so op. And with the factory shop, you just spam stone bricks everywhere and it's undestroyable.

Don't get me wrong, it's a nice idea but it would unbalance resources imo.
