### ISSUE TITLE
[Feature Request] Ability to hover over nearby teammates to see inventory

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#308]
This shouldn’t show the players full inventory. It should only show class-specific items like bombs for knights and arrows for archers.

It should look similar to how teammates hearts look (non-obtrusive).

It may help players know what teammates have to help them decide how to play in particular situations. I don’t expect this to immensely impact gameplay, especially in pub matches.

I’m willing to implement this myself if people are interested.

**Comment by Harrison-Miller** [comment]
Same deal as https://github.com/transhumandesign/kag-base/issues/739  I think this just to much to add to the game and not something you should really need 99% of the time.
