### ISSUE TITLE
[Feature request] Add superkegs to CTF

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#318]
Sometimes the only way to win a stalemate is through ratting.
Now i present to you a way to end a stalemate with a big bang.

A powered up keg, named the superkeg costs 250coins? in knightshop. (can be siegeshop for balance)
bigger explosion, heavier then a normal keg. longer timer.

https://www.youtube.com/watch?v=4JWyDrAS-kk&list=PL4HcOaO1UX7uhDWU0sqf9CFtJdVzm-EUe&index=2&t=0s

**Comment by Shylie** [comment]
I feel that an explosion that size is too large for only 250 coins. Perhaps if some changes are made, I will be on board with the change.

**Comment by eps0003** [comment]
The first team who get their hands on this keg will have a huge advantage. It’ll basically turn matches into a race for a super keg (if ratting hasn’t been successful), then the match would become one sided.

**Comment by Alainx277** [comment]
I think it's a nice idea, but I'd remove the explosion on impact, which makes defending almost impossible. The longer fuse time should be a debuff and not make using a catapult easier.
