### ISSUE TITLE
Pause ingame (Competitive or Captains)

### ISSUE THREAD

**Issue by HappySheepo** [transhumandesign/kag-base#319]
Hello everyone, i'm Sheepo and this is one of the idea i've come up with:

I suggest adding an option for any player to pause the game for a limit period of time. This would only be available on captains and competitive servers/matches.

For example, if several players are in a captains game and someone has to go pee, talk with family member, etc, they can pause the game for a limited period of time (i would set it at 5 mins) and then restart it with a countdown of 10 seconds.

The game could be unpaused in 3 cases:

a) The member who has paused, returned and decided to start again.
b) An admin decides that the pause took too long, or that the game should go on (with the member going to spec mode).
c) Most of the players ingame (over 50% active players, spec dont count) vote to unpause, pressing the standard surrender vote (O=Yes).

I think that could be extremely handy (obviously not applied to public games, that would be crazy haha).

This is an example of what looks like, in league of legends:
![pause](https://user-images.githubusercontent.com/46035291/50313652-59dc3300-04ac-11e9-8da8-e430ce4143de.png)

I would add in the text:

-"The game has been paused by XXX"
-"Time remaining: 5:00..."
-"Unpause? Press O"

I'm sorry i dont have any idea of designing and doing stuff, but i think the idea was enough good to post it here. :)

**Comment by bunniewormy** [comment]
good idea, but probably its going to only ever happen as a mod

**Comment by HappySheepo** [comment]
Close the thread then.
