### ISSUE TITLE
Feature Pitch: Adding heads to the scoreboard

### ISSUE THREAD

**Issue by HappySheepo** [transhumandesign/kag-base#321]
Hello everyone, it's Sheepo!

I suggest adding a small icon of the head between the name and the class icon (on the green area), so you can see the face of everyone. That would make the heads more interesting and the menu would look more complete.

![heads](https://user-images.githubusercontent.com/46035291/50315055-89da0500-04b1-11e9-8aa4-599ce5585915.png)

Thanks everyone for reading.

**Comment by Mazey** [comment]
Like the idea. You should add [Feature Pitch] to the title! ([info](https://forum.thd.vg/threads/contributor-bounties-coming-in-june.27696/))

**Comment by eps0003** [comment]
#331
