### ISSUE TITLE
[Feature request] Add new siege vehicle: RAM!

### ISSUE THREAD

**Issue by HappySheepo** [transhumandesign/kag-base#323]
Hello everyone, It's Sheepo and I have another idea to implement ingame, let's see what you think! :)

### RAM!
 ![image](https://user-images.githubusercontent.com/46035291/50363774-78eec980-056d-11e9-83b6-bbb95d1e47dc.png)

**_Summary_**

1. Introduction
2. Main characteristics
3. Offensive with RAM
4. Offensive against RAM
5. Visual idea

__________________________________

**1. Introduction**

We already have two siege items (catapult and ballista), but both of them are mainly used on highground:

*Ballista: Has respawn ability, can melt enemy base with bolts upgraded.
*Catapult: Can throw stones, boulders and players around the map.

Both of them are mainly made to be used at the top of the buildings, but they are pretty useless at the ground level.

My idea is to implement a new siege option, which is the ram. This would be a 3length x 2height vehicle that if you run for over 3-4 blocks, you damage/destroy 1 layer of blocks (1x2) from the enemy base.

__________________________________

**2. Main Characteristics:**

- Cost: 120 coins.
- HP: 3/4 of ballista/catapult
- No respawn option.
- Can be taken, with half timer than ballista/catapult.
- Wheels not removable (unlike other vehicles).
- Can be used by 1 or 2 players. If used by 2 players, the ram will move faster.
- No ceiling (players can jump around, throw arrows, etc).

__________________________________

**3. Offensive with RAM**

_Material --> Hits to destroy_

- Wooden blocks --> 1 hit
- Stone blocks -----> 2 hits
- Wooden doors  --> 2 hits
- Stone doors  -----> 3 hits

- You can kill players instantly if you have run for 3-4 blocks straight (the ram will stop completely because of the impact).

Note: You can't destroy backwalls or shops, so they don't get too op and collapse buildings.

__________________________________

**4. Offensive against RAM:**

- Normal swings/fire arrows will hit the ram, not the player.
- Standard bombs/Bomb arrows will hit both ram and player, since it's an explosion.
- Water bombs/Arrows affect players inside the ram.
- Pickaxe will work efficiently, like with cata and bally.

__________________________________

**5. Visual idea (Credit to Turtlebutt)**

![the ram](https://user-images.githubusercontent.com/46035291/50364496-75a90d00-0570-11e9-824e-4dc811cafe62.gif)

What do you think? In my opinion that would help to siege the ground level instead of encouraging rats to dig around! 

Thanks for reading this topic :)

**Comment by Turtlebutt** [comment]
![the gay gif](https://user-images.githubusercontent.com/41750971/50364424-907f7f80-0578-11e9-8eec-eceeb76a43a0.gif)
here you go

**Comment by HappySheepo** [comment]
wep

**Comment by Blubahub** [comment]
I'm working on this now...

**Comment by Harrison-Miller** [comment]
I think this feature died with democracy.
