### ISSUE TITLE
Drill tweaks

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#336]
Currently, fighting others with drill is currently a bit broken. When you start drilling an opponent, sometimes the damage happens instantly, and sometimes after some time (like 1 second or so), even with 0 ping. This should be fixed to make drill combat consistent.

Another problem is that it's sometimes hard to target certain blocks (specifically, when you're drilling forward in a 2-block tall tunnel, the upper block sometimes doesn't get damaged)

Another thing that I'd change is drills overheating after killing someone: you drop them basically right after killing someone with it. I think you should still be able to use it a bit and it should overheat slightly slower.

I also suggest adding a bar which says how heated the drill is: you could see for how much more you could use it and how fast it goes down. New players would also be able to notice that it goes down faster if you move, which isn't really a known mechanic.

![image](https://user-images.githubusercontent.com/39147836/50513126-095d6a80-0a96-11e9-9757-2a5e825de390.png)

**Comment by Orsovi** [comment]
The actual oveheating rate is good, otherwise, the drill will be way too powerful.
I agree with the bar or other indicator like maybe make the "scrrrrrrrchhhh" noise and animation sooner (rn it's just one hit before overheating, you havn't the time to take count of it)
