### ISSUE TITLE
Change the way slashing interacts with logs

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#337]
**Current in-game behaviour.**

Currently, sometimes knights help builders with cutting trees. Unfortunately, they don't know about the fact that their slashes also destroy logs, which makes the builder not get wood. I have this happen to me every few days.

**Proposed Change**

In the case it would be changed, I have 3 solutions:
1. Make slashes destroy logs slower, like require at least 3 slashes
or
2. Make slashes work like saws - convert logs into wood
or
3. Make slashes work like saws and convert logs into wood, but would only give 50% of normal wood 

Probably could use some testing or a democracy vote

**Comment by Orsovi** [comment]
i'm for 1 or 3
The 2 might be kinda OP

**Comment by Harrison-Miller** [comment]
I like the idea of number 3. Shouldn't be to difficult of change to implement, we should definitely get lots of opinions though.

**Comment by AsuMagic** [comment]
3 seems a bit unintuitive for me, much like drills giving 50% resources (IIRC).  
If a knight sees slashing logs drops wood, they will not necessarily assume that there is a loss of resources associated.
