### ISSUE TITLE
Feature Pitch: Archer grapple hits for damage

### ISSUE THREAD

**Issue by benjamingorman** [transhumandesign/kag-base#339]
An archer's grapple could hit players kind of like a whip, for a small amount of damage similar to a jab.

This would give archers more outplay potential especially against knights since they would be able to interrupt a slash more easily.

Also the grapple could potentially hit projectiles like bombs, bouncing them back at the thrower.

If the grapple hit a player I think it should retract instantly and not also hook onto the ground.

Pros:
* Encourages aggressive play from archers
* Outplay potential from hitting projectiles back. The main way archers die in CTF is from bombs hitting them.
* Interrupts knight slash at close range 

Cons:
* People could whip a player accidentally instead of grappling the ground
* The move could be spammed (but there could be a cool down)

**Comment by bunniewormy** [comment]
cons:
would make archer fucking OP

**Comment by starsoccer** [comment]
If the grapple could also be grabbed by others it would be less OP

**Comment by Franrek** [comment]
If you want to buff archer make the shooting better not add some strange new abilites

**Comment by Coroz** [comment]
a like just so i can troll a bit more as archer

**Comment by Shadowblitz16** [comment]
archer is already op. archer should not be used for front line combat but instead be more of a support class. this would make him worse.
