### ISSUE TITLE
CSprite::getTextureWidth() and CSprite::getTextureHeight()

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#341]
please add CSprite::getTextureWidth() and CSprite::getTextureHeight() functions that would return the width and height of a sprites texture.

this would be a shortcut for getting a sprites texture size without requiring the creation of a new texture.
this could be used for converting sprites for the use of rendering functions.

**Comment by Harrison-Miller** [comment]
Wish granted, it may be a little before this gets merged in.

**Comment by Harrison-Miller** [comment]
This has been merged into the game you can find the functions in Manual/Objects/CSpriteLayer.txt
