### ISSUE TITLE
Feature pitch: Make Bodies great again

### ISSUE THREAD

**Issue by Panky123** [transhumandesign/kag-base#355]
Bodies are boring and minus some shenanigans with mines the meta game is pretty tame. Id like to suggest we allow players to enter corpses in the same way we enter crates, giving a use to something that generally just litters the battlefield.

**Comment by CatWiz** [comment]
Hiding inside a body is weird and imo makes no sense. I would like to make it possible to store items inside bodies similarly to crates, but with less space. This would allow some interesting tactics, like hiding mines inside bodies to kill enemy that breaks them or storing resourses in a middle of battlefield without enemy builders noticing.

**Comment by Franrek** [comment]
> like hiding mines inside bodies to kill enemy that breaks them or storing resourses in a middle of battlefield without enemy builders noticing.

it is possible

**Comment by CatWiz** [comment]
I know, but it isnt as simple as crates and is in fact a bug that most players dont know about.

**Comment by Panky123** [comment]
get your own feature request libtards

**Comment by vicenteferrari** [comment]
@Panky123 Your previous comment has been hidden due to violating the code of conduct of this repository, please refer to it and try to act accordingly. If you keep up with this behavior there will be more severe consequences.

**Comment by Panky123** [comment]
Libtard too strong i rescind my attempt to make bodies great again
