### ISSUE TITLE
Broken mapcycle in tutorials and Save the Princess game mode.

### ISSUE THREAD

**Issue by Diprog** [transhumandesign/kag-base#36]
_**Tutorials:**_
- First green arrow loads the same map again (Tutorial01.png) and you can't complete the map after that at all (green arrow doesn't do anything).

_**Save the Princess:**_
- First green arrow loads the same map again (Princess01.png), and then everything goes well.

Console logs haven't any errors or warnings.
![screen-17-10-21-18-54-20](https://user-images.githubusercontent.com/17686295/31861539-ab22f10e-b737-11e7-88ae-90044a6ca138.png)

**Comment by 1bardesign** [comment]
This has been noted internally as well. It's likely due to a recent change in how mapcycles progress, I'll be debugging it today if I can.

**Comment by 1bardesign** [comment]
Fixed in both tutorial and STP from here on https://github.com/transhumandesign/kag-base/commit/3e95358f333eb522a07ea77cb273a5475f834b4f
