### ISSUE TITLE
Timer on 'suicide' option.

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#364]
I would like to see a simple timer on the suicide button so you cant spam it a 1000 times in a row.
5 or 10 sec should be more then enough to stop the pointless suicide spam that sometimes happens at the start of a new game.

**Comment by HappySheepo** [comment]
Who does that?

**Comment by AsuMagic** [comment]
@HappySheepo Wait, you've never seen that happen?

**Comment by Blubahub** [comment]
The thing I don't understand about this suggestion/Issue is why being able to click it 1000 times in a row affects the game - after all, the respawn time is about 10 seconds (and TDM respawning is non-existant).

**Comment by AsuMagic** [comment]
@Blubahub That is during warmup of CTF matches. Suicide spam causes a lot of particles to be emitted.

**Comment by BarsukEughen** [comment]
5 sec long cooldown is too long, shorten it up to a second or something, some modded gamemodes need you do press suicide button 2+ times to actually die, so that might affect it
