### ISSUE TITLE
Some strange bug with Hall's no-build zone

### ISSUE THREAD

**Issue by Diprog** [transhumandesign/kag-base#37]
![screen-17-10-22-19-18-37](https://user-images.githubusercontent.com/17686295/31864059-1169e738-b760-11e7-8db4-5dcb7486efdb.png)

**Comment by Mayer318** [comment]
Can you provide any details to help others reproduce this bug?

**Comment by Diprog** [comment]
Oh, it's not a bug. It's just a stupid hole made on map, so you can't close it with doors
![juggernaut](https://user-images.githubusercontent.com/17686295/31865094-5a5e3d0c-b771-11e7-9fed-fa4af821fd87.png)

**Comment by 1bardesign** [comment]
I'm not really sure what a better fix for this would be; you cannot remove the floor of a hall intentionally. Making a "better" no-build-zone would involve a lot of separate sectors which wouldn't be particularly great for performance. Maybe not too expensive though (just 3 zones for this screenshot), and I guess there aren't many halls. I'll think about it.

Is it a huge problem to just build a ladder there so you can walk over it? Most times I see the ladder and 2 doors below like in your screenshot.

**Comment by Diprog** [comment]
You know, I want some kind if perfection there xD

**Comment by 1bardesign** [comment]
Ok we'll do something for this. We're holding the build for a bit anyway.

**Comment by 1bardesign** [comment]
Fixed. Please test this once it's pushed back to github.
![image preview of working doors in floor](https://i.imgur.com/YYEIAsi.png)
