### ISSUE TITLE
[Feature Pitch] New drill stuff

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#383]
Reposting this as a feature pitch because i dont think anyone was working on this

Currently, fighting others with drill is currently a bit broken. When you start drilling an opponent, sometimes the damage happens instantly, and sometimes after some time (like 1 second or so), even with 0 ping. This should be fixed to make drill combat consistent.

Another problem is that it's sometimes hard to target certain blocks (specifically, when you're drilling forward in a 2-block tall tunnel, the upper block sometimes doesn't get damaged)

Another thing that I'd change is drills overheating after killing someone: you drop them basically right after killing someone with it. I think you should still be able to use it a bit and it should overheat slightly slower.

I also suggest adding a bar which says how heated the drill is: you could see for how much more you could use it and how fast it goes down. New players would also be able to notice that it goes down faster if you move, which isn't really a known mechanic.

![image](https://user-images.githubusercontent.com/39147836/52182035-3a4d5f80-27f9-11e9-8316-db239bd87505.png)

**Comment by Coroz** [comment]
its kinda broken that a heated drill can do 2 damage instantly

**Comment by AsuMagic** [comment]
@Coroz That behavior is caused by the drill applying "a lot" of damage but only at a low frequency. The correct behavior would be applying less damage but at a higher frequency (basically).

**Comment by Mazey** [comment]
This feature pitch has been selected by the community as a bounty for **20$**

To complete this bounty you should open a pull request with:
-Drill cools down quicker
-Add a visual representation of the drill's heat level, as seen in the OP.
