### ISSUE TITLE
`rebuild` does not work well with includes

### ISSUE THREAD

**Issue by AsuMagic** [transhumandesign/kag-base#389]
**Description**

Scripts that are not referenced in `.cfg`s are ignored when rebuilding. This makes `rebuild` behave poorly when modifying included scripts.

**Reproduction**

1. Run a singleplayer gamemode or in localhost mode
2. Modify a `*Common*.as` script
3. Open game console and type `rebuild`

No script will be rebuilt.

**Expected Behavior**

All scripts which have included the modified script should be rebuilt.

**Comment by bunniewormy** [comment]
can we also have rebuild work with .cfgs in the mod folder?

**Comment by AsuMagic** [comment]
That's what reloadall would be useful for
