### ISSUE TITLE
Quick class change duplication

### ISSUE THREAD

**Issue by Alainx277** [transhumandesign/kag-base#408]
**Description**

Due to the new quick class change feature (#373), clones can be created by spamming E and pressing the class buttons.

**Reproduction**

1. Join TDM gamemode
2. Spam E and change class at the same time
3. After a few seconds of doing this, at least one clone will be created

**Expected Behavior**

The player's class should be changed, and no clones should be created.

**Screenshots**

![clones](https://user-images.githubusercontent.com/26800509/53108204-eb146800-3536-11e9-972f-c72b6b7b0113.png)

**Comment by Harrison-Miller** [comment]
The fix is in progress. Thanks for finding and reporting this.
https://github.com/transhumandesign/kag-base/pull/409
