### ISSUE TITLE
Problems with video recording (F6) mode (red barrier, spectator, menus)

### ISSUE THREAD

**Issue by koihub** [transhumandesign/kag-base#411]
**Description**

Various bugs arise when using the F6 (recording) mode:

- Red barrier is not shown in CTF/TTH
- Hides cursor on main menu and hides text on in-game menu buttons
- Can't move camera as spectator (see #235 )

**Reproduction**

Steps to reproduce menu behaviour:
1. Go to main menu (before joining server)
2. Press F6 (cursor will disappear)
3. Join a server/singleplayer (GUI elements will have no text)

**Expected Behavior**

- Red barrier should stay visible
- Shouldn't be able to use F6 while in menu
- Should be able to move while spectating

**Screenshots**

![F6 disabled](https://user-images.githubusercontent.com/36970272/53142277-ed87b980-3558-11e9-877c-f0b3987bed9d.jpg)
![F6 enabled](https://user-images.githubusercontent.com/36970272/53141992-db594b80-3557-11e9-8965-697de4af16b5.jpg)

**Additional context**

From what I can gather this is due the engine disabling the  `onRender(CRules this)` hook for all rules scripts when recording mode is enabled. This is especially a problem for 'Spectator.as' as the code for movement is inside of `onRender`, so when the engine disables it movement stops.

**Comment by AsuMagic** [comment]
The correct behavior is that `onRender` should probably still be called but the scripts should individually verify whether HUD is disabled or not.
