### ISSUE TITLE
Walking noanim

### ISSUE THREAD

**Issue by Harrison-Miller** [transhumandesign/kag-base#414]
**Description**

Sometimes when coming off a one high block ledge your character will stop animating. This bug affects all characters (Knight, Archer, Builder).

**Reproduction**

1. Start a dedicated server (unlisted, passworded, TDM)
2. Join with two clients.
3. Switch to a mostly flat map, with large flat areas and one block high ledges. (Gamblers Den)
4. Make both clients come into view in the flat area.
5. On one client run off the ledge and continue holding the direction
6. repeat until on the other client you observe no animations while the player is walking.

Note: I've founded it's most easily reproducible if you try to hit the ledge at an angle, otherwise it seems random when it will or wont occur. But it will happen about 1/4th of the time.

**Expected Behavior**

After hitting the ground off the ledge the player anims reset and their walking animation plays.

**Screenshots**

https://youtu.be/qBlJ99RzQxk

**Comment by Harrison-Miller** [comment]
So this bug is due to deltas not getting synced if the change is to small.  If you print out the position of the blob while it's falling then reproduce the bug you can see that the player sends an update the frame before, then the error occurs because the player hits the ground the next frame the difference in the delta is smaller than the threshold so it's not sent. Because the clients never receive the final position the blob is above the ground and gains some velocity in order to return to the ground. Because the blob is not on the ground it the animations show the falling frames.

Some possible fixes might be to send a fullstate update instead of a delta whenever a blob hits the ground. Or We could just mask the issue via scripts by detecting the distance to the ground is smaller than the threshold.

**Comment by AsuMagic** [comment]
Seems like we found the root cause, it appears that while the owner player _does_ send the property properly, but for some reason the server does more threshold checking over that and sometimes fail to send the new state to clients while it should have.

**Comment by Harrison-Miller** [comment]
Fixed in engine
