### ISSUE TITLE
Various issues when a gamemode doesn't have a spectator team

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#430]
**Description**

- !m is unable to put you in spectator but still shows the visual stuff for moderation
- 5 min auto AFK is unable to move an admin to spectator

**Reproduction**

!m issue
1. Join sandbox
2. !r a player
3. !m

AFK admin issue
1. Join sandbox
2. Don't move for 5 mins

**Expected Behavior**

You should be moved to spectator

**Screenshots**

![image](https://user-images.githubusercontent.com/30195802/53549583-a5841a80-3b88-11e9-8abe-71428c699588.png)

**Comment by blackjoker77777** [comment]
Working on it.
Already fixed the first issue tho, will fix the AFK as well and make a PR later at night, as soon as I have time.
