### ISSUE TITLE
[Change Request] Make Capture Status Icon Transparent on Mouse Over

### ISSUE THREAD

**Issue by Zanzibur** [transhumandesign/kag-base#439]
Currently when you capture an enemy siege weapon a status icon is displayed showing you how long it'll take to capture and how many friendlies are in the capture radius. The problem I have with this is that the icon can obscure combat around the thing you are trying to capture. For example, if the enemy has a ballista underground and you're approaching from above, the icon can block your visibility of your surroundings as seen here
<img width="576" alt="example" src="https://user-images.githubusercontent.com/39106491/53687458-cec8b600-3d02-11e9-9b3d-c3693bfa6493.png">

My proposal is to make this icon transparent upon mouse over like speech bubbles. It may also be a good idea to apply this change to emote bubbles as well.

**Comment by Andresian** [comment]
I will work on this.

**Comment by Mazey** [comment]
This feature pitch has been selected by the community as a bounty for **20$**

@Andresian has shown interest in implementing this bounty. Working on this without approaching him is ill-advised.

**Comment by eps0003** [comment]
Implemented in build 3090
