### ISSUE TITLE
Singleplayer TTH tutorial is broken

### ISSUE THREAD

**Issue by AsuMagic** [transhumandesign/kag-base#443]
**Description**

When capturing a hall in the TTH tutorial "blue team" instantly wins.

**Reproduction**

1. Singleplayer -> Tutorials -> Take the halls
2. Capture a hall
3. The game will be end shortly

**Expected Behavior**

The game should not end.

**Comment by Vam-Jam** [comment]
Can be closed now, since its been fixed
