### ISSUE TITLE
Re-implement arrows stacked on players after hit

### ISSUE THREAD

**Issue by ewetcr** [transhumandesign/kag-base#466]
Back int he day when you got hit by a regular arrow, it would remain undefinedly attached to your character. I'm sure with the current level of optimizations it wouldn't be very demanding.

![arrows](https://user-images.githubusercontent.com/46571457/54481407-83e78c00-4834-11e9-859f-c29bd35a2d81.PNG)

**Comment by eps0003** [comment]
That would sorta hide animations and be quite distracting imo

**Comment by Zanzibur** [comment]
Maybe limit the number of arrows that can stick? It would be cool to see this back in the game.

**Comment by Harrison-Miller** [comment]
I don't think it's really that big of a deal or an issue of hiding anims. Would also love to see this back.

**Comment by Shadowblitz16** [comment]
I disagree I have enough lag with kag 
I don't need a visual effect slowing it down further

I would agree to this if it was a option in settings and what done client side

**Comment by AsuMagic** [comment]
> I disagree I have enough lag with kag
> I don't need a visual effect slowing it down further
> I would agree to this if it was a option in settings and what done client side

It could get disabled in the fast graphics mode (which is already exposed script-side).

Performance side it should not be too bad. The `CAnimSprite` optimizations that has landed with the 60fps+ build and beyond should mitigate the lag.

I tested it myself a while ago and it was a bit imperfect in how the arrows would appear.  
It might be a sensible idea to put the arrows on the background layer, as to prevent arrows from hiding animations.

**Comment by Harrison-Miller** [comment]
To sum up the discussion and what I want to see from an implementation
* disabled on fast graphics
* Instead of a limit to how many arrows can be stuck in you, make the arrow decay and disappear after 30 seconds (with wood gibs)
* Arrows can stick in any class, migrants, shark, bison and vehicles.
