### ISSUE TITLE
(CTF) More war/fight stat in the scoreboard  *feature pitch*

### ISSUE THREAD

**Issue by ferlinpinpin** [transhumandesign/kag-base#474]
could it be possible to add a team kill and death counter in the scoreboard menu ?

I think it could be cool to know in the scoreboard (tab) how many live it took to a team to triumph a fight.
It would let you imagine how many worthy fighters and folks you lost to reach or not the victory.
Maybe it would give a sensation of bond between each other teamate. 
:P

**Comment by Harrison-Miller** [comment]
Gonna close this the scoreboard can't handle any more information.
