### ISSUE TITLE
Tournament heads use the wrong gibs

### ISSUE THREAD

**Issue by amgassert** [transhumandesign/kag-base#480]
**Description**

When a person using a tournament head is gibbed, the wrong head gibs are used. Each custom head consistently uses the gibs of one other head. In the linked videos, one can see that the deer skull tournament head uses the gibs of the snake tournament head, and the PUBG helmet tournament head uses the gibs of the princess head from the fantasy DLC head pack. Presumably other tournament heads also use the gibs of some other head.

**Reproduction**

1. Join any server while using a tournament head
2. Put a bomb inside inventory or have another player destroy your corpse
3. Observe the game's use of the wrong head gibs

**Expected Behavior**

Each tournament head uses its own head gibs.

**Videos**

https://gfycat.com/RashSnoopyAgama
https://gfycat.com/TiredSillyFirebelliedtoad

**Comment by bunniewormy** [comment]
This does not seem to happen any longer (tested with my head and Tern head)?
