### ISSUE TITLE
Bring back stone backwall helping against fire spreading

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#492]
**Current in-game behaviour.**

A few updates ago, if you placed stone backwall behind doors/platforms, fire didnt spread as much as it did without it. It got removed with the fire improvements, i'm pretty sure. I think that fire arrows are too OP now tbh.

**Proposed Change**

Bring back what we had before the update - fire doesnt spread as much if you put stone backwalls behind platforms/wooden doors.

**Comment by ParaLogia** [comment]
Stone backwall definitely still does affect the spread of fire. It's especially obvious if you build a straight platform wall and stone backwall it. Fire will sometimes only break 3 plats, then stop. There's pretty much no chance of that happening with unbackwalled plats.

**Comment by bunniewormy** [comment]
yeah, but its become a lot more random right now which is annoying - sometimes it can destroy 6 backwalled doors, sometimes only 1. i believe this should still be changed back.
