### ISSUE TITLE
Implementing official server rule set

### ISSUE THREAD

**Issue by EHRaaaa** [transhumandesign/kag-base#499]
Now that the refined rule set is complete I would like to start moving onto implementing it, especially before f2p.

**Short term (needs to be done)**

- MOTD style with popup on officials (Geti said there is a basic template and Mehwaffle had a working popup design of this, though depends on how it would best be implemented)
- Discord announcement
- Forum announcement
- Main screen button (similar to how the wiki/discord is now.) Maybe even an in-game esc menu button. This relies on the rules hosted on a website, worst case scenario this could just be linked to the forum announcement/post.

- Uploaded to a website (depends on how @furai @jrgp can implement this/if they have spare time)

**Longer term/not pressing goals**
- Discord channel/addition to the existing rules channel with an official rules section
- Possible Github integration/auto updating website (this is more up to furai/jrgp to implement, most likely not even needed)

@1bardesign @AsuMagic @Harrison-Miller @Shylie @eps0003 

https://docs.google.com/document/d/1gDU54c0EQqm8ixaof2C797ba7H6rBRJkuZ0FgS801SM/edit?usp=sharing

**Comment by EHRaaaa** [comment]
I created a github pages for the rules due to limited feedback on having them implemented onto another website. I think having an official github project page for the rules could be a "good enough" implementation. 

https://ehraaaa.github.io/

@1bardesign @furai

**Comment by 1bardesign** [comment]
Interesting idea, might be a nice workaround!

Contrast could be a little better especially for links already clicked:
![example of poor contrast area](https://i.imgur.com/W8xsmAX.png)

I think something like that could be a good idea @furai - maybe we could have kag_rules.github.io or similar and just have a small repo with a single markdown file in it? Could avoid having to retool the kag2d.com site every time something changes.

**Comment by EHRaaaa** [comment]
Yeah for sure, it's up to you guys on how you would like it presented.

Probably the easiest way is to specifically make a "project page" under the existing THD account. I'm not sure on the specifics on how to do this, but the link would end up looking something like transhumandesign.github.io/kag_rules

**Comment by 1bardesign** [comment]
Forked and partially rebuilt [this](https://github.com/transhumandesign/kag-official-server-rules) - visible on github pages [here](https://transhumandesign.github.io/kag-official-server-rules/). Still need to point in-game rules link there.

**Comment by Vam-Jam** [comment]
Mostly done, EhRa wants it closed
