### ISSUE TITLE
Descriptions in Trading Post on TTH are translated by server.

### ISSUE THREAD

**Issue by Diprog** [transhumandesign/kag-base#51]
![screen-17-11-01-10-08-49](https://user-images.githubusercontent.com/17686295/32264001-8ffb7618-beed-11e7-80a1-6edb7babe172.png)

**Comment by 1bardesign** [comment]
The descriptions one is interesting. We will need to translate them later on then (clientside).

I wonder about the scrolls. Obviously it's the costs change but it "should" be fine?..

Either way, will need to put out a hotfix for this.

**Comment by Diprog** [comment]
@1bardesign I think we can do something like `void TranslateDescriptions()`
And put a `TranslateDescription(string &in desc)` function for all strings.

**Comment by Diprog** [comment]
Hmmm. I've just copied KAG and called it "KAGServer", run it with `g_locale = en`, joined from normal KAG with `g_locale = ru` and all descriptions were translated.

**Comment by Diprog** [comment]
Ok, found the problem. It's only TTH, because items are set in rules script `WAR.as` by server.

**Comment by 1bardesign** [comment]
Ok so this only requires changes to fix the descriptions issue still, correct? I can handle that soon.

**Comment by Diprog** [comment]
Yep

**Comment by 1bardesign** [comment]
OK, pushing a fix for this soon;

This is on EN dedi with RU client:
![working translated RU for explosive scroll on EN server](https://i.imgur.com/xSB75L4.png)

There seems some missing translations for these but I imagine these are in the new translation PRs; hopefully they merge ok!

**Comment by 1bardesign** [comment]
Please review 77e0f9317bb46e82731cc6beb7228c72a1144959 and current head on test build and ensure this works as intended, then close. 👍 

(test build will be updated with these changes and more within 30min of this post)

**Comment by Diprog** [comment]
![screen-17-11-14-07-20-43](https://user-images.githubusercontent.com/17686295/32762766-63411cb2-c90c-11e7-8d15-6c06206eaca6.png)
![screen-17-11-14-07-20-44](https://user-images.githubusercontent.com/17686295/32762767-6362edb0-c90c-11e7-8333-6ce880cf2a0c.png)
hmmm

**Comment by Diprog** [comment]
So, descriptions without icons are not translated

**Comment by 1bardesign** [comment]
Ah, found it. Will push a fix in a minute.

**Comment by 1bardesign** [comment]
Should be fixed in 09e752c323de5e9dbb2f99c2622699d575f62025

**Comment by Diprog** [comment]
Waiting for the test build then to make sure that everything works fine

**Comment by Diprog** [comment]
It's 7;30, so I need to go to college. Will test it later.

**Comment by 1bardesign** [comment]
No problem. It should have just gone live but I'm not in a rush with this; just close the issue if you're satisfied that it's fixed and thanks for your rigor 🙂

**Comment by Diprog** [comment]
Closed. Don't see any reason for in not to work.
