### ISSUE TITLE
[Feature request] Ability to link your Discord account with your KAG account

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#511]
Adding the ability to link your KAG account with Discord would allow people to make Discord bots which directly interact with KAG. This would be similar to how you're able to link your Patreon account with KAG. Bots like the Gather bot would benefit most from this, especially if this will *hopefully eventually* be put on the Official KAG Discord.

**Comment by AsuMagic** [comment]
Plus this could be helpful when reporting people so admins can get extra info by contacting you on Discord after you made a report.

**Comment by Omen267901** [comment]
I agree. It would also allow for streamlining of reports potentially.

**Comment by Vam-Jam** [comment]
https://kag2d.com/en/discord being worked on by furai
