### ISSUE TITLE
[Feature Request] Menu when holding pickup key

### ISSUE THREAD

**Issue by Banzai99** [transhumandesign/kag-base#512]
**Idea** : Make a menu appear when holding the key to pickup items when standing on multiple items.

**Description of the feature** :
The idea behind is that it wouldn't be any longer to have some sort of wheel (like the emotes one for example, but smaller) that appears when you hold the pickup key and it would be pretty convenient as I often find myself just spamming and throwing the items away until I get the one I want (which is not what you wanna do when there is 4 knights around you as archer)
The items could always appear at the same place on the wheel, to allow consistency and fast actions.

**Comment by Mazey** [comment]
Not a bad idea, but it needs to look very neat to not be annoying during gameplay.
(ignore the assignee thing, I missclicked when adding labels :)

**Comment by AsuMagic** [comment]
Another solution would be to show buttons which might work better imo. The point is that it would be mostly only useful when there is ambiguity in the items to pick up, since buttons push each other already.

**Comment by Omen267901** [comment]
I'll agree that something should be done here. It's very frustrating when a bunch of things are close to each other and you can't pick up the correct item and have to toss things away to get to the right item.

That being said, some kind of button menu might be better. Possibly have it be a double-press of the pickup button so you don't activate it unintentionally? Would pop up a menu like storage caches showing all the items on the ground near you.

This solution does still have the issue of not being super applicable in combat when you need to pick up those fire arrows and not that stack of wood or your builder's corpse, but I'm not sure what a solution to that could be.

**Comment by Banzai99** [comment]
So there are multiple solutions :
- The wheel option, if well integrated, could make the job because it's fast and just requires a cursor move, no precision
- Buttons, requires a bit of precision, but maybe more convenient
- A simple "inventory" of what's on the ground
I think all theses solutions are applicable in combat if well integrated, but we still have to find the best one or the easiest to setup in code.

**Comment by Harrison-Miller** [comment]
I think bunnie's idea shift+c is a good compromise since it needs to be useable quickly for bombs/kegs. instead of holding c and waiting for the menu. And I think the wheel solution is well thought out.

Closing this issue since - but it's linked in the other issue for reference.
