### ISSUE TITLE
Ability to specify a different "mods.cfg" for a KAG executable

### ISSUE THREAD

**Issue by Diprog** [transhumandesign/kag-base#518]
The problem is that you have to create a new KAG folder for a modded server, if you have some servers running already.
The only workaround for this is to specify mods in server_autostart.as, but any changes to the game files make a server to display as a modded server, so all servers hosted from the same folder are gonna be marked as modded.
For example:
`if (sv_port == 50301) {}
else if (sv_port == 50302)
{
    AddMod("ExampleMod");
}`
I asked for that feature a long time ago, but now we have a github repo, so here we go.

**Comment by Alainx277** [comment]
Working on this!

**Comment by Alainx277** [comment]
Sorry for the long wait, it should be available in one of the next updates.

**Comment by eps0003** [comment]
Implemented several builds ago
