### ISSUE TITLE
Make suicides not lose coins in build time

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#522]
**Current in-game behaviour.**

If you commit die in build time, and had some coins already, you lose some coins

**Proposed Change**

If you commit die in build time, and had some coins already, you do not lose coins

**Additional context**

Useful for getting back to the tent for resupplies, but the fact that u lose coins means you just have to walk to the nearest builder shop or tent

**Comment by eps0003** [comment]
To extend on this, maybe also don't show kills on the killfeed during build time. This might reduce the likelihood of someone spamming suicide without needing a cooldown.

**Comment by AsuMagic** [comment]
@eps0003 Disagreed, this would hide teamkilling from the team and admins.

**Comment by bunniewormy** [comment]
maybe just hide suicides only, then?

**Comment by Omen267901** [comment]
Agreed. Only hide suicides.

**Comment by MatheusGodoi** [comment]
The suicide cooldown was implemented to stop suicide spamming on the build time already, hiding it to prevent spam would be strange as there is already a mechanic for that imo
But stop losing coins is gud

**Comment by blackjoker77777** [comment]
I think the idea of having it removed from the kill-feed **[during warm-up only]** would be a good way to improve visibility? 
it's as simple as: If you're still warming-up, and you see someone got killed, it's easier to assume who's the one responsible for the teamkill.
seeing something like:

> A killed B
> A killed C

is easier on the eyes than:

> D suicided
> E suicided
> A killed B
> A suicided
> D suicided
> A killed E

Especially that removing the coins reduction after suicide, would reinforce using the suicide button as a "refill/better mobility" function during building phase; which might imply that people would be using it, way much more than usual.

I have already finished working on this. I'd include it in #510 in the next few minutes/hours hopefully.
