### ISSUE TITLE
Make new players drop hearts when killed by new players

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#523]
**Current in-game behaviour.**

New players [under 2 weeks, i believe] dont drop hearts when killed. This was done to prevent pubstompers from constantly healing on new players

**Proposed Change**

I think they should drop hearts again, but only if killed by new players as well. If killed by veterans, they shouldn't

**Comment by Omen267901** [comment]
I personally hadn't even realized this was a mechanic. It seems like an odd handicap to me, but I definitely do understand the sentiment. Pubstomping sucks and can easily drive new players away in droves, and finding ways to combat it without making the game frustrating or annoying for older players is a struggle.

I think this might be a good solution for the time being.
