### ISSUE TITLE
Enemies can spawn from ballistas while it is being captured.

### ISSUE THREAD

**Issue by ShnitzelKiller** [transhumandesign/kag-base#536]
**Description**

See title

**Reproduction**

1. Join TTH.
2. Sit on an enemy ballista, observe the capture bar appear, indicating that it is being captured.
3. Watch them continue to spawn from it, blocking you from capturing it further.

**Expected Behavior**

Since this was explicitly a bug that was already fixed in CTF, obviously the intended behavior is for enemies to be blocked from spawning while the ballista is being captured.

**Comment by Trumbles** [comment]
Locking out respawns during capture is definitely a good idea.

**Comment by Gingerbeard5773** [comment]
resolved issue?

**Comment by AsuMagic** [comment]
Ballistas aren't respawn points anymore
