### ISSUE TITLE
Make 'incorrect blob property' error more detailed

### ISSUE THREAD

**Issue by Pirate-Rob** [transhumandesign/kag-base#537]
https://gyazo.com/cb6321c64d626c76a2201e1afc090ceb.png

Currently, when setting or accessing a blob's properties incorrectly, it displays the above message. For clarity's sake, I request the numbers (was 2 is 4) be changed to:
(initially u16, tried u8)

**Comment by eps0003** [comment]
Resolved in engine-side pull request #​102

**Comment by eps0003** [comment]
Implemented several builds ago
