### ISSUE TITLE
Solo game modes are bugged after playing on a server.

### ISSUE THREAD

**Issue by Diprog** [transhumandesign/kag-base#54]
You spawn as a random thing and can't play.
Also a lot of random objects are spawned too.
Sandbox game mode:
![screen-17-11-08-10-57-44](https://user-images.githubusercontent.com/17686295/32537483-e1783dc4-c473-11e7-8ac9-c244b687c0d7.png)

**Comment by 1bardesign** [comment]
Opposite happens too; this is a huge issue, but the fix is much more complicated than it should be. It's on our internal list for a long time.

**Comment by AsuMagic** [comment]
It should be fixed this build, MM has commited a fix for those precache issues.
