### ISSUE TITLE
Start Server Button for mac users

### ISSUE THREAD

**Issue by xXIlluminatiPartyXx** [transhumandesign/kag-base#549]
I believe you should be able to start a server with a click of a button; on mac its almost impossible to start up a server because some of the files required don't exist on mac. All it needs to be is a button that runs that file and gives you server settings. I have tried starting a server on mac before, and I tried for about an hour before giving up searching for the file. Thanks!

**Comment by Mazey** [comment]
Hosting servers is officially only supported on Linux, for which we also distribute a server package.

**Comment by xXIlluminatiPartyXx** [comment]
Ah i see thanks

**Comment by AsuMagic** [comment]
You can create a script easily:

```
./KAG nolauncher autostart Scripts/server_autostart.as
```
