### ISSUE TITLE
Heroes

### ISSUE THREAD

**Issue by xXIlluminatiPartyXx** [transhumandesign/kag-base#551]
If you kill enough people or build enough blocks to get enough points then next time you respawn you can choose to be a hero. Each team is restricted to 2 heroes and they have significantly more health and damage than normal characters. If a normal player kills a hero they receive a lot of gold and get a buff of some sort. A good reward.

I have two examples:

Example one would be a white knight that has about 15 hearts and does 1 extra heart of damage. Slightly increased speed and slow health regeneration.

Example two is a robin hood figure that always shoots three arrows at a time but only uses 1. Robin hood also have 5 hearts and faster speed and longer grapple hook. Robin can also go through opposite facing platforms.

Hope you like the idea

**Comment by eps0003** [comment]
I recommend you turn these ideas into a mod. I think these ideas would work well, but not in vanilla KAG.

**Comment by Alainx277** [comment]
I agree with eps, it should definitely not be added to vanilla. The skill difference between players is already high, imagine giving the best players more than 3x the health of normal people.
