### ISSUE TITLE
TTH swapping class makes items dissapear

### ISSUE THREAD

**Issue by MatheusGodoi** [transhumandesign/kag-base#553]
**Description**

When playing TTH, if you have something in your inventory that you don't get when changing classes/respawning (bombs, arrows, materials, etc) and you swap class, all the items will vanish; they won't be dropped on the ground, won't appear again, they just get erased.

**Reproduction**

1. Join TTH
2. Put some items in inventory (fish, burguers, grains, drills, buckets, sponges, bodies, etc)
3. Swap class

**Expected Behavior**

They should drop to the ground.

**Screenshots**

First image: I have a fish, a lantern, a bucket and a drill
![1](https://user-images.githubusercontent.com/31485083/56914205-dfd73e80-6a89-11e9-925c-31f6cfa830db.png)
Second image: After swapping class, all the items dissapear
![2](https://user-images.githubusercontent.com/31485083/56914234-f087b480-6a89-11e9-9905-0f3a7f03f1f7.png)

**Additional context**

Items like bombs/water bombs, normal/special arrows and materials seem to dissappear, but when you swap classes back they appear again, but im not 100% sure.

**Comment by blackjoker77777** [comment]
iirc when swapping classes, your inventory gets stored into the hall storage, if you press E and click that storage button you'll find what seems to have gone missing.
When swapping a class you'll automatically get the items related to said class (bombs for knights, arrows for archers, resources for builders).
I may be mistaken, didn't play TTH for quite some time; but as far as I recall, it used to be (and probably still is) working like that.

**Comment by MatheusGodoi** [comment]
epic magmus hehe
