### ISSUE TITLE
Holiday event - Thanksgiving

### ISSUE THREAD

**Issue by Asleste** [transhumandesign/kag-base#564]
The background of the game changes, The players would be dressed as pilgrim, there would be turkeys in the game and the trees would have a different tonality. (Sorry if the idea is very basic, Any suggestions or ideas are welcome)

**Comment by Artis823** [comment]
Great idea but you could add snow and the idea with turkeys as BURGERS would be very good

**Comment by Trumbles** [comment]
Cool idea.

**Comment by eps0003** [comment]
Closing this because it is celebrated only in a select few countries.
