### ISSUE TITLE
Flag back tiles cannot be damaged

### ISSUE THREAD

**Issue by AsuMagic** [transhumandesign/kag-base#569]
**Description**

Title, essentially.

**Reproduction**

1. Join singleplayer Sandbox
2. Create a flag base using `!flag_base`
3. Change teams with `!team 1`
4. Try to break background tiles in any way (hammer, explosives)

**Expected Behavior**

Back tiles should get destroyed.

**Additional context**

I don't think this is intended, but it is far from intuitive and annoying IMO.  
In many instances, you may find yourself trying to collapse an enemy tower that has a flag base as its foundation. This makes it significantly harder to destroy it.

**Comment by Panky123** [comment]
You shouldnt be able to collapse the flagroom that is why the background(and if blocks were put there in .png) are indestructable. The flagroom(the 5x3 area) should be protected until you lose the flag. If this change goes through then explosive spamming the flagroom will not only create a deathzone, but itll collapse the room afterwards. Leaving the defending team little option.

**Comment by Harrison-Miller** [comment]
Closing because above, we shouldn't change flag room protection.
