### ISSUE TITLE
Change Request: Team Balancing

### ISSUE THREAD

**Issue by pajrc1234** [transhumandesign/kag-base#570]
**Current in-game behaviour.**

While teams are unbalanced (due to players leaving), players from the team with _fewer_ players are prevented from switching teams and are "balanced back". However, when new players join, they might be assigned to _either_ team, which may be the team with more players.

**Proposed Change**

When a person joins a game with imbalanced teams, they should always be put on the team with fewer players.

**Comment by bunniewormy** [comment]
> However, when new players join, they might be assigned to either team, which may be the team with more players.
nope, doesn't work like that

**Comment by Mazey** [comment]
New players always get assigned to the smaller team, perhaps you were playing a mod with custom gamemode rules.
