### ISSUE TITLE
Pike spikes

### ISSUE THREAD

**Issue by xXIlluminatiPartyXx** [transhumandesign/kag-base#571]
Basically its a normal spike that doesn't retract when a player is standing on it and it deals constant damage to any enemy in it while its active. If its on wood its basically a bigger hitbox spikes. Costs 65 stone

**Comment by Omen267901** [comment]
I'm not entirely sure what the advantage is here. Spikes already deal constant damage if placed on stone, and they cost 30 (10 for the stone, 30 for the spike). I'd be more apt to see punji sticks or something like that as a form of wooden spikes that deal less damage and only hit once.

**Comment by xXIlluminatiPartyXx** [comment]
What I mean is, the spikes dont retract like stone spikes but stay inside the person to do about quarter of a heart per half of a second

**Comment by Omen267901** [comment]
> What I mean is, the spikes dont retract like stone spikes but stay inside the person to do about quarter of a heart per half of a second

This functions exactly the same as regular spikes, just with a different visual (and are actually weaker I believe). Unless you mean that the spike breaks off and sticks inside the player, in which case that sounds like a horrific waste of stone and an incredibly niche application.
