### ISSUE TITLE
Lockers

### ISSUE THREAD

**Issue by xXIlluminatiPartyXx** [transhumandesign/kag-base#575]
Don't you just hate it when you buy bomb arrows and leave them so you can get them later, or after you die, and someone has taken them? I have a solution to this problem and it will stop all of your worries.

I propose you add am item called the locker that costs around 100 stone and is a 1 x 2 block. If its your locker then when you walk up to it a star symbol will appear and you can open it. It contains a 4x4 grid of space for you to put your items in! However no one else can take these items!

If an enemy builder gets in to your base then watch out! They could destroy your locker and take all of its loot!

This would be an interesting addition to the game and it will allow you to give your next life some items that will boost its worth! Remember that items that cannot go in inventories cannot go in the locker so don't bother trying to put the enemy flag in your locker.

**Comment by MrPotatobird** [comment]
That would be a waste of stone. Think of it from a team perspective, you're literally investing 100 stone in a way to prevent your team from using items. What valid reason do you have to store 4 bomb arrows or whatever in a locker? Wouldn't you want to use them? What happens if you leave the game?

Anyway if you really want to hoard stuff for fun, do what I do and stash it in a crate in a nice dark cave.

**Comment by xXIlluminatiPartyXx** [comment]
Basically if you dont want to lose your bomb arrows or if you can afford lots of bomb arrows and cant hold them all this might come in handy, if you leave the game your locker stays there

**Comment by AsuMagic** [comment]
> Basically if you dont want to lose your bomb arrows or if you can afford lots of bomb arrows and cant hold them all this might come in handy, if you leave the game your locker stays there

This would make it so you're essentially spending resources into actively preventing your team from profiting from your excess coins and take virtually no risk of losing coins when doing that.

**Comment by Panky123** [comment]
Allowing you to lock a crate with coins/a type of resource might be a more agreeable addition.

**Comment by MrPotatobird** [comment]
> Allowing you to lock a crate with coins/a type of resource might be a more agreeable addition.

Eh, it still has the same fundamental problem of being an anti-teamwork change. It does sound easier to implement though. But the strangeness of the crate button is already kind of pushing it, so it would probably be better to have two different types of crate in the store, locked and unlocked, like a chest vs. crate. Not that I think that would be a good idea.
