### ISSUE TITLE
Revert auto-swap nerf for archers

### ISSUE THREAD

**Issue by ewetcr** [transhumandesign/kag-base#576]
**Current in-game behaviour.**

Since a few months ago the archer special arrow swapping doesn't work as it used to, it's fairly awkward in comparision. If you are out of regular arrows and buy a special one (fire/water/bomb), the arrow type doesn't automatically change to the only arrow you are capable of shooting, and you have to do it manually, not by tapping F but by opening the arrow menu. 

**Proposed Change**

I'd like the behaviour to be reverted to the previous system, where whenever you only had 1 type of arrow the type selected would automatically become that one or it would fastly change by tapping F. 

**Additional context**

**Comment by Harrison-Miller** [comment]
Let's go with trying to figure out why tapping f is broken in this situation.
