### ISSUE TITLE
Building interaction while inside crate

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#577]
When inside a crate, the only way out is to jump out and break the crate.

But if you are also near a workshop of another class, you can switch to that class which makes you leave the crate without breaking it.

The other thing you can do is you can sleep in the quarters while staying in the crate. You can cancel your sleep by pressing "up", which makes a headless sprite appear at the quarters, but you will still be in the crate.

**Comment by bunniewormy** [comment]
i believe it was done for gameplay reasons - so you couldn't re-use crates like that. i believe the changing class part is a bug

**Comment by Panky123** [comment]
Not a bug just an unintended feature
