### ISSUE TITLE
Unable to change zoom level while in spectate

### ISSUE THREAD

**Issue by Zanzibur** [transhumandesign/kag-base#579]
**Description**
Upon being put in spectate mode, I am unable to adjust the zoom level.

**Reproduction**
Join a match, any mode that allows spectate will work. Either die or switch to spectate, then try to change zoom level. 

**Your Setup:**
- OS: macOS Sierra 10.12.6 
- KAG Build Number: 2936 

**Additional context**
This may just be a weird osx thing, as I haven't heard of anyone else having this problem.

**Comment by bunniewormy** [comment]
Happens on all systems, should definitely be fixed because max zoom out while in spec is the best

**Comment by CharlesAMiller** [comment]
Does anyone know if this remains a problem? I haven't been able to recreate this issue with modern builds.

**Comment by bunniewormy** [comment]
This only happens on 30fps apparently and I think I can blame @AsuMagic for that

**Comment by Vam-Jam** [comment]
removing good first issue, engine bug

**Comment by Gingerbeard5773** [comment]
Check if this still happens

**Comment by bunniewormy** [comment]
it still happens
