### ISSUE TITLE
Unable to cancel vote kicks on osx

### ISSUE THREAD

**Issue by Zanzibur** [transhumandesign/kag-base#580]
**Description**
I am unable to cancel votes. In testing, I found the usual key combination workarounds sometimes needed on macs didn't resolve the issue

**Reproduction**
Have someone with a mac join a server with another user. Have that other person start a vote (Can be nextmap, votekick etc.), try to cancel the votekick.

**Your Setup:**
- OS: macOS Sierra 10.12.6
- Build Number: 2936, this issue has persisted for quite a while however. I can't remember exactly when I first noticed it, but I recall testing it possibly around Feb of this year.

**Comment by AsuMagic** [comment]
What servers? This might be a seclev issue.

**Comment by Zanzibur** [comment]
Could be, I've only tested it on official servers.

**Comment by Harrison-Miller** [comment]
Support for MacOS was dropped.
