### ISSUE TITLE
Block inside flag

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#588]
Normally you cannot place blocks inside flags. I think at least until the flag has been captured.

I had a game where enemy had a stone block inside of the flag, and it was not possible to destroy it as builder. So it was kind of game-breaking. We don't know how it occurred.

https://i.imgur.com/Z7rGmHR.png

When I find more info, I will update here.

**Comment by eps0003** [comment]
Gather has a change to FlagBase which makes it clear blocks after a few ticks of the map generating. This might be a quick and easy fix for this assuming the blocks are being placed by the map and not somehow by players.

**Comment by eps0003** [comment]
https://cdn.discordapp.com/attachments/658249429274460184/764473747125698580/unknown.png

**Comment by eps0003** [comment]
Apparently fixed in #980
