### ISSUE TITLE
Rare bug causes red area to be displaced

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#596]
This bug causes the red area to be displaced to the right, causing an unfair disadvantage for the red team

1) https://forum.thd.vg/threads/about-eu-ctf-storm-the-castle-fire-and-wood-server.28110/

2) https://i.imgur.com/GgAKMef.png

**Comment by regakakobigman** [comment]
Had this happen too in CTF. It only affected me on the blue team.

Maybe related to recent changes in #114?

**Comment by mugg91** [comment]
I first posted about this issue (see number 1 above) on May 5th. Your #144 link says it was done on May 28th. So maybe that's not it.

**Comment by AsuMagic** [comment]
... 2018 :)

**Comment by mugg91** [comment]
Nevermind then. lol

**Comment by Blubahub** [comment]
https://forum.thd.vg/threads/about-eu-ctf-storm-the-castle-fire-and-wood-server.28110/#post-409581

**Comment by Vam-Jam** [comment]
#691 this PR was added a few updates ago, should have reduce this error. Open up a new issue if this still happens.
