### ISSUE TITLE
Mark your area in sandbox

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#597]
In sandbox servers I'm pissed that people jump into my unfinished creations and start changing and breaking stuff. I don't know if this is a good idea, but I'd like it if I can somehow block access to my creations. As in, I have my 20x20 area that other players cannot walk into (similar to red area in CTF/TTH). Maybe have it limited (by a 5 minute time limit and can only use it once every 30 mins or so).

Of course you'd have to think about how this could be abused, for example to lock people in, etc.

The basic idea is that I want to release my creations to others when they are completed. And not when they are uncomplete.

**Comment by eps0003** [comment]
I like the idea of this, but in practice, it'll probably lead to trolling. If people are worried about griefers, they may as well build in singleplayer and share screenshots. I do see the appeal in building with others on a multiplayer server though.
