### ISSUE TITLE
!gold abuse in sandbox

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#598]
Gold does not despawn, it seems.

It is possible to bring a sandbox server to its knees by !gold spam to spawn 1000+ gold heaps, which causes framerate to become >1 FPS.

Possible solutions:
* Cap the amount of commands you can send
* Limit the amount of gold (and other objects that don't despawn) on the field at the same time (For example, only allow each team to have 20 boats, boulders, etc. at maximum).
*

**Comment by Harrison-Miller** [comment]
That or just make things that don't despawn, despawn in sandbox.

**Comment by Harrison-Miller** [comment]
ok actually apparently there's a fix for this already, closing.

**Comment by mugg91** [comment]
This is not fixed in the current build 3900. Tested in Official Sandbox EU server.

**Comment by mugg91** [comment]
Gold spam was fixed a while ago.
