### ISSUE TITLE
Quarters + Vehicle + Tunnel bug

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#599]
This works both in online and offline sandbox. How to:

1) Build a quarters and a tunnel next to each other
2) Build a 2nd tunnel somewhere else
3) Take damage
4) bring a boat or catapult to the first tunnel & quarters
5) have action commands opened (hold down the key), press down to enter vehicle, then click on "sleep in quarters button". You should now sleep in the quarters while also riding in the vehicle.
6) While sleeping, open commands again and click on "travel in tunnel" button. This will cause the quarters building you slept in to be relocated to where the 2nd tunnel is. If there is wall around the 2nd tunnel, the quarters will be some place above the 2nd tunnel. 

As a side effect, you cannot build over where the quarters was previously.

Will play around with this bug some more and post a video soon.

If there are more than 2 tunnels, it will not work because you cannot press the arrow buttons while in a vehicle.

**Comment by bunniewormy** [comment]
i think this is a feature

**Comment by Panky123** [comment]
you can control a catapult while being in the bed of the quarters. How in the blue hell is that a feature?

**Comment by mugg91** [comment]
Video: https://www.youtube.com/watch?v=ziVp20CAOmU

The video also shows a bug you can do with archer, which is to press "down" near a vehicle and using hook right after. This will cause the hook to stay out and frozen while riding the vehicle.

The last part of the video shows a bug you can do with crate and quarters.

**Comment by mugg91** [comment]
I found that you don't need a vehicle to do the "sleep + travel" bug. Server ping allows that you can click both icons if you are quick. And if the quarters is teleported to a place that will cause the destruction of the quarters (spikes), it looks like you can cause a "through walls" bug.
https://www.youtube.com/watch?v=hhag0VCCVmQ

I also did this with someone else in sandbox. At some point, I couldn't click on the "sleep" icon anymore and the server died 5 seconds later and we couldn't rejoin. So perhaps the bug caused it to crash.

**Comment by mugg91** [comment]
Traveling with ship
https://www.youtube.com/watch?v=2Ck7_h8XSSg
