### ISSUE TITLE
Ballista/Catapult and tunnel interaction

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#600]
When you ride a ballista or catapult near a tunnel, and there are 2 tunnels only, you can travel through the tunnel with the catapult or ballista.

But when there are more than 2 tunnels, there will be a selection which tunnel to travel to and you cannot make the selection while riding a vehicle. This seems like an inconsistency.

Either make the selection possible while riding vehicles, or make the character unmount before traveling.

**Comment by mugg91** [comment]
You also cannot make the selection while carrying a dinghy (but you can when carrying a crate).

**Comment by mugg91** [comment]
Here is a bug you can do if you are mounted to the charger on the catapult or ballista and use the tunnel.

Because of the "free camera movement" when mounted to that spot of the vehicle, you can move the cursor out of bounds.

https://www.youtube.com/watch?v=hbGxtPw3zRo

**Comment by eps0003** [comment]
The bug above looks related to #164
