### ISSUE TITLE
Make doors server side instead of just client side

### ISSUE THREAD

**Issue by Vam-Jam** [transhumandesign/kag-base#611]
**Current in-game behaviour.**
Currently when you walk through a door, all of that is done client side, which is fine but it results in a lot problems, the main one being people walking through already closed doors, weird door de-syncs where on your screen, the door is closed but might not be open on theirs. 

**Proposed Change**

Let the server deal with all the collision stuff, so when it see's you walking into it, it sends you a cmd to let you walk through x door.
This also lets the server see when x door is in use, from a dead body or a player standing in it, or when its closed.

**The problems**
These are the problems i have noticed so far with the idea

First being that people with high ping might have issues with walking through doors, as they have to wait longer for the server to let them walk through it, which is not ideal at all.

A small fix to this could be to let users walk through a door but teleport them back if not allowed, but even then this can be abused if the user has high ping,which is not ideal (but no different to the current problem with client side doors)

**Old suggestion, read below link**
https://github.com/transhumandesign/kag-base/issues/611#issuecomment-501905545

**Comment by bunniewormy** [comment]
this is the shittiest idea i have ever heard honestly, possibly it even beats the quarry suggestion

**Comment by Vam-Jam** [comment]
care to explain why?
The idea is to prevent people complaining about people 'hacking' because they walked through x door, most people who are use to kag don't care, but its one of the more common thing's you see with new players/f2p

For matches where most people are < 100 ping, they should not even notice it, hence why the **problem** area exists, since it'll ruin it for other players if they have x or more ping

**Comment by Vam-Jam** [comment]
Re discord talk:

Server side checking before walking in is a bit too much, and is not ideal

Suggestion;
Have the client tell the server when they are done walking through x door (I don't think opening a door is needed?), that way the server can let all the other clients know that x door is closed.

This would not effect the game what so ever, its just making sure that no visual glitches happen with doors being left open out of thin air, and that people are not randomly walking through closed doors

**Comment by Harrison-Miller** [comment]
Closing because I think we've decided there isn't really a better way to handle doors with out severely impacting the player everytime they walk through it.
