### ISSUE TITLE
an option to use a different pick-up menu

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#613]
**Proposed Change**

it would be cool if you could press let's say Shift+C to open a different pick up menu. it would show all the currently items you can pick up in a circle. they should always be in the same spot for consistency. people could learn to ignore the problem of super shit pickup priority by using this new pick up menu

**Additional context**

this is how i imagine it

in this screenshot, someone clicked shift+c while being next to a keg, an enemy undeployed mine, stone and gold and a bomb arrow

![image](https://user-images.githubusercontent.com/39147836/59476478-2bcf1e80-8e51-11e9-96fb-04ebfa57725b.png)

the Xs are items that would show up if they layed on the ground. 

i believe all pick upable items should be included in this circle. fairly sure there would be less than emotes so people could learn and memorise their spots on the circle

**Comment by MatheusGodoi** [comment]
Maybe a easier button to press? The main problem with pickup is when you try to pick something in a hurry (like a mine, lit keg, lit bomb, etc) and end up grabbing 3 logs and your teammate body on the ground, but still a good suggestion, a "fix" for the pickup system that can be really frustating at times.

**Comment by blackjoker77777** [comment]
Related to #512?

**Comment by Harrison-Miller** [comment]
Let's get this implemented

**Comment by Harrison-Miller** [comment]
One thing that does seem to be a shortcoming of this idea is what two do when there is multiple of a blob to choose from. Does it just grab the nearest one (seems easiest)?

**Comment by Harrison-Miller** [comment]
@bunniewormy can you mock up all the items that should be on the wheel and a WIP order.
