### ISSUE TITLE
make change class area on ballistas work like on tents

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#614]
**Current in-game behaviour.**

currently changing class on ballies is shit because you need to move your cursor up and click the small button.

**Proposed Change**

you should just be able to open the change class menu by clicking E anywhere, like on tents

**Comment by eps0003** [comment]
Ballistae have multiple buttons which may be obstructed if class GUI automatically displays.

**Comment by bunniewormy** [comment]
you could just make it work like that if the ballista already has detached wheels or you aren't holding bolts in your hand

**Comment by Gingerbeard5773** [comment]
resolved issue?
