### ISSUE TITLE
You should be able to place ladders even if another player is standing in the spot you want to place the ladder in

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#617]
**Current in-game behaviour.**

you can't

**Proposed Change**

you should be able to. it's very annoying, especially when trying to climb up enemy tower with your team

@edit: i meant players from your team in title

**Comment by MatheusGodoi** [comment]
Not a bad idea, its a huge struggle when you want to ladder to enemy tower but your team is blocking the way. Also happens when you are trying to build a tower and your team is in the way so you cant :/

**Comment by eps0003** [comment]
What's the issue with allowing the player to place ladders on top of any player, regardless of their team?
