### ISSUE TITLE
Drills should not give 50% of the resources

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#618]
**Current in-game behaviour.**

title, it's unintuitive, and people think drills are used to dig faster + it's annoying when someone uses a drill on gold, which is a limited resoruce

**Proposed Change**

drills should give 100% of the resources, at least when used on ores [gold, stone]

**Comment by Zanzibur** [comment]
Agreed. Its so unintuitive, there's really no reason why you would ever expect there to be a difference unless you somehow noticed it randomly.

**Comment by MatheusGodoi** [comment]
I agree the idea on ores (100% for gold as its limited, maybe less for stone ores (but more than 50%) as there is already others means to get stone?) Not a fan of it giving mats on blocks and other things tho

**Comment by ferrezinhre** [comment]
side note: Drilling gold veins give 12 gold from 20 possible which is 60%, wonderful isn't it.

**Comment by Omen267901** [comment]
IIRC, the drill just got a small buff to how long it takes to overheat, so it may be best to approach things slowly here.

That being said, I also agree that it's awkward having the drill only give partial resources, ESPECIALLY for gold. Maybe for the time being only change gold to 100% and stone to 75%? Agree that it should give 0 for placed structures to encourage using pick a bit against them.

**Comment by benjamingorman** [comment]
It would be a large increase in the amount of stone you can mine. Especially on maps with water. Drilling 2 stone blocks atm is slightly faster than mining - so if we're talking about doubling the amount then it's quite a big buff.

I agree it should be buffed but perhaps not by so much. Maybe tone it up to 70% of resources and see how that feels.

**Comment by benjamingorman** [comment]
I'm still concerned that this buffs drills too much. Doubling the stone yield is a lot.
