### ISSUE TITLE
Drills should be able to drill doors and platforms the same as normal blocks

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#619]
**Current in-game behaviour.**

Currently, a drill overheats after destroying 4 wooden doors, sometimes even 0, same with stone doors and platforms.

**Proposed Change**

Drills should not be that weak against doors, and should be the same as against normal stone and wooden blocks. Same with platforms

**Comment by MatheusGodoi** [comment]
I like the idea of not dying after drilling 2 wood doors due to overheat, but maybe let stone doors as they are? Im not sure how strong they are against a drill but im not sure of making all doors weak as blocks. As for platforms I dont care much, they are already weak against a lot of stuff imo

**Comment by Panky123** [comment]
Drillspam is uber strong allowing it to chew thru doors on the same vein as blocks would allow players to destroy/break in easier than they should builder vs builder. With normal blocks you can repair with doors you have to wait for the block to break(which would make Drillspam legit hell to deal with)

**Comment by Omen267901** [comment]
Agree with Panky, this being implemented would be a terrible idea unless door repairs came with it too, and even then it should remain unchanged for stone doors. Agree that wooden doors breaking drills so fast is dumb though.
