### ISSUE TITLE
Make it possible to bind changing to specific blocks in settings

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#622]
**Proposed Change**

Each block you can place should be possible to bind in the settings, for example stone block to shift+1, wooden door to shift+2 etc.

**Comment by Harrison-Miller** [comment]
Excellent idea, the binding menu should work like the emote menu if possible. Although that might be difficult if we want to be able to rebind the keys. A stop gap solution might be to just use a config.
