### ISSUE TITLE
Fix text about resupplies and make it bigger

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#626]
**Current in-game behaviour.**

Sometimes after you get a resupply the countdown until next resupply doesnt appear on your screen.

**Proposed Change**

- Fix problem
- Have the message change into one that tells that you can resupply, instead of disappearing [in build time only I guess]
- Mention what a resupply actually is, maybe something like
'Next resupply (free materials available at tent or builder shop) in xx seconds[...]'

**Comment by MatheusGodoi** [comment]
Seems to be a small QoL, i dont see a reason to not make that

**Comment by eps0003** [comment]
Has this been fully resolved via the text that appears above your hearts?

**Comment by Gingerbeard5773** [comment]
resolved issue?

**Comment by AsuMagic** [comment]
Probably doesn't repro anymore
