### ISSUE TITLE
Platforms and ladders should give a small amount of wood when mined

### ISSUE THREAD

**Issue by benjamingorman** [transhumandesign/kag-base#630]
It's inconsistent/unintuitive that mining platforms or ladders doesn't return any wood. On the other hand mining wooden doors does give wood.

Platforms/ladders should be changed so as to give a small amount of wood when mined - perhaps roughly 50% of the cost of the block similar to doors.

**Comment by Vam-Jam** [comment]
Merged in a few updates ago
