### ISSUE TITLE
Admins shouldn't be displayed in spectator while in !m

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#634]
**Describe the feature**

Griefers can see if someone is in spectator and may change their behaviour to not look suspicious. Therefore, being invisible while in spectator would make it easier to catch and record griefers in the act. Other admins should be able to see fellow admins in spectator at all times. It could even say that the admin left the server when they !m to trick the griefer.

**Comment by blackjoker77777** [comment]
> Griefers can see if someone is in spectator and may change their behaviour to not look suspicious.

"Thieves outsmart cops", is not a new thing..

> Therefore, being invisible while in spectator would make it easier to catch and record griefers in the act. 

True, the very first time I got the spectator team thingy fixed, I had it working as you stated.
In fact it could simply be reimplemented but adding a single variable; [a preview..](https://gfycat.com/bossywelllitisopod)

The reason I decided against this [and still do] is that I wouldn't want to increase admin powers any further _[and some KAG players advised me not to have it that way]_, a good admin should in theory be able to handle any situation smartly with what's in hand.

They can hide their name color, why the need to be fully invisible? Even catching a badmin would be real pain in the arse that way..

Imagine this:

```
- X joins the server. [X being an admin but he has hidden name color so we don't know that].
- X does !m.
- "X left the server".
- X is still actually there..
- People get frozen and they start complaining.
- Ghost! oh noe..
[Basically the only solution is to contact the server owner (which regular players rarely do)
 to check for logs and figure out who the heck did what?!]
```
(I can see a couple of other abuse scenarios, but I'm too lazy to share honestly)
> Other admins should be able to see fellow admins in spectator at all times. 

This, I totally agree with; in case these modifications see the light.

>It could even say that the admin left the server when they !m to trick the griefer.

And trick other players as well? prohibit them from gathering any evidence against the admin either? provoke further chaos? have some non-responsible admins mess around more than what they used to do? haha please no.

I think this should be voted by the community tbh.
If it was accepted and decided to be added.. I will gladly work on having this modified as required. But as of now, I'm personally against this suggestion.

**Comment by eps0003** [comment]
#233 is probably the most ideal solution to the issue at hand
