### ISSUE TITLE
Vote-Icons and more Player-animations

### ISSUE THREAD

**Issue by butterdome** [transhumandesign/kag-base#639]
I always had soo much ideas for this game, especially for some Design-improvements and today i decided to write some of them down. 

 [KAGgamedesign1.pdf](https://github.com/transhumandesign/kag-base/files/3298033/KAGgamedesign1.pdf)

I hope you like them and they are realizable

**Comment by Harrison-Miller** [comment]
@butterdome can you split each of your ideas into separate tickets and explain them in the text of ticket please :)
