### ISSUE TITLE
If you throw a drill while drilling, it should continue drilling for about 2 seconds

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#642]
**Describe the feature**

Title. this can be used by builders to damage enemies on bigger distances. If this is not accepted I will do a Fuzzle. pls accept this.

**Comment by mugg91** [comment]
Drill is already ridiculous imo.

**Comment by MrPotatobird** [comment]
It is, but this really sounds fun as hell. I think it should just keep drilling till it overheats. I also think it should maybe get "stuck" in whatever wall it hits and keep moving forward if it breaks the blocks, so it could keep drilling by itself through a wall as well as a player. Drill could be adjusted in other ways if this makes it too good a purchase. It should probably overheat faster when thrown, I guess.

**Comment by Panky123** [comment]
Drills stuck in on/off position(turns off when overheats) would be hilarious af

**Comment by AsuMagic** [comment]
Seems fun, I'm a bit worried about it being OP though. Maybe it shouldn't go through shields and/or only deal a fraction of the damage? 2 seconds is a whole lot - long enough to throw from a tower to another.

**Comment by MrPotatobird** [comment]
I mean, they can just grab it. And then they have your drill. This is a meme strat.

**Comment by bunniewormy** [comment]
yeah because a strat that can be countered by clicking C is op as fuck!

**Comment by bunniewormy** [comment]
immature, unserious and not fit for official servers
