### ISSUE TITLE
Coins can overflow

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#643]
Coins overflow at 32767 so you come out with 0 coins.

I wanted to make a map full of kegs in sandbox, but was disappointed to find this problem.

**Comment by benjamingorman** [comment]
New steam achievement: reach 32767 coins in a CTF match

**Comment by Vam-Jam** [comment]
Increase coins from s16 to u32 (since we don't need to go negative coins). This will help mods such as TC where coin overflow are common, and prevent issues like this in other mods. I doubt this will effect/change much with normal vanilla game play.

**Comment by Orsovi** [comment]
Some mods could use negative coin, i think at shiprekt iirc.

**Comment by HKGx** [comment]
And achieving over 2 billions of coins is really hard, even in TC.

**Comment by AsuMagic** [comment]
Going `u32` would make sense but I'd be afraid random spots in the engine would just underflow because it assumes coins are a signed type. `s32` would give enough room anyway.

**Comment by Vam-Jam** [comment]
Temporary fix done engine side for the next kag update, there's a cap on how much coins you can get (32765), in the future i'll explore if we can increase it without breaking mods (i'll keep this issue open for now)

**Comment by eps0003** [comment]
Added in build 3090
