### ISSUE TITLE
damaging siege/siege health/coin gain changes

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#645]
**Current in-game behaviour.**

Currently, you get 2 coins for damaging any vehicle, and jabs do 0.25 hearts of dmg to vehicles. Ballista has 30 hearts, catapult has 24 hearts.

**Proposed Change**

- Ballistas stay at 30 hearts
- Catapults stay at 24 hearts
- Jabs should do 1 heart, slashes 2 hearts, bomb 3 hearts, normal arrow 1 heart, fire arrow 5 hearts, bomb arrow 24 hearts (as it is now I believe for bomb arrows)
- 5 coins for 1 heart -> no more than 150 coins from killing a ballista
- Killing a vehicle [final hit] should be additional 20 coins

**Comment by Panky123** [comment]
120 coins for hitting a catapult with a bomb arrow? Suck your mum

**Comment by bunniewormy** [comment]
noobs think that putting siege in the open is perfectly ok and should have 0 consequences
