### ISSUE TITLE
Boat/Catapult "through walls" bug

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#646]
Ride the boat and travel through a tunnel while your head is inside a wall, and you will gain "through walls" status.

https://youtu.be/DRqd8Iixbx4
This was played in offline sandbox.

It is easier to do than the other "through walls" bug...

**Comment by mugg91** [comment]
Finally I understand how this happened https://www.youtube.com/watch?v=WydmCxXzKJg

All of these through walls bugs have in common that you are inside a wall while traveling through a tunnel.

**Comment by Vam-Jam** [comment]
This issue was fixed a few updates ago with #724 , we did a work around to prevent this issue for now, an engine side update may happen in the future to prevent this all together.

Thanks for the report
