### ISSUE TITLE
Formal council

### ISSUE THREAD

**Issue by ferrezinhre** [transhumandesign/kag-base#653]
Architecture of council

High council: require 7 members ( separate channel for discussion )
Low council: multiples of 7 (aim is 42) main place of discussion
Links to issues and pr’s on github (so they know about what they work)
Applications
Whatever else they need

Roles of council

High councilors -  people whos main task is choosing course of development of kag, they should work together. And do whatever they believe is right for ours “dark” future.
Councilors - discuss problems, issues, prs etc. 
“overseers” aka geti, furai anyone else  to check if “idiot’s” know what they do.
visitors - role for people who don’t want do anything just read this “mess”
And this one will be controversial - Dictator role - if council will show no progress in their works on of high councilor will be picked up to “enforce” progress on his whim. (I know it can be dangerous but i hope it would enforce them to work together)

What is responsibility?
There will be no benefits form begin councilor, no colours no alocades, nothing. (I bet the half community who read this left already) But your gift will be a responsibility for shaping future of kag, now ask yourself question did you will endure this task?
I also would ask for time bans form council (3 months for councilors: inactivity, questionable behaviours etc, 6 months for Dictators if they fuck up)

Application: A logical reason why council would have any benefits from your person? rest depends on applicants whim

Probably everyone will disagreed with it or not read at all, and you still will be fighting with each other like wild beasts. Or you can make one step further…(I don’t believe you will)

**Comment by EHRaaaa** [comment]
Again, as I explained in discord, having split council parts would ultimately (although you say they don’t) have different levels of power. This would eventually build resentment, pointless discussions or nullify the use of a “lower council” if the “high council” are truly the ones making the decisions. 

So for my reworked idea;

Council consists of 15 or so members (this number is honestly up to others on how many we want to include). 
All council members will have equal voting power in discussions. 
Once a decision is voted on, a shared account (think of it as Council_github) would post the results of the discussion and the suggested decisions. 

Council would be chosen in two ways; a few members chosen by Geti/Furai/Mazey/Whoever else. Rest of the members are chosen by these members through submitted applications. 
OR all members are chosen through applications. 

Decisions are made through discord, using channels for discussion, GitHub posts via a bot, votes (either discord or via an external program). 

A possibility of a leader. This leader would have no more power in voting than any other members. The leader would exist purely for making sure members are actively contributing to discussions and are meeting any other requirements set by the council/application process. 


Why I believe this idea is better than the above; it eliminates differences in voting power, allowing everyone a fair voice (out of those chosen) and making sure everyone is able to contribute fairly to the voting process.

**Comment by Orsovi** [comment]
To decide between thoses proposition, i made a form, fell free to fill it it'll give a general mood of people willing to be involved.

https://forms.gle/QXndijqh6F6DsvjCA

**Comment by ferrezinhre** [comment]
Your "leader" idea is what high council should be and I tired explain it for you, but for me it's not one person but few. You ask why? Real life, health problems and other things, point of high council is ensure kag future not ruling, they should work together that what I see. And you created difference in voting not me, I never said they would have more power. And once more i will say this I want equality I just don't want council fall into stagnation after short period. Feel free to disagree

**Comment by EHRaaaa** [comment]
The leader idea isn’t a necessary part of the council, and in no way should or will they have more power over any other member in regards to making decisions (again like I said they are primarily for making sure people are active within the council and can make announcements etc.)

Sure the basis of your idea presumes there is no equality, but I explained to you in discord that having those separate roles (high vs lower council) with different responsibilities means two things;
• they are equal and as a result are worthless to be split (hence my idea of having just one council) 
• they have to have more power to be able to do things, hence my worries about inequality in voicing opinions or making decisions. 

Again, what’s the point of a lower council if they higher one is the one making/deciding on the issues

**Comment by ferrezinhre** [comment]
Alright in simplest possible way because you don't understand it. You make pr on github, it is disscused and voted but it's requre to be reviewed, that would be part of high council to ensure that this change have sense, would benefits  development of kag. You ask why? To don't end with grapple control idea. Still they will be equal in voting and everything else. Isuess on github still can make anyone,  it's up for council how they would work with issues, while you want enforce rules I would give them more freedom

"Sure the basis of your idea presumes there is no equality" this sentence is proof that you don't read what I write.

**Comment by EHRaaaa** [comment]
But why have a separate “high council” at that point, would it not be better to have the whole council decide on the viability of the issue instead of a select few (10-15 as the council idea I suggested would most likely have.)

Eh, meant to say “the basis of your idea presumes there is equality.” (Was too busy thinking of how to write that paragraph that I included a wrong word)


The use of the word “choose” in “choosing course of development of kag” implies that the high council is the ones making the decisions, where as the inclusion of “discuss etc...” implies that the lower council are there to only talk and don’t necessarily have an equal say in he voting process.

**Comment by Vam-Jam** [comment]
I think this is a bit overkill to be honest. I'm still mixed on having a council for KAG. The whole idea makes sense, but like EHRaaaa says, having 2 stages of it is not needed, and the 'higher council' just dominates the lower half, basically making them useless (plus 45 members is way too much for the lower half, you'll struggle to find that many people who actually care except from your captain friends).

Along with that, the council really is not needed, i feel like the content that gets added to KAG needs to go through a better quality check then 'it just works' with testing.
IMO features like the quarry should have been used on a few real matches, in captains or in a testing match to see how op it is, at least then it could have been prevented or heavily nerfed pre-release

The whole council idea is eh, It seems like people just wanting to get more power in the community, and having a bigger voice then other people who just play the game for fun.

**Comment by bunniewormy** [comment]
casuals not happy with actually good players trying to preserve balance :ok_hand:

**Comment by Vam-Jam** [comment]
But why can't casual players not have a voice in what they want to see happen to the game? Not everybody needs to and wants to play 'good' just to have a voice in what features should get added.

**Comment by bunniewormy** [comment]
because casuals don't know how to balance the game

**Comment by ferrezinhre** [comment]
@Vam-Jam If I may clarify few this in long text, well I hope it will be short.  this make me both sad and confused but also laugh for bit " your captain friends". Playing with some people don't make them my friends and you know assuming without thinking is a bit bad habbit.

Now this one "having 2 stages of it is not needed, and the 'higher council' just dominates the lower half, basically making them useless" - point is that council will have no settled rules so it will be up to community how this will work, only true differences between HC and LC will be in channel of pr and isuess, do add them to it you know to keep it clean, nothing big if like 10 people form LC want add some pr HC will be obligated to add it. And here come "overseers" aka furai and other staff to check if everything is fine. Ofcourse it's bit flawed but well.

Now this "the content that gets added to KAG needs to go through a better quality check then 'it just works' with testing." and here we have mostly common stuff that council would do, plus helping community manger and remaining staff.

I really sad to see it again "The whole council idea is eh, It seems like people just wanting to get more power in the community, and having a bigger voice then other people who just play the game for fun."
So let's say truth, I play kag for fun and in my eyes I see council as group of clever open-minded people who in jolly cooperation try change something and try reach brighter future. There is no power only a willingness to help.

So here is my offer  kag is like ship without captain on endless sea, so I ask you all of you did you want do anything or wait until it will sink. Just believe that despite all differences and disputes between all of you, you can work together.

btw: I hope bunnie will change his way of thinking for bit..
btw2: 42 members well it's open for everyone, trough applications (because community votes are em, technicaly well... friends choosing)
btw3: about causal players: applications
btw4: oh my hope we will talk some other time on less complex topic

I hope it's all, I truly tired of this, and @EHRaaaa  if you want still talk pm me on discord

**Comment by Vam-Jam** [comment]
Im not fully against it. My fear and a few others is having something like bunnie control it, who's known to be against people who don't play captains, or vanilla 8 hours a week. 

Currently i think it would make more sense for the council to focus on improving 'testing' part of kag, quarries could have been prevented with enough testing and time put into them, but testers are just inactive.

> btw2: 42 members well it's open for everyone, trough applications (because community votes are em, technicaly well... friends choosing)
btw3: about causal players: applications

Nice to know this, it was another problem i had since somebody on discord dislikes the idea of people who prefer mods over vanilla (but still plays vanilla from time to time) getting into the council, but knowing that, its not going to be that way.

Thanks for the clarification

**Comment by bunniewormy** [comment]
> dislikes the idea of people who prefer mods over vanilla (but still plays vanilla from time to time)
you mean 30 minutes per month?
