### ISSUE TITLE
[Bug] Cursor stays hidden after you disconnect from a server

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#654]
**Description**

If the cursor is hidden using `CHUD::HideCursor()`, it remains hidden in the main menu after you disconnect from a server

**Reproduction**

1. Hide the cursor using `CHUD::HideCursor()`
2. Disconnect from a server

**Expected Behavior**

The cursor is shown when the player leaves a server

**Comment by Vam-Jam** [comment]
Fixed a few builds ago by mm
