### ISSUE TITLE
AMD Relive

### ISSUE THREAD

**Issue by terracraft321** [transhumandesign/kag-base#66]
AMD Relive doesn't work with KAG, i suppose. Only if i record in Windowed mode or something similar. I think that Relive doesn't detect it. I'd would rather have to use a another recording software unless there would be any fix for this.. Okey after doing some research. I found out that it doesnt work with OpenGL games at the moment. So i suppose i will have to run the game borderlessly and then record. To my suprise. Oh, well. That neither seems to work, neither of them. I guess i will have to use Bandicam then.

**Comment by 1bardesign** [comment]
I feel like this is definitely Relive's fault and not ours (for once!), but good to know about the compatibility issue.

**Comment by furai** [comment]
If anything use OBS, way better and no watermarks.

**Comment by terracraft321** [comment]
I agree that it's not kags fault. Also Yes, i do know about OBS. But datacaps are datacaps.
