### ISSUE TITLE
Remove TTH official servers and move TTH to the Mods folder

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#661]
TTH has plenty of issues and shouldnt be considered an official gamemode. It works entirely different than CTF or TDM. There are no coins, bad resupply system, weird system with buying stuff with gold and making factories, day and night, unbalanced scrolls and the fact that noone plays it

**Comment by Panky123** [comment]
Low iq to remove something rather than fix it. Wven if its poorly designed its an entire gamemode/content for players.

**Comment by Shadowblitz16** [comment]
I disagree I think kag needs more official gamemodes.
I think someone should fix the tth bugs if anything

**Comment by Vam-Jam** [comment]
> I think someone should fix the tth bugs if anything

RIP who ever does that

**Comment by Shadowblitz16** [comment]
why?

**Comment by Vam-Jam** [comment]
TTH code can be weird in places, i tried to fix the #462 issue, but the code for shops are confusing compared to ctf

**Comment by Shadowblitz16** [comment]
why don't someone just make a easy to use universal shop system?
I never understood why kag's scripts weren't made to think about easability and expandability

**Comment by bunniewormy** [comment]
Closed, I guess according to current 'community' something that is played once a month, is horribly bugged and a bad experience for majority that plays it should stay as an official gamemode
