### ISSUE TITLE
[Balance] Building blocks should slow you down as much as breaking them.

### ISSUE THREAD

**Issue by FusIntel** [transhumandesign/kag-base#667]
As you may already know, building doesn't cost you any momentum, which makes solo scaling 
of the walls (aka block spamming) a cake-walk. All the while breaking the blocks placed is painfully slow, especially with the lag, current targeting system, and tortoise weight + speed.

Theoretically speaking, an allied builder can easily catch an enemy builder who only holds RMB, which makes block spamming the only plausible scenario due to the convenience of speed, and obstacles you make for the pursuers, who, in turn, cant deal with you as easily due to issues stated above.
I believe what most problems people have with this, come exactly from that speed vs power imbalance.

As stated in the headline, I propose to equalize your speed while building to the one of breaking/mining. Not the other way around, however, because building, i believe, is the only action with the mouse what doesn't slow you down, making it the odd one out.

**Comment by bunniewormy** [comment]
Offensive builder gamestyle - which is already underused due to how easy defensive gameplay is - should not be nerfed. This would make it even harder for any actual offensive gameplay. Offensive playstyle - especially builder one - should be buffed and encouraged...

**Comment by FusIntel** [comment]
"Actual offensive gameplay" would be left unchanged by this.

Scenario there a builder runs away throwing blocks in the way of another builder, who in turn cant hit him due to his speed is, to be completely honest, just an annoyance in the grand scheme of things, unbalanced, yes, but just an annoyance.

You may be surprised, but winning has always been a team effort. Builders encase themselves next to the wall (still more than possible, as it should) and dig through it, then knights move in under archers cover-fire with the keg and blow the hall through the flag room, boom, you win. The only way of winning solo was always been ratting, and only if you are lucky enough.

The aforementioned issue i stated should be looked at separately, placed against it's possible counters and balanced accordingly, due to it being a 1v1 encounter by nature alone.

**Comment by MrPotatobird** [comment]
You're throwing the baby out with the bathwater with this change. Imagine how painful building in general would be if you could only place one block every 5 seconds. Just not very fun at all, especially now that we're all used to the current building speed.

Building so fast has its problems, sure. Being able to easily shit out blocks all over the enemy base is definitely not great. Takes you like 5 seconds and takes them minutes to clear it out. This just isn't a good  enough way to make it better IMO.

**Comment by ferrezinhre** [comment]
So I tested it and well, how to say, it is bad. Firstly scaling walls is still possible and is still easy due "wall running", everything stay same here. Secondly, spamming block will be still possible by ferociously mashing mouse button, slowdown would be applied only if you hold mouse button. Thirdly, building bases will be slow and cumbersome.
Here is code:
// slow down walking
	if(this.isKeyPressed(key_action2))
	{
		RunnerMoveVars@ moveVars;
		if(this.get("moveVars", @moveVars))
		{
			moveVars.walkFactor = 0.5f;
			moveVars.jumpFactor = 0.5f;
		}
		this.Tag("prevent crouch");
	}
	
	if(this.isKeyPressed(key_action1)) // slow down building
	{
		RunnerMoveVars@ moveVars;
		if(this.get("moveVars", @moveVars))
		{
			moveVars.walkFactor = 0.5f;
			moveVars.jumpFactor = 0.5f;
		}
		this.Tag("prevent crouch");
	}
Feel free to disagreed, oh and testing is important!

**Comment by Zanzibur** [comment]
Probably the most problematic aspect of this suggest is brought up by ferre's third point: this would have a massive impact on base building. It honestly seems like it would completely change the whole pacing of the game.

**Comment by FusIntel** [comment]
Well, what's a lot to unpack here.
Firstly, thanks for the code, ferrezinhre, greatly appreciate it. Just did a test with it, and i agree, building without the jump height is extremely clumsy, what's why originally i didn't emphasize on it, but on the walk speed, so i removed the moveVars.jumpFactor out of the code and tested again, the results are on [tape](https://youtu.be/tujNSGxL7KQ).
As you(lot) can see in the video, the difference may be small, but at least now you have an actual chance of catching up to the builder and doing something about him. Building seemed perfectly fine (at least to me), considering what usually you don't really need to run around left and right placing ground floors.

Secondly, maybe my wording wasn't exactly clear, i'm not saying what a block spam is a taboo and should be banable or something, any tactics are welcome, even ratting. My firm belief is just what for the game to be truly skill-based, one must put players on an equal playing field. It isn't exactly fair then one team gets it's football net facing backwards by default, and the opposing team don't, yet have to score in there somehow, such thing would only cause confusion and frustration if it there to happen, just as it currently does, in fact, due to the issue being completely artificial.

Lastly, i do believe what no solution is perfect, however, if no solution is being proposed or present to be considered good, one must propose at least something.

**Comment by ferrezinhre** [comment]
If I may ask for short, straight to the point messages without senseless babbling and academic writing style, I would appreciate that.

Firstly, this change still it will cut both ways, it will affect both of offensive and defensive aspects of builder, it's require testing on populated CTF to see results. @Vam-Jam I hope you can do it. Another thing it will affect moving with drill, speed will be reduced because to use drill you need press and hold lmb.

Secondly your second paragraph is just waffling about nothing.

**Comment by eps0003** [comment]
Closed due to overwhelming negative response.
