### ISSUE TITLE
auto translator for kag chat

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#671]
please add a auto translator for kag chat.

the way it would work would be translating the user's messages to other users in their language and translating their language to the user's language automatically.

I am sure a library could help with this since it would probably have to be done engine side

**Comment by Blubahub** [comment]
Yes. Make it optional, though - too many errors that can happen with slang, names, and such. The auto-translator, even while on, should NOT translate usernames or nicknames (otherwise the user would not know the other user's real name, and most importantly wouldn't be able to PM the other in chat).

**Comment by Harrison-Miller** [comment]
This will not be implemented.
