### ISSUE TITLE
Menu bug on build 3007

### ISSUE THREAD

**Issue by TypicallyNamed** [transhumandesign/kag-base#672]
When i was about to return to KAG after a long time i was dissapointed at finding that when i opened the game on full screen nothing will appear on the menu,i tried windowing it but nothing still won't appear. https://steamcommunity.com/sharedfiles/filedetails/?id=1813295919 (screenshot)

**Comment by Vam-Jam** [comment]
Can you try deleting autoconfig.cfg and running forceupdate.bat. This has never happened before as far as im aware.

**Comment by furai** [comment]
Do you run any overlays? Discord? TeamSpeak?

**Comment by TypicallyNamed** [comment]
No

Em qua, 24 de jul de 2019 às 05:41, Lucas Grzegorczyk <
notifications@github.com> escreveu:

**Comment by TypicallyNamed** [comment]
It worked,thank you.

Em ter, 23 de jul de 2019 às 17:55, Vam-Jam <notifications@github.com>
escreveu:
