### ISSUE TITLE
Sending /nextmap through rcon crashes the server

### ISSUE THREAD

**Issue by Qadric** [transhumandesign/kag-base#676]
Sending the /nextmap command through rcon causes the server to enter in a /nextmap loop and crash.

*Windows KAG server, not sure if it happens on Linux*

**Comment by Vam-Jam** [comment]
Is this ingame or using tcpr?

**Comment by Qadric** [comment]
tcpr

**Comment by Vam-Jam** [comment]
Fixed engine side for KAG next update
