### ISSUE TITLE
[Feature Pitch] [Ambitious] Long-term Goals

### ISSUE THREAD

**Issue by Radinyn** [transhumandesign/kag-base#678]
_Please read the whole discussion_

_As we all know KAG is not in the best situation, I think the lack of long-term goals is an important factor. Here's a pretty ambitious reform that adds such goals to KAG. Thanks to Cuttek for helping me write this._

**EXP:**
EXP is a new currency, it can be gained by building and fighting, just like coins, however it is stored outside of a match. It can be used in the things listed below.

**Perks:**  (most drastic, look down for different version)
**Discuss please! We need something fresh without changing the core!**
They are bought with a certain amount of EXP, only one perk for each classed can be used, you can change them when you are dead. I tried to make them valuable without changing core mechanics of the game. _Those are just my ideas for them and can be changed._

_Knight:_
> Bouncy Shield
When you point down with your shield and fall from a certain height you bounce further at like 75% of your falls power
> Reflective Shield
Works like normal shield however arrows are reflected back
> Meteor Shield
When you fall from a certain height while pointing your shield down you break some block and create a small explosion
> Mobile Shield
Allows you to do a second half-jump mid air while holding your shield up
> Gliding Shield
Allows you to glide faster and longer

_Archer:_ (changing bow's long click ability)
> Old ability
Old archer ability of shooting 3 arrows in a row
> Line arrow
You shoot an arrow with a line behind it, it connects to blocks it hits and you can hold it with graphling hook
> Strong arrow
Arrow that can break wooden blocks just like knights attack (slowly) and deal 0,5 more damage
> Piercing arrow
If this arrow is not blocked by a shield it can hit multiple enemies
> Knockback arrow
Arrow with a strong knockback

_Builder:_
> Reinforced Wood
Wood built with this perk takes 1 more hit to break
> Dirt-drill
Drill doesnt overheat so fast when digging dirt
> Better vision
You have better vision in the dark, perhaps even a lot better
> Discount
You can buy items for a smaller amount of coins/resources
> Recycling
You recover more resources from breaking placed blocks

_More perks could be implemented in the future._

**Or instead**
**New weapons**
Perhaps new weapons? Much less radical
like axe for the knight - deals more damage but is slower etc
crossbows for archers? All buyable with EXP
Maces, Spears, Throwable spears, skins for them to fuel the market

**EXP Reward Boxes:** (not buyable with real cash!)
When you gain some amount of EXP (it shouldn't change), you get a box you can open and get one cosmetic upgrade from it (weapon color, a single head (note: they can be created by the community)) you can either use it or you can trade it, and here are two options:
1) Perfect option: Full connection to the steam marketplace
2) Worse-but-good-enough option: In-game trading system

Edit: Also keg skins, bomb skins, bomb colors, lantern colors

**Daily login rewards:**
Pretty simple, some EXP maybe some cosmetics if you want.

**Comment by Vam-Jam** [comment]
EXP sounds fine, perks however feel a bit op. It'll allow pro players to stomp more easily. The idea sounds nice for a mod, but for vanilla its questionable. 

The idea of exp sounds fine, and might work out depending on how its done, how its rewarded and so on.

**Comment by Radinyn** [comment]
> EXP sounds fine, perks however feel a bit op. It'll allow pro players to stomp more easily. The idea sounds nice for a mod, but for vanilla its questionable.
> 
> The idea of exp sounds fine, and might work out depending on how its done, how its rewarded and so on.

The main point of perks is to bring freshness to the game, as it's lacking that right now.

**Comment by Snikerss** [comment]
I think perks will break all balance in game if it will be done like u described, so need make it public. I trying to say thats KAG is game based on your skill, if perks if although they will be added they mustn't be like in MMORPG games, because of this, players who playing more will have huge advantage. So best way on my mind is:
1. make no passive skils
2. active skills must be also based on skill (something like in super smash knights mode but lesser FX and simple
3. No big RPG tree, enough will be 2-3 cells for skills and little skill tree to choose.

**Comment by Radinyn** [comment]
We need something fresh yet somethign that doesn't change the core mechanics.

**Comment by Turtlebutt** [comment]
>That doesn't change the core mechanics
Literally almost everything you suggested does that lol.

**Comment by Radinyn** [comment]
> > That doesn't change the core mechanics
> > Literally almost everything you suggested does that lol.

Core combat stays the same mostly stats change with the new weapons version, about perks more changes but base still is pretty normal.

Stagnation is much worse.

**Comment by Turtlebutt** [comment]
By combat do you mean being able to slash/ stab/ shield/ shoot arrow ? Because that's core to the simplest bit. By having this shit you throw all skill out of the game.

**Comment by Radinyn** [comment]
> By combat do you mean being able to slash/ stab/ shield/ shoot arrow ? Because that's core to the simplest bit. By having this shit you throw all skill out of the game.

You are the user of these things therefore skill is still present. We are not changing people into bots or anything, nothing is automatical its just different, don't fear changes. Also weapons options is much less radical.

**Comment by Turtlebutt** [comment]
If you change how those mechanics work, you change how the game works, that would be like removing special arrows from archer and bombs from knight, it would change how the game is played drastically.
This would pretty much be a complete combat overhaul.

**Comment by Radinyn** [comment]
> If you change how those mechanics work, you change how the game works, that would be like removing special arrows from archer and bombs from knight, it would change how the game is played drastically.
> This would pretty much be a complete combat overhaul.

The point is, don't we actually need some drastic changes?

**Comment by Turtlebutt** [comment]
Not like these.

**Comment by Radinyn** [comment]
> Not like these.

In my opinion weapon option could bring a lot of freshness without changing too much, it could add more tactics etc.

Perks option is much more radical and much less polished.

**Comment by Turtlebutt** [comment]
yeah but that's changing game core mechanics

**Comment by Radinyn** [comment]
> yeah but that's changing game core mechanics

An axe with mechanics like a sword with increased damage but lower speed doesnt change the core, it's more like changing statisitcs 
+ You can add Maces, Crossbows, Spears, whatever and also skins for them to fuel the market

**Comment by Vam-Jam** [comment]
Personally i dont think this is the way to go

Sure new weapons (which are basically new classes) are good on paper, but it wont change stuff that much

I'd rather look into mechanics that are not used much, like food for example

Food has little uses in game, costs a fair bit, takes up some space in your invo, hardly worth it, since most your enemies will drop hearts, which heal little but are super valuable. 
Why not make food easier to obtain, maybe letting builds grow it or something (inb4 more minecraft builders). 

This isnt a good suggestion, but it's an example of what changes are more likely to get accepted then just ``add new weapons, add new item`` and so on

**Comment by Radinyn** [comment]
> Personally i dont think this is the way to go
> 
> Sure new weapons (which are basically new classes) are good on paper, but it wont change stuff that much
> 
> I'd rather look into mechanics that are not used much, like food for example
> 
> Food has little uses in game, costs a fair bit, takes up some space in your invo, hardly worth it, since most your enemies will drop hearts, which heal little but are super valuable.
> Why not make food easier to obtain, maybe letting builds grow it or something (inb4 more minecraft builders).
> 
> This isnt a good suggestion, but it's an example of what changes are more likely to get accepted then just `add new weapons, add new item` and so on

The question is:
Is this change good enough to attract new/returning players?
I think we all agree on the marketplace thing, but I don't think thats enough.

**Comment by Turtlebutt** [comment]
i dont agree on anything

**Comment by Radinyn** [comment]
> i dont agree on anything

Why? What's bad with the marketplace?

**Comment by Vam-Jam** [comment]
There's other ways to attract new/returning players then just to have a lot of changes at once.

Stuff like;
Constant communication from the devs
Updates every few weeks, even if its small bug fixes
Having the community have a say on what they want to see (with it actually done)
Show off what the community has done, from cool mods to guides and more
Annouce community events, get the players who play the game involved more

Currently kag has little of that, communication is low, updates can be rare, community does have a say but stuff rarely gets done, a lot of community content goes unnoticed, and events are uncommon however the last head contest was nice and i'd think it would be good to see more in the future.

**Comment by Radinyn** [comment]
> There's other ways to attract new/returning players then just to have a lot of changes at once.
> 
> Stuff like;
> Constant communication from the devs
> Updates every few weeks, even if its small bug fixes
> Having the community have a say on what they want to see (with it actually done)
> Show off what the community has done, from cool mods to guides and more
> Annouce community events, get the players who play the game involved more
> 
> Currently kag has little of that, communication is low, updates can be rare, community does have a say but stuff rarely gets done, a lot of community content goes unnoticed, and events are uncommon however the last head contest was nice and i'd think it would be good to see more in the future.

Because there's no money, and there's no money because there's no players

**Comment by Vam-Jam** [comment]
> Because there's no money, and there's no money because there's no players

Excluding updates every few weeks, the stuff above doesn't require much work/effort. Having a content update/rework as you suggested requires a **lot** time to update the engine for EXP support, bug fixes, api changes so you can actually store that stuff, the whole perk system would require somebody to figure out a good was to intergrate it into the game, and a lot of balance changes (and bug fixes)

If you want players to return, start small, make the community stronger, show off what people contribute to the game, communicate with them, have people contribute to help the game grow.

**Comment by Radinyn** [comment]
> > Because there's no money, and there's no money because there's no players
> 
> Excluding updates every few weeks, the stuff above doesn't require much work/effort. Having a content update/rework as you suggested requires a lot time to update the engine for EXP support, bug fixes, api changes so you can actually store that stuff, the whole perk system would require somebody to figure out a good was to integrate it into the game, and a lot of balance changes (and bug fixes)
> If you want players to return, start small, make the community stronger, show off what people contribute to the game, communicate with them, have people contribute to help the game grow.

The point is, those changes should mostly be made by the community using the bounty system. I'm not sure about the budget tho because patreon has much less money than the minimal amount listed.

**Comment by bunniewormy** [comment]
i cant believe FOUR people think this is actually a good idea, i feel like quitting this game

**Comment by blackiceball** [comment]
???? wdym the games low player retention and its dying anyways why keep it like that?

**Comment by Radinyn** [comment]
Stagnation is really terrible for the game.

**Comment by marcelodesousa** [comment]
> 
> 
> There's other ways to attract new/returning players then just to have a lot of changes at once.
> 
> Stuff like;
> Constant communication from the devs
> Updates every few weeks, even if its small bug fixes
> Having the community have a say on what they want to see (with it actually done)
> Show off what the community has done, from cool mods to guides and more
> Annouce community events, get the players who play the game involved more
> 
> Currently kag has little of that, communication is low, updates can be rare, community does have a say but stuff rarely gets done, a lot of community content goes unnoticed, and events are uncommon however the last head contest was nice and i'd think it would be good to see more in the future.

Tbh I think this is the way to go. I think it brings the community together and creates room for some cool, fun stuff to happen. It's generally what keeps players to come back and play the game.

I think creating comprehensible guides, tips and whatever for modding would be cool. Having this resources open and accessible might lead to some great creative stuff... new people experimenting and tweaking stuff. Vanilla KAG is awesome, and there's so much room and so many amazing things that players have been doing over the years.

These community contests, like the heads one, also enhance participation. It's was not about having the best heads, but about doing/making cool stuff.

**Comment by Radinyn** [comment]
> > There's other ways to attract new/returning players then just to have a lot of changes at once.
> > Stuff like;
> > Constant communication from the devs
> > Updates every few weeks, even if its small bug fixes
> > Having the community have a say on what they want to see (with it actually done)
> > Show off what the community has done, from cool mods to guides and more
> > Annouce community events, get the players who play the game involved more
> > Currently kag has little of that, communication is low, updates can be rare, community does have a say but stuff rarely gets done, a lot of community content goes unnoticed, and events are uncommon however the last head contest was nice and i'd think it would be good to see more in the future.
> 
> Tbh I think this is the way to go. I think it brings the community together and creates room for some cool, fun stuff to happen. It's generally what keeps players to come back and play the game.
> 
> I think creating comprehensible guides, tips and whatever for modding would be cool. Having this resources open and accessible might lead to some great creative stuff... new people experimenting and tweaking stuff. Vanilla KAG is awesome, and there's so much room and so many amazing things that players have been doing over the years.
> 
> These community contests, like the heads one, also enhance participation. It's was not about having the best heads, but about doing/making cool stuff.

That's a good way to keep the game alive, but we need something to reanimate the community.

**Comment by marcelodesousa** [comment]
> That's a good way to keep the game alive, but we need something to reanimate the community.

Imo the first thing i'd do would be redoing the UI and Main Menu. Especially the main menu... it's too cluttered, and some options are unnecessary. But mostly a visual upgrade.

**Comment by Radinyn** [comment]
> > That's a good way to keep the game alive, but we need something to reanimate the community.
> 
> Imo the first thing i'd do would be redoing the UI and Main Menu. Especially the main menu... it's too cluttered, and some options are unnecessary. But mostly a visual upgrade.
> 
> This is not really something aimed at the mechanics and stuff, and what you proposed, but I think it's in dire need of a facial lift.

That's a good idea, it could make it easier for new people to join, but still its not enough.

**Comment by Snikerss** [comment]
@Radinyn yes its better i think it may be maked balanced

**Comment by Panky123** [comment]
Cba to read all the back and forth but XP is a great way to describe what people want out of stats. It gives people a reason to login and play and there could be a leaderboard and perks(I personally dont like gamechanging perks but cosmetics sound hype)

**Comment by Olimarrex** [comment]
Personally, I think the best thing that could be implemented right now would be ranked matches. Skilled players are constantly scaring off potential newbies by absolutely destroying them. With ranked, skilled players will get actual challenges rather than constant pub-stomping / captains, and new players aren't put off the game by their helplessness.

Perks and things represent something that might keep new players engaged for longer, giving them something to work towards before they dismiss the game. You have to be very careful in terms of balance, though. Perks should be more focused on providing small changes that allow users to tweak their playstyle to suit their personal style. Or perhaps just extra visual changes?

**Comment by Radinyn** [comment]
We just need changes, big ones, freshness brings new and returning players and long term goals make them stay

**Comment by butterdome** [comment]
> > That's a good way to keep the game alive, but we need something to reanimate the community.
> 
> Imo the first thing i'd do would be redoing the UI and Main Menu. Especially the main menu... it's too cluttered, and some options are unnecessary. But mostly a visual upgrade.
> 
> This is not really something aimed at the mechanics and stuff, and what you proposed, but I think it's in dire need of a facial lift.

Yes i often think about rediesigning Kag, especially the UI.. it really makes a huuge difference to new players. A well structured, appealing design that makes players feel good when starting Kag.

In my opinion new features would be great but redesigning and explaining old features is much more important to make the game more beginners friendly. 

my ideas:

**Design:**

- redesign the UI, with more icons(weapons, tools, ...) and medieval themed pixelart, but still keep the not overfilled, clean look

- consider new colours, like other greytones for the UI and maybe warmer colours in general 

- remake backgrounds... i mean i kinda like the cold scottish feeling but still, they could be way cooler and more complex(but still discreet) and better placed (often you just see the sky instead of the landscape), could be connected to the paralax effect that should also work vertically

- better (pixelart) font

- i think we could learn a lot from games like Kingdom New Lands: https://www.supersoluce.com/sites/default/files/node/176616/kingdom-new-lands-tuto-creer-blason-001.jpg

**Old Features:**

- Let not only shoot archers burgers but also knights, and not only burgers but also hearts (or even all items (with different weight))

- add stars above head even when you are just stunned shortly (when stunned with shield for example)

- Make animations for moves combined with crouching, it shouldn't be a secret technique that only pro players know!!! in the end pro expect it anyways and noobs just think its a bug. 

- make picking up coins feel better and more reliable

- add a healing animation (sth like green sparkles)

- drowning should do quarter dmg just like burning. quarter hp should be more important, since you can heal quarter dmg in bed. (maybe add other sources that do quarter dmg (or just remove it completely))

- remove team-boulders  :c
