### ISSUE TITLE
[Change request] Make wooden doors weaker against enemy knight attacks

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#683]
Atm it takes 14 slashes and around 56 jabs to destroy a single wooden door as a knight.
Builders with drills can cause havoc in enemy towers by spamming wooden doors and drilling anyone that come near them.

To give knights a bit more power to take down builders that spam wooden doors i suggest to nerf wooden doors to around 5-7 slashes and 15 to 21 jabs. 

Just remember that knights cant slash/jab stone doors/blocks.
And maybe it requires a bit more thinking on where to place doors and where to place stone blocks, and that would be a good thing.

**Comment by bunniewormy** [comment]
Bump, please do this

**Comment by AsuMagic** [comment]
An extra problem is that partly due to this, it's hard to know how many more hits a door will take. It's annoying when you need to plan an attack or a way to escape as you have to break some wooden doors and cannot tell exactly which hit will break the door.

**Comment by Coroz** [comment]
I am closing this because wooden doors have been nerfed enough vs bombs
I don't see a reason to nerf them even more.
