### ISSUE TITLE
[Change request] Remove the max on resupply 

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#684]
Atm there is a max on resupplies you can get with wood and stone.

Remove the max and make it so you can resupply all wood and stone without having the need of dropping mats on the ground.
(its like a 2 line code and maybe some edit for archer)

They should have been the case when the game just came out. Its very annoying to drop mats all over the place all the time just to get a full resupply.

**Comment by eps0003** [comment]
If it’s only two lines of code and it still hasn’t been changed, then you should think about reasons why. The only flaw with this is that AFK players can rack up crazy amounts of mats while standing at the tent. We can’t expect admins to always quickly kick AFK players, therefore this flaw is valid.

**Comment by CatWiz** [comment]
We have resupplies working like that on captains already and i believe bunnie updated it so that afk players dont receive resupplies (there's a PR for this change, but it isnt updated)

**Comment by Panky123** [comment]
Eps your logic is negative iq. Afk players suck we all agree but them getting ressuples while theyre afk would be a good thing. Atleast in some way the team is being compensated for the afkness. If push comes to shove and someone afks for a long time as builder and gets aton of res the team That's been disadvantaged atleast has something

**Comment by bunniewormy** [comment]
why did you make this issue? theres literally a PR being in the works that is editing this

**Comment by Coroz** [comment]
I actually forgot about it being a PR because it was 'ages' ago

**Comment by Vam-Jam** [comment]
Coming for next update #583
