### ISSUE TITLE
[Change request] Archer autopick on arrows

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#685]
Currently you autopick arrows until you have 60 arrows.

When you swap as a archer for some mats for your builders and swap back it happens that other archers take your 30 arrows and run of with them.

Reduce this to 30 arrows. easy fix

**Comment by Panky123** [comment]
Autopicking up arrows on the battlefield is more important(imo) to class swapping at spawn for res being awkward.

**Comment by Coroz** [comment]
Read it again punk, you still autopick arrows but with this change its limited to 30 arrows

**Comment by Panky123** [comment]
I can read thanks. Autopickup to 60 is better.

**Comment by Trumbles** [comment]
Not sure I understand the need to automate playing Archer.

**Comment by Harrison-Miller** [comment]
I don't think this is a beneficial change. Looking at the problem it seems more like a concern with how resource drops are handled. And trying to get the free mats. I'd prefer if archers could easily get 60 arrows still.
