### ISSUE TITLE
Official way to "register" a clan and its members.

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#699]
Since the rules have been changed, which allows for clan impersonation once again, I suggest to add a way to officially register a clan and its members and make it impossible to use a clantag if you're not in the clan. People with fake clantags can give bad reputation to clans - and it's assholery/trolling in general, so I don't see why it should be allowed

You could make such a system so you can do it in-game, but that probably would be hard to do, or you could do it similarly to the mod manager: https://forum.thd.vg/resources/kag-mod-manager.153/ (so just add stuff like official clans to the API)

This could be also used in the upcoming global stats system - you could make leaderboards for clans. It could also potentially somewhat revive the clan scene.

**Comment by furai** [comment]
I agree that we lack proper tools for enforcing anything related to clan tags. [Hence the rule was removed.](https://github.com/transhumandesign/kag-official-server-rules/commit/55d9279f09cc26c3609e9c3f79abf5475a63e22e) I was never fond of it. It shouldn't be part of OKSA duties to patrol clan scene.

We need proper system that would take care of it.

I don't see how it could revive clan scene but in general I'm sure it would only benefit the community. 

Best would be API side but we know the state of the current KAG dev. We can't even get simple changes out - not mentioning that currently a build just hangs there not being pushed to release (though we should get it out this week).

As to the idea itself - I'm sure we've discussed it many times @bunniewormy. The idea would be to first off give admins ability to remove clan tags from users. 
Other part would be some website where you register as clan owner and you add members to it.
Then that would be pulled in-game and showed next to your name.
Probably best would be to skip the website part and just do all of it straight in-game.

That being said - it's non-trivial thing to do.
