### ISSUE TITLE
Resource value and drill nerf by RA

### ISSUE THREAD

**Issue by DaS-21** [transhumandesign/kag-base#706]
Hello, RA here.

So Vamist wanted me to suggest my own changes I would like to see. I know I am wasting time on this but whatever, here they are (for those who don't like long poems, imma do TLDR version at the bottom)...

This is what current drills are: 
- https://cdn.discordapp.com/attachments/149347330313682944/629720196894162957/balanced_drill.mp4
To add more to this: you can destroy 6-8 wooden door, lots of platforms but that depends what and/or how you hit em and on couple more things. _Not gonna bother explaining glitches and how to abuse them in here_

And this is what Vamist want to do "to balance and nerf them _(#704)_ ":
- No decay when dropped in water;
- More damage to door;
- Faster cooling when walking which means almost everytime;
- Setting things on fire;

Everyone knows me and hate me for being the worst rat. Whoever reads this should know how good I am at it. Maybe not the best but you know what I mean. I just know how ratting works, been doing it for long enough to know how things should be and how they should not.

### Mats value
Let me start from this one first. 
Back in the day, materials used to have a big value. Very often you could see a builder dying and losing a stack of stone. The other teammates tried to do everything to bring it back to the base knowing how important it was.
This thing is no more since the moment we got quarries. 

From what I've heard it was Mazey's feature, nobody really asked for but whatever. This thing has changed the gameplay completely. With unlimited wood (once you have a tree farm, build every game nowadays) you can feed the quarry and get pretty much endless supply of stone. 
I did not say unlimited because quarries itself do not really make it unlimited. The thing that does it are drills now.

### OP drills
They are complete bullshit. Whoever decided to remove 50% waste probably does not really play the game and simply - should not be allowed to develop it in any way imo.

You spawn with 30 stone and very often there is some stone already dropped on the ground from people switching classes so getting 100 for a new drill is very easy and takes less than 15-20 seconds. This basically means that you can hop on drill fights every time you spawn. It is even more easier when you set up a quarry. 75 stone from it + 30 from resupplies = free drill. I've been playing yesterday and could get it literally every time I spawned. 

Is not it broken? If you don't believe - go on the server and tell me how long it took you to get a drill.

So now the question is:
### How we can really balance it?
This is actually what Vamist wanted me to tell him so - the easiest thing would be - let me think :thinking::thinking::thinking::thinking: restore KAG to the old version before quarries?

Yeah.. Would be great, wouldn't it? But seriously, there was nothing wrong with the old ones and the current drill and some of the other features should be very close to the ones we used to have.

Before I start talking about drills, let me go back to resources and their value.

**Wood** was always like this, at least from what I remember and well - everywhere, too much but easy comes, easy goes. 
**Quarries** tho should be nerfed but just a little bit so they are still worth constructing. The best way to do it in my opinion is by increasing wood needed for production of stone. This would make it so getting drill takes little bit longer or require you to mine stone as well as remove excess amount of wood. 2 in 1.

**Drills** - something completely flipped up. They are not a weapon but a tool HOWEVER - builders should use it as a weapon to kill, but only the enemy BUILDERS and not everyone, especially knights. Knights should be a really big challenge if you want to fight them. It worked very well in the past I would say. Killing a knight was possible but not easy as it is now.

**_Removing 50% waste_** was one of the biggest mistakes, one of the reasons why we have stone stacks laying on the ground everywhere and decaying. You can have 500 stone, die and not care about it at all. 
The whole concept of having a drill was to give builders a way to gather stone quicker if really needed and 50% waste was a fair cost of it. This should be added back asap and not 25% waste or whatever - 50% was perfect.
It should not be possible or at least very rare that you can make a drill instantly and buy another one in less than 15 secs so you have another one if you die and respawn. 
**_More heat = more damage_** - it's kinda cool but bugged and OP in its current state. When on max heat you can literally insta kill. _It's hard and more of luck if your heat indicator bar is bugged but that's another thing._
I would leave that feature but nerf it significantly. I don't know how much damage it does now but it just should do slightly more (x1.5) when on max heat and that's just it. 
_**Overheating on wooden things**_ or rather not overheating on wooden things is another bullshit. Add it back as it was. Drill SHOULD be a **mining** tool - for mining **STONE** and not wood. Nerf so it overheats as in the past. 2-3 door/platforms and overheated.
_**Vamist's other suggestions**_ Not decaying in water - no. It still should. I know that water is used to cool it down but decay and heat are two different things. If you wanted to make it more realistic then don't tools get damaged over time when in water??? 

If you make it so drills do not decay in water then water rats will be even more OP. It was a cool thing to make air pockets and manage inventory if you want to carry a drill and it should stay like this. 
There is this misconception where almost everyone thinks that flooding big parts of the map, caves is actually helping with fighting the rats. It actually NOT. Defending from water rat is much harder and very often you are going to drown in the puddle you've created. 

**_Overheated drill setting things on fire_** - sounds fun but **DO NOT** add this. With this how common drills are, you will very likely have random fires because of that when people did not even plan to set things on fire. I can only imagine myself building a fast skybridge tower (wooden, 1 block thick) to get on top of the enemy tower, heating my drill on some wood/stone and setting the rest on fire. Same with going from underground. 
No.

At the end I want to say that the change with resupplies is something I like. Creates too much wood and stone but I think it would be good with all I suggested in this post.
Anyways, I expect nothing from this. The game is ruined thanks to those who want it to become a slaughterhouse simulator focused only on combat, killing each other and nothing more. CTF is slowly becoming a new TDM mode, thanks to you all.

### **_TLDR version_**
**Quarries**: make it so more wood (+25-50%) is needed to produce 75 stone which would reduce drill spam as well as wood overflow
**Add 50% waste** back to drills
Significantly **reduce the damage** they do **when heated**
**Increase** how fast drills **overheat on wooden things**
**AND DON'T FLIPPING TOUCH WHAT'S WORKING JUST FINE**

**Comment by Vam-Jam** [comment]
#704 working on drill changes, current list is 
- Damage is 1.0f
- Heat damage reduced to 0.5f (now deals 1.5f total)
- Mat drop to 75%, instead of 100% 
- Now overheats about 20/15% faster
- Ignores useless blobs so it doesnt heat up
- Doesnt decay in water

next thing i'll take a look at is quarries

**Comment by ewetcr** [comment]
Drills at its current state have taken away the skill-cap in several builder areas and have damaged the game balance. I've mained builder for around 8 years and I believe I know what I am talking about:

Issues: 

·    builder 1 v 1  = the one with the drill kills (just by holding LMB and aiming), not the more tricky or the more clever; This means the game is telling the players they don't need to think twice but to buy an item that gives you superiority over the other's skill (unless they have a drill)
·     1 v 2 = if you have a drill and the enemies don't you kill them 
·    gathering stone is almost free, and it gives you more stone so you can buy more drills (comments on Quarry after this part)
·    used with a tile of water means an endless tunneling (it's not a map design problem but what drills offer to play the map)
· a constant "hiss" sound, as usually there's somebody tunneling with it
· it has no natural counter (siege/arrows; bombs/shields etc)

What I propose:

· It gives you 50% of mats, but 100% of gold 
· Water cools it, but also damages it (would you toss some water on an overheated toaster?)
· It does nothing against shields
· At a point of overheatting it delivers the same damage to the carrier
· Make it more expensive (mostly more stone, as you'll get it fast)
· No added heat damage on enemies

The sound reason I've heard about buffing the drills this much is that  it would be a counter to those usual massive castles (built with or without skill, that's another story). Slicing through them shouldn't be that easy however, as it shouldn't be making well shaped castles.

Also, this brings into table Quarries, which were an addition the game never needed and adds to the problem of stalemates. Even at this very moment after being limited to 1 per team only, they got in the middle of some nasty balance issues:

· It first asks for gold that should be used for Teleporters or Siege Shops for choices on how to invest it should be important, then it gives free stone, as wood is never scarce in most of the maps. 

· More stone means thicker castles, more blobs to add to the CPU usage and hardly any skill for material management or inventiveness in building with few resources. Moreover, with the full amount of resupply added recently, this gets a bit worse. 

· Quarries, along with the addition of catapults throwing stones through platforms, provoke endless stone rain from catas. This means, and it's quite paradoxical, that you get more stone to build more, and you get more stone to destroy more. Stone for catapults and defenses should be a precious resource, similar to the comparatevely more expensive bomb bolts. Castles should be the result of creativity for the defense, shop keeping and friendly navigation.


This second part is problematic, and I would just suggest to remove quarries for good, but I understand how unpopular this could be. Map design with less gold and less trees to fuel the quarries or to limit the options sounds good to me too.

**Comment by DaS-21** [comment]
https://www.youtube.com/watch?v=KZWEOEiLOWA&feature=youtu.be

This is one of the random games I hoped on. Match time was around 3-5 minutes and this is how it looked like.
Good job on creating such a bullshit. Keep listening to people who want CTF to become a new TDM mode. Who don't even play regularly.. But well.. What can we expect if the "devs" don't do it as well? You literally do not know what you've created and what you're developing. 

Imma end it here and keep the rest for a steam review.

**Comment by Harrison-Miller** [comment]
Closing because this is out of date
