### ISSUE TITLE
KAG is not optimized for macOS High Sierra 10.13.4 and later

### ISSUE THREAD

**Issue by GeorgeOrlov1** [transhumandesign/kag-base#711]
**Description**
Hello! My name is George! 
I bought KAG 3 years ago. And KAG my favourite game.
Ohh... but I recently updated the operating system on my computer and now I can’t play this cool game... 
because when I try to enter the game I get a notification that the game is not optimized for my computer.

What can I do to continue playing the game? Preferably without Steam!!!
I always played not through Steam. I don't want to lose my account... 
but if I can play with my account via Steam then okay :((((( or no?

**Reproduction**

1. I'm trying to enter the game
2. I see notification, error 

**Expected Behavior**
I can enter the game

**Screenshots:**

<img width="132" alt="Снимок экрана 2019-10-09 в 03 59 11" src="https://user-images.githubusercontent.com/56326400/66443826-499c4100-ea49-11e9-8fe0-de5bcbfccc3f.png">

<img width="778" alt="Снимок экрана 2019-10-09 в 03 07 22" src="https://user-images.githubusercontent.com/56326400/66442836-31c2be00-ea45-11e9-8776-9673f5832257.png">

**My Setup:**
- OS: macOs Catalina version 10.15
- Build Number: ???
- CPU: 2,9 GHz, Intel Core i5 dual-core processor
- Graphics Hardware: Intel Iris Graphics 6100 1536 megabyte
- RAM: ???

**Additionally**
https://support.apple.com/en-us/HT208436

If it matters, my KAG username is "greoryuis"

**Comment by furai** [comment]
Hello,

There's nothing you can do about it other than running it in parallels in any MacOS that has 32 bit support. 

Catalina dropped support for 32-bit apps and we have to make KAG 64-bit which won't happen anytime soon. We'll most likely drop support for MacOS for foreseeable future.

Cheers,
Furai

**Comment by GeorgeOrlov1** [comment]
Thanks!! for the answer

**Comment by Trumbles** [comment]
I don't know enough to say anything on this :(
