### ISSUE TITLE
[Bug] Drill progress bar jittery when moving

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#712]
**Description**

Title

**Reproduction**

Walk with drill in hand

**Expected Behavior**

It should be buttery smooth

**Comment by furai** [comment]
I think also when riding vehicle name tags suffer from the same issue.

**Comment by Vam-Jam** [comment]
I had a PR that was reverted that fixed this issue. getInterp seems to have issues on a dedicated server.
