### ISSUE TITLE
combat basically broken at ping greater then 100

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#714]
currently in the game if a knight stabs a knight that is shielding or shields against a slash he is suppose to get stunned giving the you a chance to do damage.

however with a ping 100 or greater, this time is literally to small to do anything because by the time the packet reaches the server that the other person is attacking he is already out of stun stabbing you or ready to slash you.

I propose the following...

1. increase stun time just long enough for a player with a ping of at least 200 can do something and still have time do recover. that's literally 0.2 seconds or 400, 0.4 to register with the server.

2. something should be done with animations to check the validity with the server. maybe enough stun to actually check with the server and display and sync stun animation?

I'm not quite sure why this is a problem since I believe stun time is 0.5 seconds however it makes the game competitively worthless if you don't live in a city where the server is hosted.

I literally live in usa organ and can't play on us west servers without being unable to attack players and see their animations

**Comment by Shadowblitz16** [comment]
this has happened again today I can't hurt anyone and slash takes me 2 times longer to charge then anyone else. sometimes I wonder if someone increased charge time in recent updates.

I literally can't hurt anybody on the other team due to the horrible lag.
stabbing used to work well when lagging but something has changed and now they don't seem to do anything.

**Comment by Harrison-Miller** [comment]
This is not to do with a change in the games code. Though kag does have poor networking, issues like this are generally related to packet loss which is not something we can control. The best course of action is to monitor your network health latency/packet loss and complain to your ISP. I would also suggest making sure to play on regional servers.
