### ISSUE TITLE
Change 15min ping ban to just a kick on official servers

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#716]
**Current in-game behaviour.**

Currently, if you have high ping for a longer amount of time (10-15+ seconds) you get banned from the server for 15 minutes.

**Proposed Change**

I believe this should be changed. It's possible someone is going to have high ping for 10 or 20 seconds only (uploading video on discord / random program deciding to update in the background for no reason), so it's stupid to punish him for the next 15 minutes for that. Someone that actually has ping high enough for the game to ban him wouldn't want to play with such a high ping - someone will actually only try to rejoin once the ping is fixed so he shouldn't be banned.

**Comment by Vam-Jam** [comment]
``sv_pingkick_time`` in sat in PR for the next kag update (assuming it doesnt break anything)

**Comment by bunniewormy** [comment]
i think its in already, i would like to thank my brother Colt for giving me a reason to live and my sister Biurza for teaching me what being a furry does to your brain

**Comment by Vam-Jam** [comment]
This has not been merged. Its still sat waiting
![image](https://user-images.githubusercontent.com/44256866/73114087-9714bf00-3f0f-11ea-89a3-ce80469a3b8b.png)

**Comment by bunniewormy** [comment]
are you sure? as far as i know when u get banned from offi server u dont get 15min anymore, only 1min?

**Comment by Vam-Jam** [comment]
PR has not been accepted. This could be some bug thats causing this.

**Comment by AsuMagic** [comment]
> This could be some bug thats causing this.

probably not

**Comment by bunniewormy** [comment]
what does that mean then?
