### ISSUE TITLE
Add small CTF to officials

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#717]
It would be nice to have a more action packed CTF (but also a more crazy one)

Tiny/small CTF: 
1. Small maps
2. Short build timer
3. Max pop 16
4. coinloss on death reduced
5. short spawn timer
6. add bomber airship, superkeg, and some other epic stuff.
7. Make team colours: green vs purple (giving it a unique colour for small ctf mode)
Any thoughts?

**Comment by MatheusGodoi** [comment]
I really like the idea! Just my toughts on each point:
1. Small maps are awesome and its already proven to get a decent number of players
2. Yes please no need to build for 3 minutes on a small map
3. Maybe its too small and people would complain about it? Everyone hates having to wait to join a populated server, and that would make it easier to fill. Maybe 18, 20 or even 16 is fine, just trying to know imo.
4. Yes please
5. Yes please (not too much tho)
6. Yes please, airship seems a bit busted for small maps tho
7. YES PLEASE FOR THE LOVE OF GOD WE HAVE LIKE 8 DISTINCT TEAM COLORS BUT ALL GAMEMODES except moddeds USE THE SAME 2 COLORS PLEASE MAKE IT HAPPEN

**Comment by Trumbles** [comment]
I'm all for more game modes. Sounds awesome.

**Comment by Vam-Jam** [comment]
Closed as small CTF is sat in PR and is being ready for future updates officialy
