### ISSUE TITLE
More armour/weapon skins for patreons

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#718]
To make patreon more attractive make more skins. (for royal supporters)
We already have some good looking skins in mods, not that we have to copy it. 
Viking armour/weapons would make for a good start and maybe some black armour/weapons
If this is accepted we just need a artist that can make some good looking skins.
You can pay them with permanent royal supporter perks if no money is available. or heck i even put in some money if i have to

**Comment by MatheusGodoi** [comment]
Please do, patreon rewards are sad like they are. New weapon colors would be ez to make as there is already the gold ones, some small changes in designs would not be a big problem (not that I know much about sprite making tho). Armor colors would be awesome too, all the characters have enough color or them to be differentiable.

**Comment by Trumbles** [comment]
Patreon needs to be beefed up if we expect to rely on it in any way whatsoever. I am 100% all for adding things to it.

It should also have different tiers of donation.

**Comment by Harrison-Miller** [comment]
any additional armor sets anything require changes to the scripts and to the engine as well as art.

**Comment by Harrison-Miller** [comment]
This is basically a duplicate let's move the discussion to a single issue: https://github.com/transhumandesign/kag-base/issues/487
