### ISSUE TITLE
Force all players to be a builder until the last 20 seconds of warmup

### ISSUE THREAD

**Issue by Vam-Jam** [transhumandesign/kag-base#738]
I need my team mats

thank you for coming to my ted talk

**Comment by Shadowblitz16** [comment]
there should probably be text displaying info about when you can and can't switch

**Comment by Panky123** [comment]
'Swap classes' when timer reaches 20 seconds

**Comment by Shadowblitz16** [comment]
or it could be something like...
you can swap classes in <time from 20 seconds>

**Comment by bunniewormy** [comment]
People who are too lazy to build will still be too lazy to build, if anything this will make more people minecraft and build art/houses or whatever

**Comment by Vam-Jam** [comment]
At least they are doing something. And from what ive seen, this really isnt the case, theres been mods that force this in the past, and its worked fine.

**Comment by Trumbles** [comment]
Not a bad change per se. Pubs are for messing around though. Is there really a need to enforce strict rules on them? We can do that with tutorials.

**Comment by Harrison-Miller** [comment]
Make this controlled by the ctf vars file.

**Comment by Gingerbeard5773** [comment]
This can also be closed like the PR was
