### ISSUE TITLE
Allow admins to see what’s in a players inventory while in !m

### ISSUE THREAD

**Issue by 123dino** [transhumandesign/kag-base#739]
**Describe the feature**
Allows you to see what’s in a persons inventory to help prevent people from jumping into the void with tons of gold or tree seeds.

**Additional context**

**Comment by Trumbles** [comment]
No. Just mod properly instead.

**Comment by bunniewormy** [comment]
kinda hard to watch 23 people at once to make sure noone is throwing a seed into the void when you cant even see their inventory...

**Comment by Harrison-Miller** [comment]
Interesting feature pitch, but extraordinarily hard to implement and probably wont be useful most of the time.

**Comment by AsuMagic** [comment]
@Harrison-Miller since we're talking about mod tools, we probably don't need a fancy GUI, and just an inventory name+quantity list should be enough. (Looks like you can loop over inventory blobs quite easily, too)
