### ISSUE TITLE
Upgrade main title screen to modern standards (the art)

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#749]
(Click on pictures to see bigger versions)
Main title screen is the first thing people see when they open the game, and it doesn't really look good (even in 1080p - not to mention higher resolutions). It was made in 2013 standards I guess (1280x768), while nowadays people have much bigger screens

1080p:
![image](https://user-images.githubusercontent.com/39147836/71301488-f840f400-239f-11ea-9a7b-e6ed95f0680a.png)
![image](https://user-images.githubusercontent.com/39147836/71301490-fbd47b00-239f-11ea-93f9-9e47e446c3da.png)

1440p:
![image](https://user-images.githubusercontent.com/39147836/71301492-0131c580-23a0-11ea-8a5f-30c5fac05adc.png)
![image](https://user-images.githubusercontent.com/39147836/71301497-04c54c80-23a0-11ea-8f41-d621918cc0f9.png)

My suggestion is to somehow upgrade it to modern standards. As an example, I've made the original image (1280x768) twice bigger and changed the median in paint.net (it even works in-game)

Original:
![image](https://user-images.githubusercontent.com/39147836/71301506-19a1e000-23a0-11ea-922c-792d5721965c.png)

Edited:
![image](https://user-images.githubusercontent.com/39147836/71301511-20c8ee00-23a0-11ea-866f-037dcfd35ae7.png)

It's kind of a temporary solution, but it already looks much better:
![image](https://user-images.githubusercontent.com/39147836/71301520-2f170a00-23a0-11ea-9847-778a96532568.png)

![image](https://user-images.githubusercontent.com/39147836/71301523-350ceb00-23a0-11ea-88c4-8337812ac788.png)

The title text could also use a upgrade, however:
![image](https://user-images.githubusercontent.com/39147836/71301527-4229da00-23a0-11ea-8cf3-7bdf1628b47d.png)

I think the website version could work well here - it's much higher quality:
![image](https://user-images.githubusercontent.com/39147836/71301533-5077f600-23a0-11ea-83bc-9ae610bf6636.png)

![image](https://user-images.githubusercontent.com/39147836/71301678-a3eb4380-23a2-11ea-89e1-845fae1c5fb8.png)

I'm no photoshop master and someone could probably do it much better than me, but after some edits this is what I got:

After:
1920x1080
![screen-19-12-21-03-30-33](https://user-images.githubusercontent.com/39147836/71301670-8e761980-23a2-11ea-82c8-d0133bd33084.png)
2560x1440
![screen-19-12-21-03-31-02](https://user-images.githubusercontent.com/39147836/71301671-8e761980-23a2-11ea-9957-85d6a0c25437.png)
1600x900
![screen-19-12-21-03-31-37](https://user-images.githubusercontent.com/39147836/71301672-8e761980-23a2-11ea-821b-bfb59490ac1f.png)

Before:
1920x1080
![screen-19-12-21-03-34-06](https://user-images.githubusercontent.com/39147836/71301691-d2691e80-23a2-11ea-9149-bba037370c0a.png)
2560x1440
![screen-19-12-21-03-33-54](https://user-images.githubusercontent.com/39147836/71301696-e44ac180-23a2-11ea-9106-8de2fba6f081.png)
1600x900
![screen-19-12-21-03-34-21](https://user-images.githubusercontent.com/39147836/71301693-dc8b1d00-23a2-11ea-8bdd-932b3ec2d7a7.png)

@Edit: I don't really know how it really works regarding resolutions and stuff like that, but I guess if we made the resolution bigger something in the launcher would have to be edited:

![image](https://user-images.githubusercontent.com/39147836/71301776-ee20f480-23a3-11ea-9ff0-b671ab4a5f7d.png)

**Comment by AcrylicOracle** [comment]
that, and also i want gifs when you hover over the main menu buttons. this menu is super still and makes the game seem old no matter what resolution it is

**Comment by 123dino** [comment]
Imo it needs to be reorganized. the buttons should be in the center, and a lot of that stuff could be under an information tab or something.

**Comment by AcrylicOracle** [comment]
kag supports transparency, you've seen it at least in mods like territory control. i do really like the solid buttons though, and while i think the menu should be more animated, the rigid aesthetic needs to be preserved.

**Comment by AsuMagic** [comment]
The transparency wouldn't look quite right on the buttons IMO. Updating the background and title would be a good idea IMO, though as for the background I have been getting better results using waifu2x upscaling.
FWIW in my branch the launcher is killed (other than autoupdate, which doesn't feature the title) so it would not be a worry then.

**Comment by Panky123** [comment]
Holiday themed backgrounds(and just in general changes from time to time) would be awesome.

**Comment by Omen267901** [comment]
I'd agree to stick to the fully solid buttons, but more animation would be excellent. I like the simplistic and straightforward menu, but it is VERY static and uninteresting atm.

**Comment by Trumbles** [comment]
This was a good change, the main menu is nice to look at.
