### ISSUE TITLE
Checking for a script being attached to a blob

### ISSUE THREAD

**Issue by Pirate-Rob** [transhumandesign/kag-base#78]
Feature request:
Currently, there is no way to check if a script is attached to a blob.
A simple ".hasScript(string)" would be a nice feature.

**Comment by 1bardesign** [comment]
Shouldn't be impossible (tho won't be particularly cheap), will likely get around to this in the next month or two.

Should the string be the `ScriptName.as`, the `Full/Path/To/Script.as`, or would multiple versions be useful? I imagine the path would "break" certain stuff when mods were used, but might also be possible for "detecting" mods being used?... I'm not sure if that's useful at all though.

**Comment by Pirate-Rob** [comment]
Preferably "ScriptName.as" without the path, but any more functions are always nice though!

Detecting mods may be useful for anti theft or version checking, but not sure if there's anything else it could be used for. (I doubt this functionality is important, and if it is, it would probably better to have it's own script)

**Comment by 1bardesign** [comment]
This is done for next build - `bool T::hasScript(const string& filename)`; the argument should be normalised exactly the same as `AddScript` and `RemoveScript` are.
