### ISSUE TITLE
Flag return timer freezes 1-2 seconds before flag returns

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#782]
1. Join CTF
2. Pick up the enemy flag
3. Drop it on the ground and wait for it to return
4. A few seconds before flag returns, bar that shows how much time is left before flag returns will freeze

**Comment by Harrison-Miller** [comment]
I don't think this is really a bug with the scripts so much as an issue with how progress bars work in the game. They use whats called a 9 patch rect. and I think that is the smallest it can be drawn.
