### ISSUE TITLE
Make sponges re-usable after a certain duration of time

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#789]
Currently if you get stunned twice by a water arrow or bomb, the sponge dies. If you use a sponge to absorb water blocks, there's also a limit before the sponge becomes full.

The idea is that after a certain amount of time, the sponge could become re-usable.  This way you could put used sponges in storage to reuse them later.

Could be 2-3 minutes.

**Comment by Nananas** [comment]
FYI, sponges dry when in fire, or close to a fireplace. We could extend this in a way, so they don't fill up storage?

**Comment by Harrison-Miller** [comment]
There's no fireplaces in CTF I think the idea is for them to work similar to drill cool down. Which also works while in inventory.
