### ISSUE TITLE
Make the game more beginner friendly

### ISSUE THREAD

**Issue by Azzwor** [transhumandesign/kag-base#793]
Kag button tutorial is kinda hidden,new players join on kag get smashed and quit, the game tutorial ins't forced enough they have to learn by then selves,and if they won't read the sings they can beat tutorial only hoping around with knight,despite the fact that the sings break.

Today i was on the kag server list when i saw a server done by an streamer, that had kag classic experience, he had two more friends that joined just to play some TDM with him, they didn't had the tutorial so i tried to show some base game mechanics like slashing and all,don't learned anything,  after some time we played TDM but it got boring, you know TDM has some monotony, so i tried to show them the CTF gamemode, they couldn't do anything, they dindn't had the tutorial, at the start it was a private server cuz they didn't wanted to get rekt but they gave a chance and played on CTF EU, and got to an point that they could'nt play the games the veterans was smashing them, they work build , wont kill, won't sap nothing, just a thrash match. the sad part: i told them to give a try to the tutorial, he just gone into and skipped totally,won't read any sings and got thru. the point is that some players some players just enter the game die to people in the servers and quit,and call the game bad cuz they don't learned anything on the run. 90% of the player base at least know some of the game. and the beginners won't stay much longer.

**Comment by Harrison-Miller** [comment]
I think making the tutorial button a top level button instead of grouped with solo is a good idea.

I am however going to close this issue because it just reiterates the point that we need better tutorials see this issue: https://github.com/transhumandesign/kag-base/issues/679 for additional discussion.
