### ISSUE TITLE
Make it possible to buy stuff from quarters while sleeping

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#799]
Every time you accidentally go to sleep instead of opening buy menu in quarters, you have to press W to stop sleeping before you can actually open it. Is annoying, wastes time, please change.

**Comment by eps0003** [comment]
#640 changed it so you can't open the shop while sleeping. Even before this change, you could only open the shop but not buy anything.

**Comment by Harrison-Miller** [comment]
Yeah I don't think the behavior needs to be changed for this. It makes a lot of sense that you can't open menus while sleeping.
