### ISSUE TITLE
Improve voting UI

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#837]
1. Dont make vote window disappear after voting.
2. Show the amount of for/against votes in the voting window.
3. Allow admins to force votes they've already voted in. It's annoying when you cant cancel a vote because you accidentally pressed P instead of Ctrl+P
4. Remove "asda voted for" "adsa voted against" chat spam, but keep some way of logging who voted for/against.
5. Make it possible to change your vote? May not be a good idea

**Comment by KrakenZ** [comment]
Votes should only be visible once you voted (or after the end of votes) as it can affect player's decision
