### ISSUE TITLE
f32 CSprite::GetZ()

### ISSUE THREAD

**Issue by Pirate-Rob** [transhumandesign/kag-base#84]
Currently, there is no way to check what's the current Z-Level of a sprite. A function like this would be incredibly useful when dynamically setting z values of sprites.

**Comment by 1bardesign** [comment]
Done, is in the next build and refers to the same Z set by SetZ. it's actually called `CSprite::getZ()` for consistency with the existing getters/setters which for whatever reason use UpperCamel for the setter and lowerCamel for the getter (I think it has to do with return values but MM would have to clarify tbh)
