### ISSUE TITLE
Remove ballista explosive bolts upgrade

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#841]
Remove the upgrade in siege shop. Make explosive bolts a seperate material. Make it possible to buy explosive bolts seperately in the siege shop (100 coins for 12 normal bolts, 100 coins for 6 explosive bolts? maybe less coins for normal bolts?). Add a way to swap between the bolts for person currently in ballista.

2017 Fuzzle gifs:

https://media.discordapp.net/attachments/337266863841214465/353210452169457665/mems.gif

https://media.discordapp.net/attachments/337250580303052801/344280131684139019/new.gif

**Comment by Harrison-Miller** [comment]
Tap f to cycle bolt type while in gunner seat.

**Comment by CatWiz** [comment]
also add some way to tell if a ballista is going to shoot an explosive bolt of a normal one

**Comment by Harrison-Miller** [comment]
yeah probably similar to the UI for the knight/archer special ammunition.
