### ISSUE TITLE
::isServer()and ::isClient()

### ISSUE THREAD

**Issue by Pirate-Rob** [transhumandesign/kag-base#85]
One of the most common lines of code across kag base and mods is `if(getNet().isServer())`. Being able to call `isServer()` without `getNet()` would be a nice QoL improvement.

**Comment by Pirate-Rob** [comment]
Actually, I just realised an even better improvement would be to make them global variables instead of functions, even less typing then!

**Comment by 1bardesign** [comment]
I've done this for next build, but I'm not making them global variables _or_ global constants as I'm not sure if the AS script compiler will attempt to optimise based on them if that is the case; and they may change over the lifetime of the program.

Global functions I can do though 👍
