### ISSUE TITLE
Chat history should only remember first occurence of identical messages

### ISSUE THREAD

**Issue by eps0003** [transhumandesign/kag-base#852]
**Describe the feature**

Chat history remembers every single message you sent, regardless of if a message is identical to the previous one. This is pointless. It should only remember the first of these messages.

**Examples:**

Messages sent:
> foo
> foo
> bar
> foo
> foo

Current chat history:
> foo
> foo
> bar
> foo
> foo

Proposed chat history:
> foo
> bar
> foo

**Comment by eps0003** [comment]
Just to clarify, when I say 'chat history', I mean your history of sent messages when you press up/down while chat is open.

**Comment by Vam-Jam** [comment]
Nananas added this last update
