### ISSUE TITLE
CBlob::getOldPosition()

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#86]
Please add a a way to get a CBlobs position from the previous Tick changed for the current onTick() frame.

I have tried to use ShapeVars::oldpos  but it is either buggy or is not the same.

This would allow people to override forces applied to the blob on that tick without setting it to be static.
It would be initialized as the blobs position and would be applied before the blobs new position is updated to avoid issues.

**Comment by Pirate-Rob** [comment]
What's the point of this though? You could just save it yourself no? This feature means you'd be forcing every blob to save their previous position, which can add up once you have a lot of blobs.

**Comment by Shadowblitz16** [comment]
I don't think its even possible to save the old position before velocity is applied.
no matter what you do the other force upon the blob still push it around a little bit.

this would be a way to completely bypass this and it shouldn't take too much resources to add 1 vec2f
it also is more confusing when the player see's a way to get the oldVeleocity but no way to get the oldPosition and when something like this should be simple to get.

**Comment by Shadowblitz16** [comment]
updated the request to be per tick instead of everytime the position gets changed

**Comment by 1bardesign** [comment]
`ShapeVars::oldpos` is the only thing we have - it's not really clear what you mean "not the same".

I've created a pass-through function `CBlob::getOldPosition` for next build - it does the same as the current `CBlob::getPosition` does for position, but for the old position. Both are just pass-through reads into the `ShapeVars`.
