### ISSUE TITLE
Manual Position clarification

### ISSUE THREAD

**Issue by Pirate-Rob** [transhumandesign/kag-base#87]
Semi-Recently the manual was updated so that it includes the argument names of each function. I think this could be improved by updating all methods' position arguments to specify whether it requires tile position or world position.

**Comment by 1bardesign** [comment]
How do you see this being done + what functions need changing?

I think almost everything is in world position other than those which have specific reference to tile space already in their function names.

**Comment by Pirate-Rob** [comment]
There are a LOT of ambiguous functions, map being the worst (only?) offender.

I would simply rename the vars in the manual(or source, since apparently manual is generate from that?) to worldPos or tilePos (or startWorldPos for things like raycast).

Examples (all from CMap):
- hasSupportAtPos(Vec2f offset)
- server_DestroyTile(Vec2f pos, float damage)
- isInFire(Vec2f pos)
- isTileSolid(Vec2f p)
- rayCastSolid(Vec2f start, Vec2f end)
- isBelowLand(Vec2f pos)

So you can see all of these use different names, which can be confusing, and there's often doubt as to what they use, often times leading to modders having to do weird checks just to make sure they're using the right measurement.

Almost all functions in CMap that don't have it defined in their name would need to be changed I think. I don't think functions outside of CMap need to be changed as CMap is the only class that works with tiles.

**Comment by AsuMagic** [comment]
Indeed the manual is dumped from registered stuff on the AS side in the engine.

Solved in engine (engine pr 64)

**Comment by AsuMagic** [comment]
Example snippet:

```angelscript
bool hasSupportAtPos(Vec2f posWorldspace)
void server_DestroyTile(Vec2f posWorldspace, float damage)
void server_DestroyTile(Vec2f posWorldspace, float damage, CBlob@ damager)
void server_setFloodWaterWorldspace(Vec2f posWorldspace, bool water)
void server_setFloodWaterTilespace(int xTilespace, int yTilespace, bool water)
void server_setFloodWaterOffset(uint offset, bool water)
void server_setFireWorldspace(Vec2f posWorldspace, bool fire)
void server_setFireTilespace(int xWorldspace, int yWorldspace, bool fire)
```

**Comment by AsuMagic** [comment]
Implemented for a while now
