### ISSUE TITLE
Opening scoreboard while holding RMB copies someone's username

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#871]
1. Hold RMB, aim mouse somewhere around the centre of the screen
2. Open scoreboard
3. Someone's name will be copied
It shouldnt work like that because you copy usernames accidentally all the time

**Comment by Shylie** [comment]
This feature was requested by admins for convenience of administration. As such, I disagree with removing the feature, although I can see using RMB to copy the name not being the best. Perhaps change the key to copy?

**Comment by CatWiz** [comment]
I never said anything about removing it. I just want it to not copy a name if you pressed RMB before you opened the scoreboard.

**Comment by Shylie** [comment]
My bad. I misread the issue.

**Comment by AsuMagic** [comment]
It's easy to accidentally copy stuff in general in the scoreboard anyway.

To get rid of most false positives it should be done so that copying an username only happens if you pressed LMB while the scoreboard is open and released it without having moved your username to another user.
