### ISSUE TITLE
void SetFirstAvailableBomb in KnightLogic.as

### ISSUE THREAD

**Issue by longwoodbow** [transhumandesign/kag-base#879]
Now, if you selected bomb and have only water bomb...:
u8 type = 255;
if (this.exists("bomb type"))
type = this.get_u8("bomb type");// now type is 0

CInventory@ inv = this.getInventory();

bool typeReal = (uint(type) < bombTypeNames.length);
if (typeReal && inv.getItem(bombTypeNames[**type**]) !is null)// don't return because bomb is null
return;

for (int i = 0; i < inv.getItemsCount(); i++)//start, i is 0 and check first item
{
const string itemname = inv.getItem(i).getName();
for (uint j = 0; j < bombTypeNames.length; j++)
{
if (itemname == bombTypeNames[j])
{
type = j;
break;
}
}// hmm.. first item is not a kind on bomb...

if (type != 255)// type is 0 and not 255, so it's true
break;// wait, how about second and other items?
}

this.set_u8("bomb type", type);
so, water bomb will be selected if when it's in first only.
So it's better:

u8 type = 255;
**u8 nowType = 255;**
if (this.exists("bomb type"))
nowType = this.get_u8("bomb type");

CInventory@ inv = this.getInventory();

bool typeReal = (uint(nowType) < sprayTypeNames.length);
if (typeReal && inv.getItem(sprayTypeNames[**nowType**]) !is null)
return;

for (int i = 0; i < inv.getItemsCount(); i++)
{
const string itemname = inv.getItem(i).getName();
for (uint j = 0; j < bombTypeNames.length; j++)
{
if (itemname == bombTypeNames[j])
{
type = j;
break;
}
}

if (type != 255)
break;
}

this.set_u8("bomb type", type);

**Comment by eps0003** [comment]
I tried looking into this. I have no clue what this changes. Please elaborate.
