### ISSUE TITLE
When doors are damaged by bombs, then opened, then closed, they will appear to be at full health even though they actually are damaged

### ISSUE THREAD

**Issue by Hobey** [transhumandesign/kag-base#881]
Video of the current behaviour on a server: 
https://youtu.be/C3snrFSLcnk

This happens when playing on a server; it doesn't happen in local sandbox.

**Comment by Trumbles** [comment]
This is important to fix IMO. Knowing the damage state of doors is a big deal.

**Comment by Shadowblitz16** [comment]
nice title
