### ISSUE TITLE
1 tile of water does not extinguish player

### ISSUE THREAD

**Issue by soren-null** [transhumandesign/kag-base#902]
**Current in-game behaviour.**

Standing in 1 water tile is not enough to extinguish yourself.

**Proposed Change**

Standing in 1 water tile should be enough to extinguish yourself.

**Additional context**

![Fire](https://user-images.githubusercontent.com/68282824/92384500-de576500-f118-11ea-8e36-00f6563e75b5.PNG)
![Water](https://user-images.githubusercontent.com/68282824/92384603-0ba41300-f119-11ea-89f4-e084919870f8.png)

**Comment by Vam-Jam** [comment]
Closed as Nananas did this last kag update
