### ISSUE TITLE
Suggestion: Make tree sapling drop earlier

### ISSUE THREAD

**Issue by Hobey** [transhumandesign/kag-base#903]
Make tree sapling drop when the tree starts falling (instead of when the tree hits the ground or a wall), so that you can immediately pick up the sapling before there are logs next to the sapling.

Potential downside:
Might make drilling a small tree + a big tree next to each in a tree farm more annoying, since a sapling (the one from the small tree, which is gonna be on the ground before you are done drilling) will be on the ground and add extra heat to the drill.

**Comment by eps0003** [comment]
> Make tree sapling drop when the tree starts falling (instead of when the tree hits the ground or a wall), so that you can immediately pick up the sapling before there are logs next to the sapling.

You can just hold shift while picking up to select the sapling.

> Might make drilling a small tree + a big tree next to each in a tree farm more annoying, since a sapling (the one from the small tree, which is gonna be on the ground before you are done drilling) will be on the ground and add extra heat to the drill.

The drill won't interact with the dropped sapling because it takes time for the sapling to plant into the ground and start growing.
