### ISSUE TITLE
force update and force render function for possible map wrap mod?

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#94]
can a force update and force render function be added to kag?
it would be a good way to make mod where maps loop. 
logic would go like this..
- check if player is intersecting edge of map if so then..
 - update, collision and render
 - move player to other edge 
 - update, collision and render
- move player back

this would also require a camera edit too but i'm sure its possiable

**Comment by 1bardesign** [comment]
The visual aspect of this _could_ be handled with the script rendering freedom stuff, though on net you don't actually have the positions of all blobs properly up to date, _especially_ ones on the other side of the map.

Ability to render a blob's sprite layers as if the blob was at a specific position may be possible to add once the custom rendering stuff is in (needs that first so scripts can be called at a z-buffering-aware point in time).

In general though "no", the rest of this is not going to be added as it will interact badly with the networking code and open up even more latency sensitive physics interactions. Looping with seamless physics and interactions generally requires pretty hard integrated support with all systems (eg hitting code would need to know about it, camera needs to change, etc). We're not likely to add native looping support to KAG as it stands - it's a very specific feature.

---

If this is to help with multi-team, multi-direction CTF (as I think you have been working on), you would be better to put all teams in separate bedrock-enclosed areas and provide indestructible teleporters inside no-build-zones at the edge of each team's area. That'd provide the simplest gameplay and you could randomise the order of connections between regions at the start of the game, to provide variation to the neighbours.
