### ISSUE TITLE
Spectators shouldn't take up server slots

### ISSUE THREAD

**Issue by laws65** [transhumandesign/kag-base#954]
**Current in-game behaviour.**
Currently, when players spectate, they take up a server slot. I think this is bad since players can just sit in spec AFK, not letting our people join, or can fill up a server with alts. Additionally, when OKSA are spectating, watching out for griefers they take up slots and that can make certain community members quite annoyed.

**Proposed Change**
When people spectate, they shouldn't take up a server slot.

**Comment by Vam-Jam** [comment]
related to #827
