### ISSUE TITLE
CMixer Custom Music Tracks

### ISSUE THREAD

**Issue by MonkeyFeats** [transhumandesign/kag-base#96]
Due to a bug with the file matching, custom mixer/music tracks won't load.
A work around for this is to insert the full file path of your sound file, like so.

if (getMixer() !is null)
{
	getMixer().ResetMixer();
	getMixer().AddTrack(**"../Mods/MyMod/Entities/Sounds/BeachWaves_Ambient.ogg"**, 0);
	getMixer().PlayRandom(0);
}

**Comment by AsuMagic** [comment]
Sounds like it's not using the file matcher at all, is it?

**Comment by MonkeyFeats** [comment]
I should note that there was no error for an un-found file, just it couldn't load it.
If you just use the file name it will give you this.

![trackerror](https://user-images.githubusercontent.com/38561388/39055870-9fdfda42-44f8-11e8-93b1-174aaf6f058f.png)

**Comment by 1bardesign** [comment]
Fixed next build 👍
