### ISSUE TITLE
Revert all recent pickup changes

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#972]
First of all ones from halloween update, but i personally would be happy about reverting all the way back to pre pickup wheel update mechanics (keep the wheel itself, but revert changes done to normal pickup system).

**Comment by AsuMagic** [comment]
The older pickup logic had a few things that this update fixed IIRC, e.g. team pickup logic being reversed. There might be some more room for improvement in pickup still, and probably requires reviewing the code a little again
