### ISSUE TITLE
Archer Grapple Issue

### ISSUE THREAD

**Issue by MonkeyFeats** [transhumandesign/kag-base#99]
If there is a solid tile against the top of a map, grappling up/out of the map registers a hit on said tile. 

Continuing to grapple upwards whilst moving away from the wall allows you to grapple higher and higher. Once you have grappled really high above the map, moving back into the wall will cause your character to be propelled away, sometimes at very high speeds. 

![archergrapplebug3](https://user-images.githubusercontent.com/38561388/39693316-f3e688da-5226-11e8-81f5-b3a3cc554e0b.gif)

**Comment by GoldenGuy** [comment]
this can be easily fixed by making grapple disappear if it reaches top border (such as with left and right ones)

**Comment by MonkeyFeats** [comment]
I was gonna say, since it would be annoying to not be able out of the top of the map. It's probably better to only deny a grapple hit if it's the grapple's max length above the map.
(If that's how it works of course)

**Comment by AsuMagic** [comment]
I wouldn't make the grapple cancel when hitting over the topmost block, only force it to hook to that block. That should work around the issue better because this way you still can grapple the top of the map fearlessly.

**Comment by norill** [comment]
disappearing grapple at map edge is annoying, often causing archers to fall into void when they touch the edge

**Comment by AsuMagic** [comment]
Fixed by #115

**Comment by 1bardesign** [comment]
Needs further testing but optimistically marking this as closed for now.

We can reopen if appropriate.
